### ISSUE TITLE
CameraRoll.save(path, { type, album: 'New album' }) : create the album if it doesn't exist

### ISSUE THREAD

**Issue by johanschram** [react-native-cameraroll/react-native-cameraroll#107]
# Feature Request

Currently, on IOS, when you use CameraRoll.save(path, { type, album: 'New album' }) with an album that doesn't exist, the media is not stored. 
On Android simulator, if the album doesn't exist, it creates it, and stores the media (doesn't seems to work on real devices thought).

It would be nice to have the album created if is doesn't exist.

**Comment by bartolkaruza** [comment]
Happy to review a PR for this :)
