### ISSUE TITLE
only requiring NSPhotoLibraryAddUsageDescription

### ISSUE THREAD

**Issue by dtheodor** [react-native-cameraroll/react-native-cameraroll#108]
I want to use this library just to save an image to the camera roll, not to retrieve images from any photo library. As far as I can tell it's not possible to do this with the proper least-intrusive permission of additions-only, the `NSPhotoLibraryAddUsageDescription`, instead I have to ask the user for full photo library usage. Is there a reason why this is so?

**Comment by bartolkaruza** [comment]
Hi there, I think the reason is that NSPhotoLibraryAddUsageDescription was added as a new permission by Apple after the original implementation of the Cameraroll, but I'm not 100% sure. I think it would be great to ask for the least required permissions, requesting the user for write-only on `save` calls and read on `getPhotos`. Would you be interested in contributing this?

**Comment by chip-astg** [comment]
> I think it would be great to ask for the least required permissions, requesting the user for write-only on `save` calls and read on `getPhotos`. Would you be interested in contributing this?

According to the CameraRoll documentation, write-only permissions should already work if you have them (but my testing shows it doesn't, you get error  `Access to photo library was denied`):

_If you are targeting devices running iOS 11 or later, you will also need to add the NSPhotoLibraryAddUsageDescription key in your Info.plist. Use this key to define a string that describes how your app will use this data. By adding this key to your Info.plist, you will be able to request write-only access permission from the user. If you try to save to the camera roll without this permission, your app will exit._

![IMG_2573](https://user-images.githubusercontent.com/68605120/99806514-211bbd00-2b0c-11eb-8b57-9434fee56d9a.PNG)

**Comment by brsaylor2** [comment]
Possible duplicate of #292

**Comment by Arjan-Zuidema** [comment]
I think the library will ask for permissions when you try to save to the camera roll. What is the code you have to save a photo to the camera roll?

**Comment by hussnainshafiul** [comment]
I am downloading the video from an ip camera which is downloaded to DocumentDir , and then trying to save in photos (which is working fine on android) but Ios shows error:

"The operation couldn't be completed (PHPhotosErrorDomain error 3302)"

This is my code to download the video:

const handleDownload = async filePath => {
const videoPath = filePath.split('A:')[1].replace(//g, '/');
const vUrl = http://${selectedCamera.ip}/${videoPath};
const {config, fs} = RNFetchBlob;
const downloads = Platform.OS === 'ios' ? fs.dirs.DocumentDir : fs.dirs.DownloadDir;

const tsFilePath = ${downloads}/${videoPath.split('/').pop()};
const mp4FilePath = tsFilePath.replace('.TS', '.mp4');

// Check if the video is already downloaded
const storedDownloads =
JSON.parse(await AsyncStorage.getItem('downloads')) || [];
const isAlreadyDownloaded = storedDownloads.some(
video => video.filePath === mp4FilePath,
);

if (isAlreadyDownloaded) {
Alert.alert(
'Already Downloaded',
'This video has already been downloaded.',
);
return; // Exit the function early
}

// If not downloaded, proceed with download
setTimeout(() => dispatch(DownloadLoader()), 700);

try {
const response = await config({
fileCache: true,
path: tsFilePath,
}).fetch('GET', vUrl)
.progress((received, total) => {
const progress = received / total;
setDownloadProgress(progress); // Update progress
});

await FFmpegKit.execute(-i ${tsFilePath} -c copy ${mp4FilePath});

await fs.unlink(tsFilePath);

/*saving the file in albums */

let savedUri = null;
try {
savedUri = await CameraRoll.save(mp4FilePath, {type: 'video'});
Alert.alert('Saved to Photos ', 'Video has been saved to your Phone Album');
console.log(savedUri);
} catch (saveError) {
Alert.alert(
'Save Failed',
Failed to save video to Photos: ${saveError.message},
);
}

const downloadedVideo = {
name: mp4FilePath.split('/').pop(),
filePath: savedUri,
url: vUrl,
};
dispatch(addToDownloads(downloadedVideo));

storedDownloads.push(downloadedVideo);
await AsyncStorage.setItem('downloads', JSON.stringify(storedDownloads));

console.log(downloadedVideo);

} catch (error) {
Alert.alert('Download Failed', Error: ${error.message});
} finally {
setTimeout(() => dispatch(DownloadLoader(false)), 700);
}
};

issue is not with file extension , it is (.mp4) , checked on android as well
I have given necessary permissions also in info.plist , still I am receiving this error on ios
any solutions? for this

packages:
"react-native": "0.74.2",
"rn-fetch-blob": "^0.12.0",
"@react-native-camera-roll/camera-roll": "^7.8.3",
