### ISSUE TITLE
Can't create Album on Android 10 Devices

### ISSUE THREAD

**Issue by rishabh876** [react-native-cameraroll/react-native-cameraroll#115]
# Bug
`CameraRoll.save(uri, {type: "photo", album: config.appName});`
Album creation fail in CameraRollModule.java - 141
Error: "Album Directory not created. Did you request WRITE_EXTERNAL_STORAGE?"
In Logcat I get
`Got a deoptimization request on un-deoptimizable method boolean`

I do have storage permission. Only happens on few devices

## Environment info

```
System:
    OS: macOS 10.15.2
    CPU: (8) x64 Intel(R) Core(TM) i5-8257U CPU @ 1.40GHz
    Memory: 58.14 MB / 8.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 13.0.1 - /usr/local/bin/node
    Yarn: 1.19.1 - /usr/local/bin/yarn
    npm: 6.13.1 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 13.2, DriverKit 19.0, macOS 10.15, tvOS 13.2, watchOS 6.1
    Android SDK:
      API Levels: 16, 19, 23, 26, 28, 29
      Build Tools: 23.0.1, 28.0.3, 29.0.2
      System Images: android-23 | Google APIs Intel x86 Atom, android-25 | Android TV Intel x86 Atom, android-25 | Google APIs Intel x86 Atom, android-25 | Google APIs Intel x86 Atom_64, android-25 | Google Play Intel x86 Atom, android-28 | Intel x86 Atom_64, android-28 | Google Play Intel x86 Atom, android-29 | Intel x86 Atom_64
  IDEs:
    Xcode: 11.2.1/11B500 - /usr/bin/xcodebuild
  npmPackages:
    react: 16.9.0 => 16.9.0 
    react-native: 0.61.5 => 0.61.5
```

Library version:  "@react-native-community/cameraroll": "^1.3.0"

Device Name: Pixel 2 (Android 10)

## Steps To Reproduce

1. Call`CameraRoll.save(uri, {type: "photo", album: config.appName});`

# Update
Definitely an Android 10 issue.

**Comment by rishabh876** [comment]
Refer : https://commonsware.com/blog/2019/06/07/death-external-storage-end-saga.html
Workaround: 
> For Android Q, you can add `android:requestLegacyExternalStorage="true"` to your <application> element in the manifest. This opts you into the legacy storage model, and your existing external storage code will work.

**Comment by PritishSawant** [comment]
Even i am facing this issue. I added  android:requestLegacyExternalStorage="true" to Android Manifest but the issue persists on the emulator. I dont have  a real device to test on

**Comment by bartolkaruza** [comment]
We've updated the docs related to Android permissions from Android 29. There is an example of how you can/should request permission explicitly. Can you check that this issue is still there after you have requested the permission in the way described in the latest docs?

**Comment by BuddhaNag12** [comment]
I'm facing the same issue on android 10 devices 
[Error: Album Directory not created. Did you request WRITE_EXTERNAL_STORAGE?

is there any solution...?

**Comment by codepenguinx0** [comment]
Tried adding android:requestLegacyExternalStorage="true" to Android Manifest but it didn't fix the issue on both emulator and real device. Does Anyone have an update for this issue?

**Comment by codepenguinx0** [comment]
> Tried adding android:requestLegacyExternalStorage="true" to Android Manifest but it didn't fix the issue on both emulator and real device. Does Anyone have an update for this issue?

I fixed this by NOT adding type:"photo"

**Comment by lucipacurar** [comment]
I'm having the same problem, and the workaround works just fine. The issues happens only on Android 10, 9 and 11 are working ok without the workaround.

**Comment by philoskim** [comment]
This problem is caused by the permission policy change in Android 10.

So I solved this problem as follows.

Add the following to `android/app/src/main/AndroidManifest.sml`

```
   <application ......
                android:requestLegacyExternalStorage="true">

```

Add the following to `android/app/src/debug/AndroidManifest.sml`

```
   <application ......
                android:requestLegacyExternalStorage="true">

```

Execute the following commaands in your project root directory.

```
# clear cache
$ watchman watch-del-all
$ rm -rf $TMPDIR/react-native-packager-cache-*
$ rm -rf $TMPDIR/metro-bundler-cache-*
$ rm -rf node_modules/
$ android/gradlew clean
$ yarn cache clean
$ yarn install
$  react-native start --reset-cache
```

Recompile your code and run it!

**Comment by KuiGoan** [comment]
This is my code. It's working on Android 10 and 11. Or you can read more in [my fork](https://github.com/KuiGoan/react-native-cameraroll/blob/master/android/src/main/java/com/reactnativecommunity/cameraroll/CameraRollModule.java)

>           String mimeType = getMimetypeOrigin(mUri.getPath(), true);
>           if (isAlbumPresent) {
>             // Notes: I got this error when using Environment.DIRECTORY_MOVIES
>             // Primary directory Movies not allowed for content://media/external_primary/file; allowed directories are [Download, Documents]
>             if (isVideo) {
>               mediaCollection = MediaStore.Video.Media.getContentUri(MediaStore.VOLUME_EXTERNAL_PRIMARY);
>               File dirDest = new File(Environment.DIRECTORY_MOVIES, album);
>               mediaDetails.put(MediaStore.MediaColumns.RELATIVE_PATH, dirDest.toString() + File.separator);
>               mediaDetails.put(Video.Media.DISPLAY_NAME, source.getName());
>               mediaDetails.put(Video.Media.IS_PENDING, 1);
>             } else {
>               mediaCollection = MediaStore.Images.Media.getContentUri(MediaStore.VOLUME_EXTERNAL_PRIMARY);
>               File dirDest = new File(Environment.DIRECTORY_PICTURES, album);
>               mediaDetails.put(Images.Media.MIME_TYPE, mimeType);
>               mediaDetails.put(MediaStore.MediaColumns.RELATIVE_PATH, dirDest.toString() + File.separator);
>               mediaDetails.put(Images.Media.DISPLAY_NAME, source.getName());
>               mediaDetails.put(Images.Media.IS_PENDING, 1);
>             }
>           } else {
>             mediaCollection = MediaStore.Files.getContentUri(MediaStore.VOLUME_EXTERNAL_PRIMARY);
>           }
>           mediaDetails.put(MediaStore.MediaColumns.MIME_TYPE, mimeType);

**Comment by sunny635533** [comment]
I also have this problem.I already add "android:requestLegacyExternalStorage="true"，but nothing help. So try add these code in here, everything is OK.
 `
if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.Q) {
          ContentValues mediaDetails = new ContentValues();
          //修复Android10下载图片的bug (Build.VERSION.SDK_INT == Build.VERSION_CODES.Q)
          if (isAlbumPresent || (Build.VERSION.SDK_INT == Build.VERSION_CODES.Q)) {
            String relativePath = Environment.DIRECTORY_DCIM + File.separator + album;
            mediaDetails.put(MediaStore.MediaColumns.RELATIVE_PATH, relativePath);
          }
......
`
