### ISSUE TITLE
Warnings to devs: Don't uniq or do any manipulation by fileName -- iOS 13 makes this impossible

### ISSUE THREAD

**Issue by bobber205** [react-native-cameraroll/react-native-cameraroll#123]
# Bug

With a recent update to iOS 13 the filenames returned by this library for all recently taken photos is "Adjustments.plist". If were uniquing by filename to ensure no dup'd photos were presented this will cause issues (obviously). I am uniquing by uri instead.

## Environment info

React native info output:

```bash
System:
    OS: macOS 10.15.1
    CPU: (4) x64 Intel(R) Core(TM) i5-5287U CPU @ 2.90GHz
    Memory: 33.63 MB / 8.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 10.16.0 - /var/folders/11/4dsnq9p12xx9s0lt7l20fbfh0000gq/T/yarn--1578347654312-0.11839324853053057/node
    Yarn: 1.21.1 - /var/folders/11/4dsnq9p12xx9s0lt7l20fbfh0000gq/T/yarn--1578347654312-0.11839324853053057/yarn
    npm: 6.9.0 - ~/.nvm/versions/node/v10.16.0/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 13.2, DriverKit 19.0, macOS 10.15, tvOS 13.2, watchOS 6.1
    Android SDK:
      API Levels: 23, 26, 27, 28
      Build Tools: 26.0.2, 27.0.3, 28.0.3
      System Images: android-27 | Google APIs Intel x86 Atom, android-27 | Google Play Intel x86 Atom, android-28 | Google APIs Intel x86 Atom
  IDEs:
    Android Studio: 3.5 AI-191.8026.42.35.5900203
    Xcode: 11.2.1/11B500 - /usr/bin/xcodebuild
  npmPackages:
    @react-native-community/cli: ^2.7.0 => 2.10.0
    react: 16.9.0 => 16.9.0
    react-native: 0.61.4 => 0.61.4
```

Library version: Latest

No code is needed to reproduce but it does require a real up to date iOS installed device.

```js
{
    "group_name": "All Photos",
    "image": {
        "filename": "Adjustments.plist",
        "height": 4032,
        "isStored": true,
        "playableDuration": 0,
        "uri": "ph://811989D1-A7D6-4D26-9DA4-84D4195E5879/L0/001",
        "width": 2268
    },
    "location": {
        "altitude": 58,
        "heading": 89.53881070999999,
        "latitude": 45.55387167000001,
        "longitude": -122.66710500000002,
        "speed": 0
    },
    "timestamp": 1578340655.2784872,
    "type": "image"
}```

is an example of what is returned in `.edges`

**Comment by stardevrk** [comment]
Hi @bobber205. Did you resolve this issue?

**Comment by bobber205** [comment]
How would I have resolved it? This is a bug either with the library or with iOS 13.

**Comment by stardevrk** [comment]
Then did you remove this library from your project? What is the alternative solution?

**Comment by bobber205** [comment]
I am simply uniquing by uri instead of filename. (I said that in the OP)

**Comment by stardevrk** [comment]
I need to read file by uri and upload that file to the firebase. But all functions can not handle such uri.
Do you have any solution?

**Comment by bartolkaruza** [comment]
For reference:
https://forums.developer.apple.com/thread/123471

There is a lot of issues raised by iOS users for similar issue in the Skype app, Google Drive app etc.. There appears to be a suggested reinstall that fixed it for some users. Perhaps it requires a recompile of your app with a newer version of Xcode. Can someone try these two options on their app to see if either works?

**Comment by bartolkaruza** [comment]
> I have been having this same issue since the update. I thought it was a problem with the Live Photo’s so I disabled the live aspect of the photo in the Photos app. Now they just upload as Adjustments.plist. When I take photos with live completely disabled, they upload as jpg like normal.

https://community.box.com/t5/Desktop-and-Mobile-Forum/Uploading-image-with-mobile-app-Default-file-extension-is-MOV/td-p/77250

**Comment by rumata2** [comment]
I confirm that recompiling with newer version of XCode does not resolve the issue - the file names still get returned as Adjustments.plist BUT only for files edited in Photos app: for example if I take a screenshot, crop it and then save it to Photos, this is what camera roll would return as file name.

**Comment by bartolkaruza** [comment]
At the native level there could be some solutions in this: https://stackoverflow.com/questions/32687403/phasset-get-original-file-name
