### ISSUE TITLE
Is it possible to have two timestamps -- one from the image meta data and one for the file meta data?

### ISSUE THREAD

**Issue by bobber205** [react-native-cameraroll/react-native-cameraroll#124]
Let's say you have a photo from a few months ago you've edited with a photo editing tool and saved locally to your device.

With how getPhotos() currently works it only returns the timestamp contained in the image meta data -- so if your app doesn't modify that it's as if you took the altered photos months ago requiring a user to scroll and scroll to find it.

Instagram and other apps seem to be taking both into account. I logged the full object of the edited photo and it had the same timestamp as the edited photo. Can the file timestamp be returned as well?<3

**Comment by bartolkaruza** [comment]
Happy to receive a PR for this :)
