### ISSUE TITLE
Unable to access CameraRoll.saveToCameraRoll

### ISSUE THREAD

**Issue by chaitanyaevoke** [react-native-cameraroll/react-native-cameraroll#136]
I am trying to save an image to camera roll in iOS.
Library : @react-native-community/cameraroll - 1.3.1

**Steps followed for installation :**

npm install @react-native-community/cameraroll 
react-native link @react-native-community/cameraroll 
cd ios 
pod install

**Added following in info.plist**

NSPhotoLibraryUsageDescription
NSPhotoLibraryAddUsageDescription

Below is the error while I am trying to do CameraRoll.saveCameraToRoll("https://.....jpg", 'photo');

Please help on the issue...

**Comment by chaitanyaevoke** [comment]
Sorry, I forgot to add the error

**TypeError: null is not an object (evaluating '_nativeInterface.default.saveToCameraRoll')**

**Comment by natanaeladit** [comment]
I am having the same error. any solution?

**Comment by bartolkaruza** [comment]
RN version? This issue is caused by something going wrong in linking the library. The native code is not available in your app.

**Comment by enisinanaj** [comment]
How is your react-native core being linked to the app?
Are you using Pods or manual linking?

I'm sure there must be something wrong with the Header Search Path

**Comment by windzzf** [comment]
I also encountered the same problem, how did you solve it

**Comment by praba1989** [comment]
@chaitanyaevoke 
try with this
CameraRoll.save(path)

**Comment by Ayzekberk** [comment]
CameraRoll.save(path) is working but i do not understand the other parameters usage.
when i use CameraRoll.save() function by below, there are no saving photo in my library

`CameraRoll.save('dh_photo', { type: 'photo', album: 'some_album_name' })`

can anyone tell how is the correct usage
