### ISSUE TITLE
Can CameraRoll.deletePhotos delete video? 

### ISSUE THREAD

**Issue by vmenekos** [react-native-cameraroll/react-native-cameraroll#152]
Is it possible to delete a video from camera roll?
If not it would be a feature that should be added.

**Comment by MrAlekhin** [comment]
please add this one 🙏

**Comment by victork9** [comment]
yes, it is possible to get photos or videos with

CameraRoll.getPhotos({
            first: 20,
            assetType: 'Photos' || 'Video',
        }).then(r => {
           console.log("return of promisse" + JSON.stringnify(r))
          })

after return get the uri of your photo and pass with param of function 

CameraRoll.deletePhotos(["file:///storage/emulated/0/Pictures/your_album/182ccd7b-c705-429b-896b-496ad20211dd.jpg"])

**Comment by victork9** [comment]
worked for me, deleting all photos of a album

CameraRoll.getPhotos({
                first: 200,
                assetType: 'Photos',
            })
                .then(r => {
                    const filter = r.edges.filter(d => d.node.group_name.includes("YOURALBUM"))
                    filter.map((item) => {
                        CameraRoll.deletePhotos([item.node.image.uri])

                    })

                })

**Comment by MrAlekhin** [comment]
Have you tried the video URL?

**Comment by victork9** [comment]
this library only deletes photos

the coment of archive typescript

Delete a photo from the camera roll or media library. photoUris is an array of photo uri's.

**Comment by victork9** [comment]
this library only deletes photos

the coment of archive typescript

Delete a photo from the camera roll or media library. photoUris is an array of photo uri's.

**Comment by victork9** [comment]
see the library https://github.com/itinance/react-native-fs maybe work

**Comment by MrAlekhin** [comment]
> yes, it is possible to get photos or videos with
> 
> 
> 
> CameraRoll.getPhotos({
> 
>             first: 20,
> 
>             assetType: 'Photos',
> 
>         }).then(r => {
> 
>            console.log("return of promisse" + JSON.stringnify(r))
> 
>           })
> 
> 
> 
> after return get the uri of your photo and pass with param of function 
> 
> 
> 
> CameraRoll.deletePhotos(["file:///storage/emulated/0/Pictures/your_album/182ccd7b-c705-429b-896b-496ad20211dd.jpg"])
> 
> 

In that case the answer is no, right? Videos cannot be removed. Is it possible to add the feature to backlog `CameraRoll.deleteVideos`?

**Comment by victork9** [comment]
I don't understand @MrAlekhin, the library itself says it is possible to delete a video I just saw, but when we use the method it doesn't work

**Comment by jairrc** [comment]
> yes, it is possible to get photos or videos with
> CameraRoll.getPhotos({
> first: 20,
> assetType: 'Photos',
> }).then(r => {
> console.log("return of promisse" + JSON.stringnify(r))
> })
> after return get the uri of your photo and pass with param of function
> CameraRoll.deletePhotos(["file:///storage/emulated/0/Pictures/your_album/182ccd7b-c705-429b-896b-496ad20211dd.jpg"])

I am trying to delete photos from my device. I created the routine that lists the photos, but when I try to delete, passing the URI, nothing is deleted. The URI is in this format: "content: // media / external / images / media / 36257"

How I should to proceed, so that it stays in this format?
"file: ///storage/emulated/0/Pictures/your_album/182ccd7b-c705-429b-896b-496ad20211dd.jpg"

**Comment by victork9** [comment]
@jairrc  
usually this type("file: ///storage/emulated/0/Pictures/your_album/182ccd7b-c705-429b-896b-496ad20211dd.jpg") is in the cache and not in the photo library, you will only be able to delete files that are saved in the library

**Comment by jairrc** [comment]
> @jairrc
> usually this type("file: ///storage/emulated/0/Pictures/your_album/182ccd7b-c705-429b-896b-496ad20211dd.jpg") is in the cache and not in the photo library, you will only be able to delete files that are saved in the library

Got it. But doing as shown in the documentation is not deleting the images. Looking at the example you mentioned on 5/25, I thought it had to be passed in that format. I don't know what to do to make it really work. Documentation always has poor examples that don't work. :(

![image](https://user-images.githubusercontent.com/1241980/87063129-528e8e80-c1e4-11ea-8d03-5a10857535fe.png)

**Comment by acponciano** [comment]
In https://github.com/react-native-cameraroll/react-native-cameraroll/blob/master/android/src/main/java/com/reactnativecommunity/cameraroll/CameraRollModule.java: 

`@Override
    protected void doInBackgroundGuarded(Void... params) {
      ContentResolver resolver = mContext.getContentResolver();

      // Set up the projection (we only need the ID)
      String[] projection = { MediaStore.Images.Media._ID };

      // Match on the file path
      String innerWhere = "?";
      for (int i = 1; i < mUris.size(); i++) {
        innerWhere += ", ?";
      }

      String selection = MediaStore.Images.Media.DATA + " IN (" + innerWhere + ")";
      // Query for the ID of the media matching the file path
      Uri queryUri = MediaStore.Images.Media.EXTERNAL_CONTENT_URI;

      String[] selectionArgs = new String[mUris.size()];
      for (int i = 0; i < mUris.size(); i++) {
        Uri uri = Uri.parse(mUris.getString(i));
        selectionArgs[i] = uri.getPath();
      }

      Cursor cursor = resolver.query(queryUri, projection, selection, selectionArgs, null);
      int deletedCount = 0;

      while (cursor.moveToNext()) {
        long id = cursor.getLong(cursor.getColumnIndexOrThrow(MediaStore.Images.Media._ID));
        Uri deleteUri = ContentUris.withAppendedId(MediaStore.Images.Media.EXTERNAL_CONTENT_URI, id);

        if (resolver.delete(deleteUri, null, null) == 1) {
          deletedCount++;
        }
      }

      cursor.close();

      if (deletedCount == mUris.size()) {
        mPromise.resolve(true);
      } else {
        mPromise.reject(ERROR_UNABLE_TO_DELETE,
            "Could not delete all media, only deleted " + deletedCount + " photos.");
      }
    }`

I got this last promise rejection ("Could not delete all media')  whenever there are videos on the deletion list in android react native app using CameraRoll.deletePhotos @react-native-community/cameraroll.

Would it be an issue?

**Comment by yahacom** [comment]
For me it also not delete video on Android 13. I got this error
`{"nativeStackAndroid":[],"userInfo":null,"message":"Could not delete all media, only deleted 0 photos.","code":"E_UNABLE_TO_DELETE"}`

I use camera-roll v5.8.0
react-native 0.71.7

on iOS it works well.
