### ISSUE TITLE
Unable to get Location object from CameraRoll.getPhotos edges

### ISSUE THREAD

**Issue by imranmirza-nxb** [react-native-cameraroll/react-native-cameraroll#154]
After capture and saving photo to camera role I need to get location(Longitude/Latitude) from where photo was captured. Is this possible as in the documentation we can get Location object inside edges array but for my case there is no object for Location?

**Comment by dkocich** [comment]
same here with cameraroll: v1.5.2, latest stable RN and Android 10 (Pixel emulator). When I checked with https://play.google.com/store/apps/details?id=net.xnano.android.photoexifeditor or using Google photos gallery I can see that coordinates are saved correctly but nothing appears in Cameraroll edges...

![image](https://user-images.githubusercontent.com/6165660/79829247-d170e980-83a2-11ea-9792-56dda5762c88.png)

**Comment by Gordeev1** [comment]
Please make just you added [ACCESS_MEDIA_LOCATION](https://developer.android.com/reference/android/Manifest.permission#ACCESS_MEDIA_LOCATION) permission to manifest file.
Otherwise, it would not give you photo location info.
