### ISSUE TITLE
Thumbnail images

### ISSUE THREAD

**Issue by noobvim** [react-native-cameraroll/react-native-cameraroll#168]
Hi, this package is unusable if someone wants to implement their own camera roll because the image sizes returned are huge, causing a very noticeable sluggish performance degradation when loading lots of images into FlatList. It would be great to have smaller thumbnail image sizes returned in addition to the regular full size images. Thanks!

react-native-image-resizer is not a valid workaround since it takes a long time to process images.

Similar to [https://github.com/react-native-community/react-native-cameraroll/issues/110](https://github.com/react-native-community/react-native-cameraroll/issues/110)

**Comment by bartolkaruza** [comment]
Hey there, this is a useful addition to the library and I would be happy to take PR's solving the problem of resizing the images (or retrieving at a smaller size).

**Comment by guy-shahine** [comment]
I created a PR from a solution that Jared Sumner provided but didn't have time to create a PR.  I looked in the repo for manual testing guidance but couldn't find any. Any pointers or someone jumping in to help testing this solution is appreciated.

**Comment by dokkis** [comment]
I agree this is a must to have for such library and solution based on generating the thumbnail are not good for performance. I looked into it a little bit, for Android we could use:

https://developer.android.com/reference/android/provider/MediaStore.Images.Thumbnails.html 

It's deprecated starting from API Level 29 but it's available from API Level 1.
`Return thumbnail representing a specific image item. If a thumbnail doesn't exist, this method will block until it's generated. Callers are responsible for their own in-memory caching of returned values.`. Interesting thread on stackoverflow here: https://stackoverflow.com/questions/32782085/querying-the-mediastore-joining-thumbnails-and-images-on-id

For iOS I didn't investigate yet.

**Comment by dokkis** [comment]
@bartolkaruza @noobvim I am trying to look into this improvement, I tried several method to generate or get existing thumbnail (only in Android for now):

Performance are observed on Xiaomi Mi A1.
1. ThumbnailUtils.extractThumbnail (around 70ms, this generated the thumbnail), could `always` return a base64 thumbnail
2. Images.Thumbnails.getThumbnail (around 10/20ms, should fetch an existing thumbnail), could return a base64 thumbnail (or null if is not yet generated)
3. MediaStore.Images.Thumbnails.queryMiniThumbnail (around 5/10ms, it fetches an existing thumbnail), could return the URI of an existing thumbnail (or null if is not yet generated)

Given that I don't think is really possible drop this further down, I am wondering if makes more sense having a separate API for fetching the thumbnail, e.g. `getPhotoThumbnail`.
I don't know how react-native parallelise components, but for example if you try to load 100 components that has an Image that tries to call `getPhotoThumbnail(mediaId/mediaUri)` is it then better than having all embedded into a much slower `getPhoto` API?

**Comment by bartolkaruza** [comment]
I really like the `getPhotoThumbnails` direction. Considering the UI pattern for thumbnails, most likely apps will retrieve many more thumbnails than actual photos, making the retrieving of photos an unnecessary load in those scenario's. Apps can then retrieve individual photos (potentially with slow metadata) through the already optimised `getPhotos` for the scenario's where they need those.

I suppose it will be a much simpler implementation for the actual retrieval of the thumbnails, at the cost of potentially duplicating some of the logic  between `getPhotos` and `getPhotoThumbnails`. How does that sound?

**Comment by gran33** [comment]
I think that `getPhotoThumbnails` isn't a good API.  
Return the thumbnail `uri` for any use-case of `getPhotos`.
 The user will decide whether to use the thumbnail or the original photo. 
In this way, the user doesn't need to re-ask the photos again.

**Comment by bartolkaruza** [comment]
> I think that getPhotoThumbnails isn't a good API.
Return the thumbnail uri for any use-case of getPhotos.
The user will decide whether to use the thumbnail or the original photo.
In this way, the user doesn't need to re-ask the photos again.

I agree that the API would be nicer from a theoretical point of view, but the performance hit is just too big for this trade off. The thumbnail needs to be generated, which consumes resources unnecessarily.

**Comment by dokkis** [comment]
@gran33 I agree having in getPhotos would be better but performance-wise is not a good idea.

@bartolkaruza I might coming back to this. A `getPhotoThumbnails` might be trickier to implement when something fails for some reason, what do you return and how to handle partial failures? To keep it simple for now, we can improve it later or add another API later, I am thinking a simple `getPhotoThumbnail` API that looks like following:

```
export type PhotoThumbnailOptions = {
   allowNetworkAccess: boolean, // iOS only
   targetWidth: number,
   targetHeight: number,
   quality: number,
 };
 
 export type PhotoThumbnail = {
   thumbnailBase64: string,
 };

function getPhotoThumbnail(uri: string, options: PhotoThumbnailOptions): Promise<PhotoThumbnail>;
```

allowNetworkAccess might be useful in iOS as the API that we can use has this flag, and you might want to deny to go to cloud to generate the image. targetWidth and targetHeight because on iOS or in general the API might not return exact size but something closer to what you request. Quality is jpeg quality to eventually compress if you want a lighter `thumbnailBase64`.

What do you think?

**Comment by tvpranav** [comment]
@dokkis Any updates on thumbnail part ?

**Comment by sgtpsibin** [comment]
any updates on this feature?, i think this will be great feature for render camera roll photo in a grid (very popular case).

**Comment by PierreCapo** [comment]
Awesome, thanks for your fast response 👍

**Comment by HERYORDEJY-DEV** [comment]
@PierreCapo Thumbnail for videos too would be appreciated

**Comment by HERYORDEJY-DEV** [comment]
@Arjan-Zuidema I am unable to get Video from the device, only Photos. Even if I set `assetType` to 'All', only Photos are retrieved. I really need help on this, been on it for almost a week, for a task I should have completed in 3 hours.

**Comment by jp-23** [comment]
I created a PR ([536](https://github.com/react-native-cameraroll/react-native-cameraroll/pull/536)) to add a `getPhotoThumbnail` method - for iOS only right now.

 @bartolkaruza want to take a look?

**Comment by Arjan-Zuidema** [comment]
Hi @jp-23 

I will take a look at the end of the week. Sorry, really busy now :)
