### ISSUE TITLE
 After adding exif loading, the loading time of photos increased 10 times

### ISSUE THREAD

**Issue by jash90** [react-native-cameraroll/react-native-cameraroll#175]
After adding this change https://github.com/react-native-community/react-native-cameraroll/commit/ade785e29d24228d3148a6f5581db7a885d029cc photo loading have been increased 10 times.
This feature should be optional.

Please undo the change or add the option to disable it.

**Comment by bartolkaruza** [comment]
If you see the discussion in #178 I think the option to disable individual fields will solve this and other performance related issues.

**Comment by ehsan6sha** [comment]
this is resolved?
