### ISSUE TITLE
iOS - Large Files/Video - Can't save (to camera roll). [PHPhotosErrorDomain error -1]

### ISSUE THREAD

**Issue by scgough** [react-native-cameraroll/react-native-cameraroll#186]
# Bug report
iOS - Photo's successfully save to camera roll but videos (or large files maybe?) do not. 

_I'll give as much detail as I can at the moment_

## Summary
I call `path = await CameraRoll.save(path);` where `path` is a local path to a downloaded mp4 file. 
The JS hands over to the Objective C side. 

The code successfully reaches here with a populated `placeholder` object: 
https://github.com/react-native-community/react-native-cameraroll/blob/master/ios/RNCCameraRollManager.m#L145

The code then continues but when `completionHandler` is called, success is `NO` 
https://github.com/react-native-community/react-native-cameraroll/blob/master/ios/RNCCameraRollManager.m#L152

The error returned is: 
`[Error: The operation couldn’t be completed. (PHPhotosErrorDomain error -1.)]`

update: This seems to be a file size or maybe image dimension issue. Some videos work but others fail.

Fail: 20MB, 2160 × 4096 (portrait) 
Success: 18MB 4096 × 2160 (landscape) 

## Environment info

RN 0.62.2
React: 16.11.0
Library version: 1.7.1

1. Download a large file size MP4 from remote URL to local (using `RNFetchBlob`)
2. Take local path for downloaded file and call:
 `const camerarollpath = await CameraRoll.save(localpath);`
3. See error as per description above.

Describe what you expected to happen:

1. Video is saved to camera roll and `camerarollpath` is set

**Comment by dokkis** [comment]
@scgough I am curious if await CameraRoll.save(localpath, { type: "video" }); make any difference. Can you please try it? Based on the type, looking at the code, two different methods are called.

**Comment by scgough** [comment]
@dokkis I'll give that a try although stepping through the code it does look like it's following the video route already :/

**Comment by scgough** [comment]
@dokkis to confirm it is calling the `creationRequestForAssetFromVideoAtFileURL` method (I tried to explicitly pass the `type` option). 

As weird as it sounds I'm wondering if the fact this video is a portrait with dimensions 2160 × 4096 that the issue is occurring? Perhaps an iOS issue handling the file?
A landscape video of the same dimensions works without issue.

**Comment by dokkis** [comment]
@scgough I see that in the JS package there is some autodetection based on the tag passed: https://github.com/react-native-community/react-native-cameraroll/blob/master/js/CameraRoll.js#L167 so probably that's why go into the video path.

**Comment by dokkis** [comment]
> @dokkis to confirm it is calling the `creationRequestForAssetFromVideoAtFileURL` method (I tried to explicitly pass the `type` option).
> 
> As weird as it sounds I'm wondering if the fact this video is a portrait with dimensions 2160 × 4096 that the issue is occurring? Perhaps an iOS issue handling the file?
> A landscape video of the same dimensions works without issue.

is it a video that you recorder with the device or some video that you imported from somewhere else? Looking at the issue seems the latter. Still out of curiosity, have you replicated the same behaviour with a big video recorded from the device it self? Wondering if it's a size issue or some weird thing around the file downloaded remotely. Have you tried with different format? e.g. .mov, .mp4?

**Comment by scgough** [comment]
@dokkis thanks. I’ll have a look at your suggested urls. If adding “.mov” to the path works I’ll be astounded and shaking my fist in Apples general direction.  

It is a private video from Vimeo. The image dimensions seem to be ringing alarm bells for me. I don’t know why but this is a 20MB MP4 video, 4K but portrait. A landscape video similar in every way (encoding included) apart from the orientation works. 

Truly baffling at the moment. I’ll report back if I find out anything else.

**Comment by dokkis** [comment]
@scgough more than renaming would be interesting to check similar file, e.g. big 4k portrait in .mov format if they have same issues (I don't think renaming should make any difference honestly, I am more curious about format/codec mp4 vs mov). Since the native format that iOS shoot is .mov, wondering if it's an issues specifically with some .mp4 format more than a file size issue. Also 20MB is not big for a video.

**Comment by kouariga** [comment]
I experienced a similar issue.

- iOS 13.5.1, iPadOS 13.5.1
- RN 0.62.2
- RN CameraRoll: 1.7.2

I tried to save a video that I recorded using react-native-camera (format: mov, quality: 1080p, codec: JPEG) in the camera roll. It succeeded on iPhone but failed on iPad giving the error `[Error: The operation couldn’t be completed. (PHPhotosErrorDomain error -1.)]`. Seeing @dokkis 's comment, I tried changing the codec from JPEG to H264, and it made it both on iPhone and iPad.

I have no idea why, but just for your information.

**Comment by khattab93** [comment]
Did any one solve this silly error

**Comment by scgough** [comment]
I’ve not got any further I’m afraid although I think @dokkis is on the right track with the encoding of the video file.

**Comment by tedi** [comment]
This is definitely happening when trying to save with file extensions other that .mov. I just updated all my outputs to use .mov.

**Comment by senolatac** [comment]
I solved it like:
First of all, download it via RNFS then move it to CameraRoll

  ```
import RNFS from 'react-native-fs';
...
downloadVideo = () => {
    RNFS.downloadFile({
      fromUrl: mediUrl,
      toFile: `${RNFS.DocumentDirectoryPath}/react-native.mov`,
    }).promise.then((r) => {
      CameraRoll.saveToCameraRoll(
        `${RNFS.DocumentDirectoryPath}/react-native.mov`,
        'video',
      )
        .then((videoUri) => {
              ...videoUri on CameraRoll
        })
        .catch((e) => console.log(e));
    });
  };
```

**Comment by scgough** [comment]
Just coming back to this again 😄 

I'm pretty sure on iOS Camera Roll/Photos app can't handle 4K (or above?) videos so what I've done is pass my file to `react-native-share` 'saveToFiles` which triggers the iOS file manager app where the user can select to save the file.

**Comment by arelstone** [comment]
I am facing this issue aswell. Our users is not able to export their videos recorded in 4K. Is there any updated on this? I've trawled the Apple developer documentation and cannot seem to find anything regarding this restriction. Is this restriction only 4K videos no matter the size of the file or does the file size matter aswell?

@scgough I've had a look at the [`react-native-share`-docs](https://react-native-share.github.io/react-native-share/docs/install) and cannot seem to find the `saveToFiles`-method. Will it be possible for you to provide an example of how you're doing this

**Comment by scgough** [comment]
@arelstone It's actually `react-native-share` and you can use this method with the `saveToFiles` flag set to true on iOS https://react-native-share.github.io/react-native-share/docs/share-open
