### ISSUE TITLE
MediaStore.MediaColumns.DATA is deprecated 

### ISSUE THREAD

**Issue by paulmasters** [react-native-cameraroll/react-native-cameraroll#188]
# Question

MediaStore.MediaColumns.DATA   is deprecated but it is currently required to get file URIs for photos in external storage. Is there a plan for how to fix this?

Deprecation notice:
https://developer.android.com/reference/android/provider/MediaStore.MediaColumns#DATA

Usage:
https://github.com/react-native-community/react-native-cameraroll/blob/b777e2bc57c263524d4fbe9dd83b81b5078b3420/android/src/main/java/com/reactnativecommunity/cameraroll/CameraRollModule.java#L83  
https://github.com/react-native-community/react-native-cameraroll/blob/b777e2bc57c263524d4fbe9dd83b81b5078b3420/android/src/main/java/com/reactnativecommunity/cameraroll/CameraRollModule.java#L521

It looks like this will break getPhotos for Android SDK > 29

Probably the preferred way to access photos is via a content URI like below but these are not currently supported by the react-native Image component

**File URI**  -  current uri gives access denied error 
`
    Uri photoUri = Uri.parse("file://" + media.getString(dataIndex));
`

 **Content URI** - possible solution but uri cannot be displayed in react-native Image
`
    long id = media.getLong(idIndex);
    Uri photoUri = ContentUris.withAppendedId(MediaStore.Images.Media.EXTERNAL_CONTENT_URI, id);
`

**Comment by bartolkaruza** [comment]
@dokkis this looks similar to #174 to me. Any ideas about how we could handle this case?

**Comment by paulmasters** [comment]
I would propose to use content URIs. It's really a bug in the RN / Fresco code that these are not displayed. 
ie as mentioned above
long id = media.getLong(idIndex); Uri photoUri = ContentUris.withAppendedId(MediaStore.Images.Media.EXTERNAL_CONTENT_URI, id);
I can put a PR together if you like?

**Comment by bartolkaruza** [comment]
@paulmasters that sounds good to me! We have to wait for the change from Fresco through to React Native to land before we can merge and release it here though.

**Comment by jamolkhon** [comment]
It seems `MediaStore.MediaColumns.DATA` has been undeprecated in API 32.
