### ISSUE TITLE
Error: Permission denied  at Object.promiseMethodWrapper [as saveToCameraRoll] (But Permission for 'write external storage' is granted)

### ISSUE THREAD

**Issue by herysihn918** [react-native-cameraroll/react-native-cameraroll#192]
I have the issue.
I am using react-native-view-shot and @react-native-community/cameraroll to capture the screenshot and save it on the external storage.
But I always get the permission denied error in Android. I have tried all the method above, but the same.
I have checked the permission status with PermissionAndroid and it said 'granted'.
But I can't save the screenshot with the error: 'Permission denied'. Which permissions are more needed?
Please help me.
Android version is 29.

Error: Permission denied
    at Object.promiseMethodWrapper [as saveToCameraRoll] (...\node_modules\react-native\Libraries\BatchedBridge\NativeModules.js:103)

**Comment by bartolkaruza** [comment]
Hi, there are workaround for this issue in #19 . You need to request permissions in the app, as well as declare them in Android 29.

We have an open issue to document this:
https://github.com/react-native-community/react-native-cameraroll/issues/194

Closing as duplicate of #19

**Comment by mars-lan** [comment]
@bartolkaruza please reopen this issue as it's a real issue due to the introduction of [Scoped storage](https://developer.android.com/training/data-storage#scoped-storage) in Android 10 (API 29). 

@herysihn918 one workaround meanwhile is by setting `android:requestLegacyExternalStorage` to `true` in your AndroidManifest.xml as described in https://developer.android.com/training/data-storage/use-cases#opt-out-scoped-storage

**Comment by bartolkaruza** [comment]
@mars-lan I'm going to need more details about what cases causes this issue for you. Is this happening on specific devices? Others have successfully been able to save photos on Android 29 by explicitly requesting the permissions. Can you provide me with a minimal reproduction?

**Comment by bartolkaruza** [comment]
Linking in this other issue, that could be related: https://github.com/react-native-community/react-native-cameraroll/issues/164

**Comment by mars-lan** [comment]
@bartolkaruza This is readily reproducible on all Android 10 devices if you set `targetSdkVersion` to `29` as mentioned here:  https://developer.android.com/training/data-storage/use-cases#opt-out-scoped-storage. Another workaround is to set `targetSdkVErsion` to `28` or lower.

**Comment by bartolkaruza** [comment]
Thank you @mars-lan , I fully get the problem now. The proper fix for this is not immediately obvious to me yet, let me give this some thought.

**Comment by bartolkaruza** [comment]
@herysihn918 can you share why you closed this issue? I don't think we've resolved this yet from the library side. I'm going to re-open it so we don't lose track of it.

**Comment by sidhanshumonga** [comment]
@bartolkaruza Any update on this? I have been struggling with this issue for a while.

**Comment by aprilmintacpineda** [comment]
Still having this error on a newly created app.

**Comment by BuddhaNag12** [comment]
I'm facing the same problem as i tried to asked permission manually but seems it takes permission but couldn't able to write to external storage

**Comment by code8decode** [comment]
https://github.com/react-native-community/react-native-cameraroll/issues/219#issuecomment-671411010

**Comment by mars-lan** [comment]
See my comment above for workaround: https://github.com/react-native-community/react-native-cameraroll/issues/192#issuecomment-648866758

**Comment by dnsgusttavo** [comment]
I was having the same problem with android 10 and API level 29. Adding android: requestLegacyExternalStorage = "true" on my AndroidManifest.xml solves my problem.

**Comment by kr4ckhe4d** [comment]
> I was having the same problem with android 10 and API level 29. Adding android: requestLegacyExternalStorage = "true" on my AndroidManifest.xml solves my problem.

Thanks @dnsgusttavo for saving my day!

**Comment by 3rco** [comment]
I was getting  "attribute android:requestLegacyExternalStorage not found." error when I add requestLegacyExternalStorage = "true" on my AndroidManifest.xml.
adding compileSdkVersion 29 to defaultConfing in android/app/build.gradle solved my problem.

**Comment by mohdaamir8182** [comment]
> @bartolkaruza please reopen this issue as it's a real issue due to the introduction of [Scoped storage](https://developer.android.com/training/data-storage#scoped-storage) in Android 10 (API 29).
> 
> @herysihn918 one workaround meanwhile is by setting `android:requestLegacyExternalStorage` to `true` in your AndroidManifest.xml as described in https://developer.android.com/training/data-storage/use-cases#opt-out-scoped-storage

This solved my issue on Android 10. Thanks.

**Comment by faheem-cmd** [comment]
> Still having this error on a newly created app running on android 10. Solved it by setting `targetSdkVErsion = 28` but I'm not sure if this has implications on the app I'm building.

You saved my life
