### ISSUE TITLE
Document troubleshooting linking issues

### ISSUE THREAD

**Issue by bartolkaruza** [react-native-cameraroll/react-native-cameraroll#198]
# Feature request

This issue is opened to keep track of the effort to document all the possible issues and solutions related to linking the library.

As part of this effort, we could overhaul the docs related to manual linking and point everyone to auto-linking by default and keep manual linking as a very last resort.

## Why it is needed

It looks like people run into problems related to linking often. The issues are not always related to the library, but providing some information about how to resolve them, could help them getting started with the library faster.

Example issues that people run into:
#191 #179 #136 #155 #147 #144 #142 #128 #113 #96 (and others ...)

**Comment by ravi-roxiler** [comment]
Any update on this? @bartolkaruza
