### ISSUE TITLE
Not getting system generated albums in my iPhone

### ISSUE THREAD

**Issue by tvpranav** [react-native-cameraroll/react-native-cameraroll#204]
I am not getting system generated albums in my iPhone, like Favorites, Recent etc.

CameraRoll.getAlbums({
      assetType: 'All',
    })
      .then(res => {
        console.log('Albums.....................', res)
      })
      .catch((error) => {
        console.log(error.message)
      })

**Could you please help to to solve this ?**

**Comment by bartolkaruza** [comment]
We are currently only returning the 'album' PHAssetCollectionType case. The 'generated' albums are of the 'smartAlbum' case: https://developer.apple.com/documentation/photokit/phassetcollectiontype.

Adding the additional case would be a small change here: https://github.com/react-native-community/react-native-cameraroll/blob/4da8310892cf2188ead33260c157682944edd7e9/ios/RNCCameraRollManager.m#L205

Happy to review a PR for this!

https://developer.apple.com/documentation/photokit/phassetcollection/1618510-fetchassetcollections

**Comment by autumnlaneweb** [comment]
Thanks @bartolkaruza for reverting on this. By using your suggestion. I have changed that line with 

`PHFetchResult<PHAssetCollection *> *const assetCollectionFetchResult = [PHAssetCollection fetchAssetCollectionsWithType:PHAssetCollectionTypeSmartAlbum subtype:PHAssetCollectionSubtypeAlbumRegular options:options];`

By this, Smart Albums are getting properly but not getting album wise photos with album name 'groupName'.

**Please suggest me the better way to do this**

**Comment by tvpranav** [comment]
Thanks @bartolkaruza for reverting on this. By using your suggestion. I have changed that line with

`PHFetchResult<PHAssetCollection *> *const assetCollectionFetchResult = [PHAssetCollection fetchAssetCollectionsWithType:PHAssetCollectionTypeSmartAlbum subtype:PHAssetCollectionSubtypeAlbumRegular options:options];`

By this, Smart Albums are getting properly but not getting album wise photos with album name 'groupName'.

**Please suggest me the better way to do this**

**Comment by bartolkaruza** [comment]
To make both cases work, I think we would need to fetch both and merge the results

**Comment by WarrenBuffering** [comment]
Still seeing this issue in **4.0.4**. `CameraRoll.getAlbums({ assetType: 'All' }) only returns user generated albums on iOS. Does anyone know if there's a fix coming soon? Or has anyone found a good workaround for the time-being?

**Comment by akmal-k** [comment]
> > @valentynberehovyi Hello, I was also facing with SmartAlbum problems in release mode. In development mode SmartAlbum works fine, but in release mode it's bringing the Albums name but not images. Do you have any solution for it ? Thanks
> 
> you can this repo for this issue https://github.com/Fredi70/react-native-cameraroll

Thank you for your reply . I installed the repo, but it's still have a problem.
