### ISSUE TITLE
App is getting crash while reading photos in iOS.

### ISSUE THREAD

**Issue by tvpranav** [react-native-cameraroll/react-native-cameraroll#211]
👋 Hi!

I have found one issue in my crash logs.

**RNCCameraRollManager.m - Line 393
__49-[RNCCameraRollManager getPhotos:resolve:reject:]_block_invoke_2 + 393**

My iOS App is getting crash while getting photos and the code is:

`[assets addObject:@{
        @"node": @{
          @"type": assetMediaTypeLabel, // TODO: switch to mimeType?
          @"group_name": currentCollectionName,
          @"image": @{
            @"uri": uri,
              @"filename": (includeFilename && originalFilename ? originalFilename : [NSNull null]),
              @"height": (includeImageSize ? @([asset pixelHeight]) : [NSNull null]),
              @"width": (includeImageSize ? @([asset pixelWidth]) : [NSNull null]),
              @"fileSize": (includeFileSize ? fileSize : [NSNull null]),
              @"playableDuration": (includePlayableDuration && asset.mediaType != PHAssetMediaTypeImage
                                    ? @([asset duration]) // fractional seconds
                                    : [NSNull null])
          },
          @"timestamp": @(asset.creationDate.timeIntervalSince1970),
          @"location": (includeLocation && loc ? @{
              @"latitude": @(loc.coordinate.latitude),
              @"longitude": @(loc.coordinate.longitude),
              @"altitude": @(loc.altitude),
              @"heading": @(loc.course),
              @"speed": @(loc.speed), // speed in m/s
            } : [NSNull null])
          }
      }];`

Please revert on this ASAP.

**Comment by dokkis** [comment]
@tvpranav can you explain better where does it break and which commit needs to be reverted?

**Comment by tvpranav** [comment]
@dokkis It is breaking while getting photos in iPhone X (iOS version 13.5), May be any media is broken/corrupt in phone. It is working on iPhone XR (iOS version 13.5).

Error on line in **RNCCameraRollManager.m** where we set image object @"image": @{}.

**Comment by dokkis** [comment]
@tvpranav are you able to try older version of the library to check if there is any that works and doesn't break to identify the change that bring this bug?

**Comment by dokkis** [comment]
@tvpranav are you able to try out older versions of the library, to understand which version bring the problem in?

**Comment by Isaacwhyuenac** [comment]
I am experiencing similar issue too.
```js
{
    "@react-native-community/async-storage": "^1.11.0",
    "@react-native-community/cameraroll": "^4.0.0",
    "apollo-cache-inmemory": "^1.6.6",
    "apollo-client": "^2.6.10",
    "apollo-link-context": "^1.0.20",
    "apollo-link-http": "^1.5.17",
    "graphql": "^15.3.0",
    "graphql-tag": "^2.11.0",
    "react": "16.13.1",
    "react-apollo": "^3.1.5",
    "react-native": "0.63.2",
    "react-native-fbsdk": "^2.0.0",
    "react-native-linear-gradient": "^2.5.6",
    "react-native-navigation": "^6.10.1",
    "react-native-typography": "^1.4.1",
    "react-native-vector-icons": "^7.0.0"
}
```

When I write code to access the iPhone 11/ 11Pro Simulator (iOS 13.5) to access the CameraRoll, it crashes the App and return to the iPhone home screen.

**Comment by laurentlouk** [comment]
I got the same bug because I did not add the keys into info.plist

```html
    <key>NSPhotoLibraryUsageDescription</key>
    <string>This app requires access to the photo library.</string>
    <key>NSPhotoLibraryAddUsageDescription</key>
    <string>This app requires access to the photo library.</string>
```
it's not possible to add these with react native link ?
