### ISSUE TITLE
When photo/video has rotation the imageSize property will be wrong on Android

### ISSUE THREAD

**Issue by Rotemy** [react-native-cameraroll/react-native-cameraroll#212]
Hi, I'm using the latest version 4.0.0 and when I use `CameraRoll.getPhotos` to fetch images and videos with rotation (90 degrees) the width and height will be opposite.

Here is the info when using ffprob on a video file:

```
    Stream #0:0(und): Video: hevc (Main) (hvc1 / 0x31637668), yuv420p(tv, bt709), 1920x1080, 11409 kb/s, 60 fps, 60 tbr, 600 tbn, 600 tbc (default)
    Metadata:
      rotate          : 90
      creation_time   : 2020-07-05T15:11:27.000000Z
      handler_name    : Core Media Video
      encoder         : HEVC
```

I'm getting in the image properties width 1920 and height 1080 which ok I guess, but there is no way for me to know the video is rotated by 90 degrees.

Any workaround for it?

**Comment by bartolkaruza** [comment]
I'm not aware of a workaround of the top of my head, we will probably need to include the orientation separately.

**Comment by german970814** [comment]
Same issue, any workaround about that?

**Comment by MarcoScabbiolo** [comment]
PR #278 includes the orientation and allows this simple workaround

```typescript
let width = image.width
let height = image.height

if (
  Platform.OS === 'android' &&
  (image.orientation === 90 || image.orientation === 270)
) {
  width = image.height
  height = image.width
}

const fixedImage = {
  ...image,
  width,
  height,
}
```
