### ISSUE TITLE
How do I delete photos from my camera roll?

### ISSUE THREAD

**Issue by jairrc** [react-native-cameraroll/react-native-cameraroll#214]
How do I delete photos from my camera roll? The documentation example doesn't work. Does anyone have any example of code that you have used, that really does the deletion, please?

This is my Code:

  **deletePhotos = () => {
    const photos = [...this.state.photos];
    photos.map((item) => {
      CameraRoll.deletePhotos([item.image.uri]);
    })
  }**

**This is the content of the URI:**
![image](https://user-images.githubusercontent.com/1241980/87192649-4b8f7b00-c2cd-11ea-8df0-f3125878fcd3.png)

**This is the error that occurs:**
![image](https://user-images.githubusercontent.com/1241980/87192347-aa082980-c2cc-11ea-806b-268d7178bbc2.png)

**This documentation example is incomplete or does not work:**
![image](https://user-images.githubusercontent.com/1241980/87190448-e2a60400-c2c8-11ea-9b0a-2e5540a18fab.png)

**Comment by DiogoAbu** [comment]
The uri you are using has the `content` protocol, which is like a link, a shortcut to the actual file (the file may not event exist).
The `deletePhotos()` expects an uri with the `file` protocol, the actual path.

You can use `stat` from `react-native-fs` to get the actual path. It will throw an error if the file does not exist.

**Comment by bartolkaruza** [comment]
Looks like @DiogoAbu answer solves this. Closing, let me know if it needs reopening
