### ISSUE TITLE
Using fromTime filter on Android SDK 29 returns empty edges

### ISSUE THREAD

**Issue by tauqeer81** [react-native-cameraroll/react-native-cameraroll#216]
# Bug report

## Summary

On **Android SDK 29** `CameraRoll.getPhotos({ first: 10, assetType: 'Photos', groupTypes: 'All', fromTime: 1584356434595, //5 hours back toTime: moment().valueOf(), })` returns empty `edges`. However it works perfect on **Android SDK 28**.

Here's my code

`    const params = {
      first: 10,
      assetType: 'Photos',
      groupTypes: 'All',
      fromTime: 1584356434595, // 5 hours back,
      toTime: moment().valueOf(),
    };
    CameraRoll.getPhotos(params)
      .then(r => {
        console.log(r.edges) // This returns empty array []
      });`

How to resolve this issue?

## Environment info

{
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "android": "react-native run-android",
    "ios": "react-native run-ios",
    "start": "react-native start",
    "test": "jest",
    "lint": "eslint .",
    "clean:android": "cd android && ./gradlew clean && cd ../",
    "clean:ios": "cd ios && xcodebuild clean && cd ../"
  },
  "dependencies": {
    "@react-native-community/async-storage": "^1.8.1",
    "@react-native-community/cameraroll": "^4.0.0",
    "@react-native-community/geolocation": "^2.0.2",
    "@react-native-community/masked-view": "^0.1.6",
    "@react-native-community/netinfo": "^5.6.2",
    "@react-native-community/picker": "^1.5.0",
    "@react-navigation/native": "^5.0.8",
    "@react-navigation/stack": "^5.1.0",
    "@unimodules/core": "^5.0.0",
    "axios": "^0.19.2",
    "moment": "^2.24.0",
    "moment-range": "^4.0.2",
    "react": "16.9.0",
    "react-moment": "^0.9.7",
    "react-native": "^0.62.2",
    "react-native-background-timer": "^2.2.0",
    "react-native-camera": "git+https://git@github.com/react-native-community/react-native-camera.git",
    "react-native-fast-image": "^8.1.5",
    "react-native-fs": "^2.16.1",
    "react-native-geolocation-service": "^4.0.0",
    "react-native-gesture-handler": "^1.6.0",
    "react-native-gradient-buttons": "^2.0.1",
    "react-native-image-placeholder": "^1.0.14",
    "react-native-image-view": "^2.1.9",
    "react-native-inappbrowser-reborn": "^3.4.0",
    "react-native-linear-gradient": "^2.5.6",
    "react-native-onesignal": "^3.7.3",
    "react-native-reanimated": "^1.7.0",
    "react-native-responsive-screen": "^1.4.0",
    "react-native-s3-upload": "0.0.12",
    "react-native-safe-area-context": "^0.7.3",
    "react-native-screens": "^2.2.0",
    "react-native-simple-toast": "^1.1.2",
    "react-native-splash-screen": "^3.2.0",
    "react-native-storage": "^1.0.1",
    "react-native-vector-icons": "^6.6.0",
    "react-navigation": "^4.1.1",
    "react-navigation-hooks": "^1.1.0",
    "react-redux": "^7.2.0",
    "redux": "^4.0.5",
    "redux-actions": "^2.6.5",
    "redux-thunk": "^2.3.0"
  },
  "devDependencies": {
    "@babel/core": "7.8.4",
    "@babel/runtime": "7.8.4",
    "@react-native-community/eslint-config": "0.0.5",
    "babel-jest": "^25.4.0",
    "eslint": "6.8.0",
    "husky": "^4.2.5",
    "jest": "^25.4.0",
    "metro-react-native-babel-preset": "0.56.4",
    "react-test-renderer": "16.9.0"
  },
  "husky": {
    "hooks": {
      "pre-commit": "npm run lint"
    }
  },
  "jest": {
    "preset": "react-native"
  }
}

Library version: 0.62.2

**Comment by cowkite** [comment]
I have same issue. Did you fix it?

**Comment by nikohpng** [comment]
I have same issue

**Comment by nathancheung22** [comment]
I'm having the same issue. Has anyone found a fix for this?

**Comment by mishsom** [comment]
This does not work correctly on Android 30 as well. I am getting >100 with ```has_next_page: true
``` images without fromTime/toTime query but getting 1 edge when firing in the same query with fromTime and toTime from the above result set only.

**Comment by nsh96hp** [comment]
https://github.com/react-native-cameraroll/react-native-cameraroll/releases/tag/v4.0.3
https://github.com/react-native-cameraroll/react-native-cameraroll/pull/277

It seems that in case it uses dateAdded it is necessary to search by dateAdded. But now is always dateTaken.
