### ISSUE TITLE
[Unhandled promise rejection: TypeError: null is not an object (evaluating '_nativeInterface.default.saveToCameraRoll')]

### ISSUE THREAD

**Issue by RomanKwok** [react-native-cameraroll/react-native-cameraroll#217]
Hi

`const getCameraRollPermissionAsync = async (uri) => {
    if (Constants.platform.ios) {
      const { status } = await Permissions.askAsync(Permissions.CAMERA_ROLL);
      if (status !== 'granted') {
      } else {
        CameraRoll.save(uri);
      }
    } else {
      CameraRoll.save(uri);
    }
  };

  const pickImage = async () => {
    try {
      let result = await ImagePicker.launchCameraAsync({
        mediaTypes: ImagePicker.MediaTypeOptions.Images,
        allowsEditing: false,
        quality: 1,
      });
      if (!result.cancelled) {
        setImage(result.uri);
        getCameraRollPermissionAsync(result.uri);
      } else {
        navigation.goBack();
      }
    } catch {
      alert(i18n.t('camera_error').toUpperCaseFirstChar());
      navigation.goBack();
    }
  };`

> [Unhandled promise rejection: TypeError: null is not an object (evaluating '_nativeInterface.default.saveToCameraRoll')]

"expo": "~38.0.8",
"react-native": "https://github.com/expo/react-native/archive/sdk-38.0.2.tar.gz",
"@react-native-community/cameraroll": "^4.0.0",

Help!  What's wrong with my code？

**Comment by costr** [comment]
Hopefully you've figured this out but I just ran into the same issue and stumbled upon your issue post. After some trial and error I found that I needed to destroy my build folder, for Android, and rebuild/redeploy it completely. Once I did that everything worked as I would expect.

**Comment by psdevss** [comment]
Hey how did you fix this on iOS

**Comment by Masadow** [comment]
@psdevss Maybe you forgot to run `pod install` ?

**Comment by peterburgs** [comment]
Hi mate, any workaround yet?

**Comment by tanu4543** [comment]
is there any workaround this issue!!
i am trying to add Inappbrowser to my react-native app and while execution command run-android, i am facing the same error. (FYI i am using react-native-cli)\

**Comment by hb-webdev** [comment]
For iOS I just went into XCode and did `Product` > `Clean Build Folder`, `Product` > `Build`, deleted the app from the iPhone, then ran (with `npx react-native run-ios --device`)

**Comment by nolife08021** [comment]
hi, i facing this issue on debug, release/ production mode too. Any solution for this?
