### ISSUE TITLE
IOS - only get uri which start with ph://...

### ISSUE THREAD

**Issue by pyeonjaesik** [react-native-cameraroll/react-native-cameraroll#218]
I want to get uri which start with file:///.

because I want to set video uri and upload that file.

but uri which start with ph:/// have many errors

**Comment by dolphinflow86** [comment]
Facing same error

**Comment by tegozen** [comment]
me too( the code worked a month ago

**Comment by tegozen** [comment]
`
/**
 * I write a litte util method to convert localIdentifier to assetURL in JavaScript
 * @param localIdentifier looks like 91B1C271-C617-49CE-A074-E391BA7F843F/L0/001
 * @param ext the extension: JPG, PNG, MOV
 * @returns {string}
 */
export const convertLocalIdentifierToAssetLibrary = (localIdentifier, ext) => {
  const hash = localIdentifier.split('/')[0];
  return `assets-library://asset/asset.${ext}?id=${hash}&ext=${ext}`;
};

export const GetAssets = async (params = { first: 11 }) => {
  if (Platform.OS === "android" && !(await Keyboard.hasAndroidPermission())) {
    return;
  }

  let result = await CameraRoll.getPhotos({ ...params, assetType: 'All' })
  result.edges.map(async (edge) => {
    if (Platform.OS === 'ios') {
      edge.node.image.uri = convertLocalIdentifierToAssetLibrary(edge.node.image.uri.replace('ph://', ''), edge.node.type === 'image' ? 'jpg' : 'mov')
    }
    return
  })
  return result
};
`
work for me

**Comment by simonepauro** [comment]
https://github.com/react-native-cameraroll/react-native-cameraroll/issues/195#issuecomment-705053078

**Comment by anhquan291** [comment]
> I want to get uri which start with file:///.
> 
> because I want to set video uri and upload that file.
> 
> but uri which start with ph:/// have many errors

I have the same issue here. Any helps, please. Thanks a lot

**Comment by nxa127** [comment]
> ```
> /**
>  * I write a litte util method to convert localIdentifier to assetURL in JavaScript
>  * @param localIdentifier looks like 91B1C271-C617-49CE-A074-E391BA7F843F/L0/001
>  * @param ext the extension: JPG, PNG, MOV
>  * @returns {string}
>  */
> export const convertLocalIdentifierToAssetLibrary = (localIdentifier, ext) => {
>   const hash = localIdentifier.split('/')[0];
>   return `assets-library://asset/asset.${ext}?id=${hash}&ext=${ext}`;
> };
> 
> export const GetAssets = async (params = { first: 11 }) => {
>   if (Platform.OS === "android" && !(await Keyboard.hasAndroidPermission())) {
>     return;
>   }
> 
>   let result = await CameraRoll.getPhotos({ ...params, assetType: 'All' })
>   result.edges.map(async (edge) => {
>     if (Platform.OS === 'ios') {
>       edge.node.image.uri = convertLocalIdentifierToAssetLibrary(edge.node.image.uri.replace('ph://', ''), edge.node.type === 'image' ? 'jpg' : 'mov')
>     }
>     return
>   })
>   return result
> };
> ```
> 
> 
> work for me

thank, work for me too

**Comment by AndriiHnedko** [comment]
Most external libraries cannot read files from _**ph:///**_ link (including popular `axios` and `react-native-video`).

If you need just to upload the file, use the Fetch API from RN, it always works. This solution never let me down.

If you need it for other purposes, then use [`react-native-fs`](https://github.com/itinance/react-native-fs), and him methods copyAssetsFileIOS or copyAssetsVideoIOS. It is also a 100% working solution.

Also a similar feachures is present in `[rn-fetch-blob](https://github.com/joltup/rn-fetch-blob)`, this library works much faster with the file system compared `react-native-fs`. I had a lot of problems with this library, so use it at your own risk.

**Comment by SolankiYogesh** [comment]
I ran into the same problem and created a small package to resolve it.
You can check it out here: [rn-camera-roll-fetcher-ios](https://github.com/SolankiYogesh/rn-camera-roll-fetcher-ios)
.

It converts ph:// asset URIs into local file:// paths on iOS using turbomodule, which might help with this issue.
