### ISSUE TITLE
Total count for all photos

### ISSUE THREAD

**Issue by maharleeeka** [react-native-cameraroll/react-native-cameraroll#225]
# Question

Is it possible to retrieve the total count for all photos?

What I tried so far is

```
const totalImagesCount = await CameraRoll.getPhotos({
      first: 9999,
      ... { additional parameters }
 }).then(res => res && res.edges && res.edges.length))
```

but that would limit the result to 9999.

Thank you for any help

**Comment by sidongmen** [comment]
interface totalProp {
    next: boolean;
    after?: string;
    total: number;
}

**Comment by sidongmen** [comment]
`interface totalType {
    next: boolean;
    after?: string;
    total: number;
}`

`const [total, setTotal] = useState<totalType>({total: 0, next: true});`

    const getTotal = () => {
        CameraRoll.getPhotos({first: 100, after: total.after })
        .then(({edges, page_info})=>{
            const newCount = edges.length;
            const nextPage = page_info.has_next_page;
            const after = page_info.end_cursor;
            setTotal({total: total.total + newCount, next: nextPage, after: after});
        })
    }

    useEffect(() => {
        if (total.next) {
            getTotal();
        } else {
            console.log('total : ',total.total)
        }
    },[total])

Bring 100 pictures each, add the count of photos, and repeat until there is no next page.

**Comment by vforvasile** [comment]
Or use `getAlbums` method and count their items:

```
 const albums = await CameraRoll.getAlbums({ assetType: 'All' });
 const totalPics = albums.reduce((total, current) => total + current.count, 0);
```

**Comment by maharleeeka** [comment]
@sidongmen Thank you for the input. I was hoping for something that doesn't require pagination since our design will show  All Photos and it's total count.

**Comment by maharleeeka** [comment]
@vforvasile Thank you for the input. That is what we actually have right now. It works well for android but iOS have the issue where the system generated albums are not getting fetched thus we we can't get the exact count for the "All Photos".
