### ISSUE TITLE
how to save a image inner project/bundle, such as '../images/xxx.png'

### ISSUE THREAD

**Issue by zyestin** [react-native-cameraroll/react-native-cameraroll#232]
# save local image from project/bundle

## Why it is needed

In many cases, we want to save an image from project, but not from server through network, eg:  '../images/xxx.png' . 

## Possible implementation

Now cameraroll provides method `save()`, we should input a string.
If input '../image/xxx.png',   `save()` will not work. 
So, we can provide a `saveImageData()` to receive a data type ,or provide `saveProjImage()` to receive a string type like ' '../images/xxx.png' .

**Comment by tingtien** [comment]
face the same issue
