### ISSUE TITLE
Support React Native v0.63.

### ISSUE THREAD

**Issue by chrisbobbe** [react-native-cameraroll/react-native-cameraroll#233]
Like https://github.com/react-native-community/react-native-cameraroll/issues/127, but for React Native v0.63. RN v0.63 was [released](https://reactnative.dev/blog/2020/07/06/version-0.63) on 2020-07-06. There don't appear to be any [announced breaking changes](https://github.com/react-native-community/releases/blob/master/CHANGELOG.md#v0630) that would affect this library, but I might have missed some, and in any case thorough testing should be done.

- The upper bound for `"react-native"` under `peerDependencies` should be increased to include 0.63.
- `"react-native"` in `devDependencies` should be set to the current latest 0.63, and `"react"` and `"flow-bin"` (maybe more) should be updated to match whatever the `react-native` repo has for those at its current latest 0.63.
- If things break, adjustments to the code might be necessary.
  - If these adjustments break compatibility with older versions of React or React Native that are within their previous range under `peerDependencies`, then the range should be narrowed to exclude those versions, and it becomes a breaking change. (This is easy to miss; see https://github.com/semver/semver/issues/502#issuecomment-466501843, and, e.g., https://github.com/react-native-community/react-native-webview/issues/1445#issue-635011818.)
  - Before making a release, do a sanity check on the peer-dep ranges for `react-native` and `react`, keeping in mind that every React Native version (that I've seen) is pinned to a single React version. E.g., see https://github.com/react-native-community/react-native-webview/issues/1445#issuecomment-642887123, where I pointed out that a React peer-dep range of ^16.9 effectively means that React Native versions before 0.61 are not supported, even if the `react-native` peer-dep range includes versions before 0.61.

**Comment by fairlycasual** [comment]
Thanks @chrisbobbe, this would be very useful for our organization as well as we are in the middle of upgrading RN from 0.61.4 to 0.63.2, and have come to this point blocking us on iOS. We will attempt to fork the library into our own repo and make these changes to see if they solve the issues we are facing, and if we are successful could open a PR for the changes. Otherwise, I think we can achieve the same save functionality using RNFS utilities.

**Comment by fairlycasual** [comment]
I should note that no alterations to the package were necessary in the end during our upgrade process. We just needed to create a bridging header to let Swift and Objective-C libraries communicate together. Now all works as expected. A quick resource can be found at: 
https://stackoverflow.com/a/56187043

**Comment by fairlycasual** [comment]
I should note that no alterations to the package were necessary in the end during our upgrade process. We just needed to create a bridging header to let Swift and Objective-C libraries communicate together. Now all works as expected. A quick resource can be found at:
https://stackoverflow.com/a/56187043
more info:
https://developer.apple.com/documentation/swift/imported_c_and_objective-c_apis/importing_objective-c_into_swift
https://support.swiftify.com/hc/en-us/articles/360032764371-Using-Objective-C-and-Swift-Bridging-Headers

**Comment by bartolkaruza** [comment]
@chrisbobbe that looks like all the right steps to me. Happy to review a PR! Also I'd like to bring this one to your attention: #242

**Comment by chrisbobbe** [comment]
> Happy to review a PR!

Great, thanks, @bartolkaruza! I've got one: #264. You'll see a couple of checkboxes in my description there that aren't checked, but hopefully I've added a clear explanation for why they haven't been checked yet (mostly, because I'm not sure how best to do something). 🙂
