### ISSUE TITLE
How to get hidden folder image in this, I want to get .Statuses folder image in my application

### ISSUE THREAD

**Issue by thejogsa** [react-native-cameraroll/react-native-cameraroll#235]
Images folder path is whatsapp status, I want to get this images and video using this library

**How to get this folder in Android - WhatsApp/Media/.Statuses**

CameraRoll.getPhotos({
                first: 500,
                groupTypes: 'All',
                groupName: '.Statuses',
                assetType: 'All'
  }).then(r => 
      {
                    setPostList(r.edges)
                    console.log('data success ',r);
                }
            ).catch(err => console.log('Error ', err))

**Comment by dwb1994** [comment]
similar question, is there some way to get & save to 'hidden' albums?
