### ISSUE TITLE
How to get photos in sequence same as Album "Recents"?

### ISSUE THREAD

**Issue by dressas** [react-native-cameraroll/react-native-cameraroll#237]
Bases on the current configuration, getPhotos() are in sequence of the descending order of creation time.
However, when images are transferred by Airdrop in IOS, the creation time of the images are kept the same and when call getPhotos(), those photos are inserted somewhere based on the creation time.
Do I have a way to get photos in a sequence like Album "Recents"?
Thanks.

**Comment by gontovnik** [comment]
I was facing the same issue today. Unfortunately, there is currently no way to achieve it using this library. If you need to simply replicate "Recents", I'd just create your own native module.
