### ISSUE TITLE
Invalid column longitude after update cameraroll to version 4.0.0 targetSdkVersion to 29

### ISSUE THREAD

**Issue by najib-pw** [react-native-cameraroll/react-native-cameraroll#238]
# Question

![Screen Shot 2020-09-23 at 19 30 57](https://user-images.githubusercontent.com/56715892/94012890-8c2e6900-fdd3-11ea-83fa-391630d71a11.png)

question: error Invalid column longitude after update cameraroll to version 4.0.0 targetSdkVersion to 29

dependencies:
cameraroll 4.0.0

buildscript {
    ext {
        buildToolsVersion = "29.0.3"
        minSdkVersion = 17
        compileSdkVersion = 29
        targetSdkVersion = 29
        supportLibVersion = "29.0.0"
    }

expected to happen:

Example runs as expected

**Comment by nicoburns** [comment]
Are you sure you've properly installed version 4.0.0. I was having this issue in earlier versions, but upgrading has solved it for me.

**Comment by selvaTecky** [comment]
may I know which version you're using @nicoburns

**Comment by nicoburns** [comment]
I'm using 4.0.1, and haven't seen this issue since upgrading to that version (from a much lower version).

**Comment by selvaTecky** [comment]
It was working fine upto android 9 the issue is occurs only on android 10 @nicoburns
