### ISSUE TITLE
Looking for maintainers

### ISSUE THREAD

**Issue by bartolkaruza** [react-native-cameraroll/react-native-cameraroll#242]
Hi there,

I'm currently not working on apps that use this library so testing PR's adds a lot of overhead for me. Because of this, I can only sporadically look at open issues and PR's and the library is starting to lag behind on updating Xcode, Gradle, React Native, etc.. versions as well as some key issues are staying open far too long.

If you care about this library, use it in an app under active development and have some spare time available I'm happy to add you as a maintainer. I'll be available to bring you up to speed and support you in maintaining going forward. More than one person is welcome to join if interested.

This library has followed the [Lean Core](https://github.com/facebook/react-native/issues/23313) path, starting out as a component in the core of React Native. Since I helped extract it to the React Native Community org, I've been handling the merging of PR's and responding to open issues as well as some general coordination of activities around this library.

Due to [a recent change](https://github.com/react-native-community/discussions-and-proposals/issues/176#issuecomment-693569246) in the definition of the role of the 'react-native-community' organisation on Github and NPM, this library will be moved to another Github and NPM organisation. If you'd like to maintain this library, this could be an opportunity to continue this library under your personal Github or under your companies Github for added exposure.

Drop me a message if you're interested > https://twitter.com/bartolkaruza

**Comment by bartolkaruza** [comment]
Just tagging a few people based on relatively recent contributions, for some visibility for this issue. 

@thekevinbrown @FrikkieSnyman @hsource @dokkis @r0b0t3d @Naturalclar 

Feel free to add if I missed anyone

**Comment by r0b0t3d** [comment]
@bartolkaruza Thanks for calling me out 😄 .
I'd love to contribute to open source projects. But currently I am working on projects that haven't use this library yet.
I can help with issues when I having spare time, but acting as a maintainer seems too much to me.
Hope someone can help you out with this!

**Comment by thekevinbrown** [comment]
Hey there!

The app we built and shipped with this library is still out there, but we are no longer maintaining it, so I'd be in a similar boat to you. That being said, I'd be happy to help out in the time I do have to work on open source, so if there's nobody that wants to spearhead the maintenance effort, I can at least help make the sporadic-ness gaps smaller by working with you.

**Comment by Naturalclar** [comment]
I don't have enough time to spend full time maintaining this project, but I can help out with pr reviews and triaging issues in my spare time

**Comment by FrikkieSnyman** [comment]
Also a bit tied up at the moment, unfortunately.

**Comment by tinacious** [comment]
With regards to Android 10+ support for scoped storage, I have some code that maybe the future maintainers can use. I developed a plugin that specifically allows users to save base64 encoded strings to their camera roll. It adds the support required for Android 10 and 11 **without** needing the `requestLegacyExternalStorage` flag—that flag is a bandaid solution but will be deprecated in August 2021 when all apps are required to target Android 11.

Here's the plugin: https://github.com/tinacious/react-native-save-base-sixty-four – You're welcome to copy the code I used to get it to save to camera roll, but it doesn't address any of the other features this plugin provides (e.g. reading from the camera roll, etc.), and it only supports base64 encoded images. So the feature set is very limited in comparison. Hopefully this helps.

Essentially you'd need to implement the content resolver API. The Android docs have a guide on this: https://developer.android.com/training/data-storage/shared/media?hl=en

Related issues: https://github.com/react-native-cameraroll/react-native-cameraroll/issues/244, https://github.com/react-native-cameraroll/react-native-cameraroll/issues/261, https://github.com/react-native-cameraroll/react-native-cameraroll/issues/248, https://github.com/react-native-cameraroll/react-native-cameraroll/issues/253

**Comment by mikbry** [comment]
@bartolkaruza I currently work on several projects that useCameraRoll. So I could help

**Comment by MarcoScabbiolo** [comment]
@bartolkaruza I would gladly help, we (my team) maintain a production app that relies on packages like this one, we can help with general maintenance, QA and testing (both iOS & Android) and bugfixes/features.

**Comment by bartolkaruza** [comment]
Thanks for stepping up guys! I've invited @Naturalclar @mikbry @MarcoScabbiolo and @doranteseduardo

It will be a much smaller workload if shared. You all have my personal contact info, feel free to ask me any questions about the details of maintaining this package. I'm going to resolve this issue now.
