### ISSUE TITLE
Image not getting saved

### ISSUE THREAD

**Issue by AnoukDunu** [react-native-cameraroll/react-native-cameraroll#248]
I installed everything properly but the image doesn't get saved even after providing the image path.

**Comment by moygospadin** [comment]
> I installed everything properly but the image doesn't get saved even after providing the image path.

Hello,u solved it?

**Comment by enisinanaj** [comment]
Please specify which system you get the issue on. Is it Android? iOS or what?

**Comment by raazatul7** [comment]
In the iOS image is not getting saves and there is not error message 

```
path = "/private/var/mobile/Containers/Data/Application/D88F1AF7-79D9-4B90-9C25-3C07D6844F71/tmp/react-native-image-crop-picker/39C29065-1148-467C-AE9A-26486BBC9230.jpg"
 CameraRoll.save(path, { type: "photo" })
        .then((resolve) => {
          console.log("resolve", resolve);
        })
        .catch((reject) => {
          console.log("reject", reject); //Error: Permission denied
        });
```

**Comment by raazatul7** [comment]
For iOS did you installed the pod files?

**Comment by enisinanaj** [comment]
I've had no problems with iOS so far. Had a problem with Android 10 though. #244
