### ISSUE TITLE
.mp4 files are returned with .getPhotos

### ISSUE THREAD

**Issue by lvillacin** [react-native-cameraroll/react-native-cameraroll#255]
When I user .getPhotos I also get .mp4 files.

**Comment by gsavvid** [comment]
@lvillacin the name `getPhotos()` is indeed a bit misleading as it returns both photos and videos. If you're only interested in the photos then you need to specify `getPhotos({assetType: 'Photos'})`. Have a look [here](assetType) for all the options.

**Comment by lvillacin** [comment]
@gsavvid Thanks! That indeed help. renaming that method might be hard to do so I think it would be better if the documentation can explicitly say this. Thank you very much!
