### ISSUE TITLE
install this lib in react-native 0.63.2 ,  dynamic load the lib with error

### ISSUE THREAD

**Issue by reylen** [react-native-cameraroll/react-native-cameraroll#259]
install this lib in react-native 0.63.2 ,  
dynamic load the lib with error 'xxx not found for architecture arm64',
`use_frameworks!`
while I change 
`s.dependency 'React'`
in file "react-native-cameraroll.podspec" to 
`s.dependency 'React-Core`
and then pod install,
 rebuild the project, 
the error dismiss!

maybe something change in react-native 0.63

**Comment by chrisbobbe** [comment]
I suspect this would be addressed by https://github.com/react-native-cameraroll/react-native-cameraroll/pull/260; you can follow a link to there for more details.
