### ISSUE TITLE
Support Android Target SDK 29 on Android Q Devices

### ISSUE THREAD

**Issue by olkunmustafa** [react-native-cameraroll/react-native-cameraroll#261]
With newly added features in AndroidSDK 29, the apps can not open the other folders that are opened by different apps. It's why the gallery is not opening when using react-native-cameraroll library.

[The official document link.](https://developer.android.com/guide/topics/providers/document-provider)

I solved the problem by adding a new line in AndroidManifest file like below.

`<application android:requestLegacyExternalStorage="true" ... >
    ...
  </application>`

It is a temporary solution. The correct way is to create a copy of the image/video and save it in our app's directory. 
I am also working on this issue, until the found a permanent solution, other developers can use the other suggestion that I write above.

**Comment by laurentlouk** [comment]
I spent 1 hour looking for this, could you please update the README :D

**Comment by billnbell** [comment]
+1
