### ISSUE TITLE
Cannot download format webp on iOS

### ISSUE THREAD

**Issue by PrayaAmadigaPitasa** [react-native-cameraroll/react-native-cameraroll#269]
I can't save image with format webp on iOS. It works on android

**Comment by lukebrandonfarrell** [comment]
@PrayaAmadigaPitasa This is not an issue with the library, iOS does not support WebP photo format.

**Comment by PrayaAmadigaPitasa** [comment]
omg... 
okkay, thank you for the information @lukebrandonfarrell

**Comment by baronha** [comment]
@PrayaAmadigaPitasa Have you resolved this issue yet?
