### ISSUE TITLE
Can't save video on iOS

### ISSUE THREAD

**Issue by eraldoforgoli** [react-native-cameraroll/react-native-cameraroll#270]
Hi,
I am trying to save videos on camera roll, but fails with the exception: 
```
{"code":"E_UNABLE_TO_SAVE","message":"The operation couldn’t be completed. (Cocoa error -1.)","domain":"NSCocoaErrorDomain ....
[RNCCameraRollManager saveToCameraRoll:options:resolve:reject:]_block_invoke.112 + 267","3   Photos                              0x00007fff2d263840 __83-[PHPhotoLibrary _performCancellableChanges:withInstrumentation:completionHandler:]_block_invoke + 62","4   Photos                              0x00007fff2d263c49 __93-[PHPhotoLibrary _commitTransactionOnExecutionContext:withInstrumentation:completionHandler:]_block_invoke + 117","5   Photos   
```
Saving images works fine. I have tried to provide the type of file that will be saved, but if does not work.
```
    CameraRoll.save(path, { album: "MyALbum", type: type })
```

**Comment by eraldoforgoli** [comment]
I solved the issue, in order for videos to be saved, i downloaded the remote video using RNFetchBlob, then saved the video using camera roll. 
For anyone having issues, this is the code: 
`
RNFetchBlob.config({
    fileCache: true,
    appendExt: <fileextension here>
  })
    .fetch("GET", url)
    .then(async (resp) => {
     CameraRoll.save(resp.data, { album: "YourAlbumHere", type:  <"image" or "video" here> })
      .then(() => {
        console.log("saved");
      })
      .catch((err) => {
        console.log("error saving to camera roll");
      });
    })
    .catch((err) => {
      console.log(err);
      showMessage({
        type: "danger",
        message: JSON.stringify(err)
      });
    });
`

**Comment by mhmdalii** [comment]
i try to save image to imgfolder but i put name of folder to album proberty and not working , any help how u save images?
