### ISSUE TITLE
null is not an object when calling react-native camera roll

### ISSUE THREAD

**Issue by zendevil** [react-native-cameraroll/react-native-cameraroll#273]
I'm using the @react-native-community/cameraroll library to upload a video from the camera roll. For this, I'm using the getPhotos function. Using this function, however, is causing the following error:
```
null is not an object (evaluating '_nativeInterface.default.getPhotos')
```
I'm calling the getPhotos function as follows:
```
<Pressable onPress={() => {
          CameraRoll.getPhotos({first:10});
          }}
        style={({ pressed }) => [{
            backgroundColor: pressed ? 'white' : '#03befc'
        },
    styles.upload]}>
            <Text style={styles.uploadText}>Upload Video</Text></Pressable>

```

What's wrong with calling the camera roll like I've called it in the onPress event of the Pressable component that it's giving me the error that I mention?

**Comment by RichardQuiros** [comment]
The same thing happens to me with all the functions, it is as if they will not be imported correctly but I already see that. #https://github.com/react-native-cameraroll/react-native-cameraroll/labels/linking
