### ISSUE TITLE
VERY SLOW ON IOS

### ISSUE THREAD

**Issue by MuhammadTayyabDev** [react-native-cameraroll/react-native-cameraroll#276]
Hi,
I know you have mentioned well in the documentation of this great library that it becomes slow on IOS wen we use after prop. I have implemented it in one of my current projects on ANDROID its working perfect but It becomes too much slow on ios with after prop then I tried with from time and to time as you have suggested and I am calling the getPhotos function in synchronous loop.

Let me explain it a bit more 

- I call the getPhotos function with last month in from month and current date in todate (I am using unix timestamp as document suggests) and I got all the photos of the last month that is expected behavior.
- When in case of success I again call the same function with changed dates minus 1 month from both from and to dates then it returns 0 records.
- just first time I am getting the expected result and for all the other ietrations I get 0 in edges.
- and if I am trying to load all the images at once then app becomes slow so I want to auto paginate records on base of months or after check.

Please improve it for IOS so that we can use after prop with no side effects or can you please suggest a way that how we can get all the photos on base of from time and to time in loop same as we do incase of after we use it like auto pagination.

**Comment by burak4ydin** [comment]
still too slow while getting thousand of photos
