### ISSUE TITLE
I can't get access to albums like Favorites or Recent Photos on IOS

### ISSUE THREAD

**Issue by douglasgondim** [react-native-cameraroll/react-native-cameraroll#282]
No matter what, the albums do not return.

**Comment by JuraSemenenko** [comment]
Favorites, Selfies Recent are Smart Albums. There is no method who can give you this albums.
In line
`PHFetchResult<PHAssetCollection *> *const assetCollectionFetchResult = [PHAssetCollection fetchAssetCollectionsWithType:PHAssetCollectionTypeAlbum subtype:PHAssetCollectionSubtypeAny options:options];`
you ned change `fetchAssetCollectionsWithType:PHAssetCollectionTypeAlbum` to `fetchAssetCollectionsWithType:PHAssetCollectionTypeSmartAlbum`
And you need to update getPhotos method.

**Comment by anhquan291** [comment]
> Favorites, Selfies, Recent are Smart Albums. There is no method, who can give you this albums.
> In line
> `PHFetchResult<PHAssetCollection *> *const assetCollectionFetchResult = [PHAssetCollection fetchAssetCollectionsWithType:PHAssetCollectionTypeAlbum subtype:PHAssetCollectionSubtypeAny options:options];`
> you need change `fetchAssetCollectionsWithType:PHAssetCollectionTypeAlbum` to `fetchAssetCollectionsWithType:PHAssetCollectionTypeSmartAlbum`
> And you need to update getPhotos method.

Thank you. It works! however, is there a way that I can get them both the normal Album and the smart Album? 
Thank you so much

**Comment by seancheung** [comment]
Please add smart album support
