### ISSUE TITLE
How can I unselect the photos that were previously selected?

### ISSUE THREAD

**Issue by jonathans199** [react-native-cameraroll/react-native-cameraroll#283]
With this library `@react-native-community/cameraroll`  I've been able to use the `CameraRoll.deletePhotos([uri]);` function, however, this also deletes the actual photo from the phone. 

We are just looking to get a set of images located in the current roll and submit a post to create a product with the images. 

Unable to find online how to remove the temporary selected images. 
RN is > 0.63v

![Simulator Screen Shot - iPhone 11 - 2021-02-02 at 01 29 26](https://user-images.githubusercontent.com/30424887/106561105-1d39ed00-64f6-11eb-9ebf-c558345dd281.png)

**Comment by doranteseduardo** [comment]
Hello Jonathan.
Yes, the deletePhotos method indeed deletes the files from the device.

So the answer to your question is on your own implementation. 

When you select files, where do you register them?

Maybe an example of your code could help. 

Best regards.

**Comment by gaurav8809** [comment]
You can delete photo from the array in which you managing the image collection
As simple is that

**Comment by jonathans199** [comment]
Closing issue, had to create a separate view where to select the images from the camera roll. 

This was not clear nor included in the instructions, so was weeks thinking as to why was not working for my app.

**Comment by jonathans199** [comment]
Closing issue, had to create a separate view where to select the images from the camera roll.

This was not clear nor included in the instructions, so was weeks thinking as to why was not working for my app.
