### ISSUE TITLE
RCTNetworking.h file not found

### ISSUE THREAD

**Issue by lancwl418** [react-native-cameraroll/react-native-cameraroll#284]
React native version: 0.60.6
react-native-cameraroll: 4.0.2

I followed the instructions of the doc. But when I tried to build the ios, there is an error saying React/RCTNetworking.h file not found. I have tried to removed the node_modules and reinstall it and also did pod install. Thank you!
![image](https://user-images.githubusercontent.com/30207801/106949750-399a7d00-66e2-11eb-92d0-46ce1d31820c.png)

**Comment by lancwl418** [comment]
get it solved by downgrade to 1.5.0

**Comment by tomta20** [comment]
Same problem to me

**Comment by taminhtien** [comment]
Same problem

**Comment by medveodoff** [comment]
Just add "${PODS_ROOT}/Headers/Public/React-RCTNetwork" to Header Search Paths in Build Settings for pod "react-native-cameraroll"

**Comment by hejun041** [comment]
> 只需将“${PODS_ROOT}/Headers/Public/React-RCTNetwork”添加到Pod“react-native-cameraroll”的构建设置中的标题搜索路径

![image](https://user-images.githubusercontent.com/16474051/124106419-c4678400-da96-11eb-8a50-b8675ec768a9.png)
not for me

**Comment by medveodoff** [comment]
> > 只需将“${PODS_ROOT}/Headers/Public/React-RCTNetwork”添加到Pod“react-native-cameraroll”的构建设置中的标题搜索路径
> 
> ![image](https://user-images.githubusercontent.com/16474051/124106419-c4678400-da96-11eb-8a50-b8675ec768a9.png)
> not for me
<img width="1437" alt="Снимок экрана 2021-07-02 в 16 45 19" src="https://user-images.githubusercontent.com/58474441/124285444-98133c80-db56-11eb-9a4e-a7b9f4a1a097.png">

You must add this header for a pod "react-native-cameraroll", not for an entire project pod

**Comment by rechardcheng12345** [comment]
> Just add "${PODS_ROOT}/Headers/Public/React-RCTNetwork" to Header Search Paths in Build Settings for pod "react-native-cameraroll"


thanks, it works

**Comment by alvintd92** [comment]
> Just add "${PODS_ROOT}/Headers/Public/React-RCTNetwork" to Header Search Paths in Build Settings for pod "react-native-cameraroll"

Although this works, this needs to be done for every fresh "pod install".

**Comment by Arkan4ik** [comment]
@medveodoff thank you so much

**Comment by Arkan4ik** [comment]
@medveodoff how to get rid off to add those strings every time when you are using 'pod install'?

**Comment by Arkan4ik** [comment]
> > Just add "${PODS_ROOT}/Headers/Public/React-RCTNetwork" to Header Search Paths in Build Settings for pod "react-native-cameraroll"
> 
> Although this works, this needs to be done for every fresh "pod install".
> 
> RN Version: 0.60.4
> react-native-cameraroll Version: 4.0.4

have you found solution?

**Comment by Arkan4ik** [comment]
I`ve write some code which need to add in Podfile in ios folder. Need to paste it inside post_install. 

```
work_dir = Dir.pwd
  camerarol_xcconfig_filename = ["#{work_dir}/Pods/Target Support Files/react-native-cameraroll/react-native-cameraroll.debug.xcconfig", "#{work_dir}/Pods/Target Support Files/react-native-cameraroll/react-native-cameraroll.release.xcconfig"]
  change_header_search_for_cameraroll(camerarol_xcconfig_filename)

def change_header_search_for_cameraroll(arr)
  ##  START Fix error with cameraroll package. Need recheck after upgrading RN version
  ##  https://github.com/react-native-cameraroll/react-native-cameraroll/issues/284

  arr.each do |file_path|
    lines = IO.readlines(file_path).map do |line|
      if line =~ /HEADER_SEARCH_PATHS/
        line += "\"${PODS_ROOT}/Headers/Public/React-RCTNetwork\""
      else
        line
      end
    end
    
    File.open(file_path, 'w') do |file|
      file.puts lines
    end
  end
    
  ##  FINISH Fix error with cameraroll package. Need recheck after upgrading RN version
end
```

screenshots:
![image](https://user-images.githubusercontent.com/23438777/132130388-40b1fe60-559c-4800-8e56-28c7864dbfce.png)
![image](https://user-images.githubusercontent.com/23438777/132130395-2ae1a109-4384-4a2b-ab98-9e21cefa28d7.png)

**Comment by ASWAN123** [comment]
i am  cooked
