### ISSUE TITLE
Expose PHPickerViewController 

### ISSUE THREAD

**Issue by MarcoScabbiolo** [react-native-cameraroll/react-native-cameraroll#288]
It should be [fairly easy](https://developer.apple.com/documentation/photokit/selecting_photos_and_videos_in_ios?language=objc) to expose an implementation of [PHPickerViewController](https://developer.apple.com/documentation/photokit/phpickerviewcontroller?language=objc) to the JS side.

It implements all of the permission variants (specific/all photos) and there is no need to request a permission to read. [More here](https://developer.apple.com/documentation/photokit/delivering_a_great_privacy_experience_in_your_photos_app?language=objc)

Android doesn't have such a straight forward native ui implementation of the camera roll, querying and calling an intent seems to be the closest thing.

**Comment by ghostknow** [comment]
any update with this feature, thank you :)
