### ISSUE TITLE
Load 20 images per time will lost some images in version 4.0.2

### ISSUE THREAD

**Issue by huynhhq** [react-native-cameraroll/react-native-cameraroll#289]
Hi everyone, I am using CameraRoll to implement the image Gallery and there is a bug.
let photos = CameraRoll.getPhotos({
                    first: 20,
                    groupTypes: 'Album',
                    assetType: 'Photos',
                    after: this.end_cursor ? this.end_cursor : undefined,
                });
It will always miss some images in Gallery.

**Comment by leena-sharma** [comment]
@huynhhq  i am facing the issue in ios. Have you found the solution?

**Comment by one-god** [comment]
i am facing the issue in ios and android
