### ISSUE TITLE
CameraRoll.save doesn't save on ios 14

### ISSUE THREAD

**Issue by JCalds** [react-native-cameraroll/react-native-cameraroll#292]
I'm facing a problem when using ios 14. 

When I'm trying to save an image using CameraRoll.save() , I'm getting this system popup (which I think isn't the correct one), and consequently, the image is not saved.

![image](https://user-images.githubusercontent.com/79947676/109732854-d5ba8580-7bb5-11eb-85ec-34e78e16a460.png)

In the other iOS versions, the saving process works fine, and I'm getting the correct writeable system popup

Both of the request permissions are needed in diferent contexts NSPhotoLibraryAddUsageDescription, NSPhotoLibraryUsageDescription

Any clue?
Thanks.

**Comment by JanKaifer** [comment]
We don't use `read` access we use only `save`. So we fixed the library here: https://github.com/JanKaifer/react-native-cameraroll

It has probably broken permissions for reading. If someone is interested it should be quite easy to port fix it for reading and writing.

**Comment by mhammerc** [comment]
I have the same problem. On the latest iOS I can't save any image to the cameraroll.

To fix this, with inspiration from @JanKaifer answer and his commit, here is a patch:

```diff
diff --git a/node_modules/@react-native-community/cameraroll/ios/RNCCameraRollManager.m b/node_modules/@react-native-community/cameraroll/ios/RNCCameraRollManager.m
index 4bd76c0..e08e4a1 100644
--- a/node_modules/@react-native-community/cameraroll/ios/RNCCameraRollManager.m
+++ b/node_modules/@react-native-community/cameraroll/ios/RNCCameraRollManager.m
@@ -101,7 +101,7 @@ @implementation RNCCameraRollManager
 static void requestPhotoLibraryAccess(RCTPromiseRejectBlock reject, PhotosAuthorizedBlock authorizedBlock) {
   PHAuthorizationStatus authStatus;
   if (@available(iOS 14, *)) {
-    authStatus = [PHPhotoLibrary authorizationStatusForAccessLevel:PHAccessLevelReadWrite];
+    authStatus = [PHPhotoLibrary authorizationStatusForAccessLevel:PHAccessLevelAddOnly];
   } else {
     authStatus = [PHPhotoLibrary authorizationStatus];
   }
@@ -116,7 +116,7 @@ static void requestPhotoLibraryAccess(RCTPromiseRejectBlock reject, PhotosAuthor
     authorizedBlock(true);
   } else if (authStatus == PHAuthorizationStatusNotDetermined) {
       if (@available(iOS 14, *)) {
-          [PHPhotoLibrary requestAuthorizationForAccessLevel:PHAccessLevelReadWrite handler:^(PHAuthorizationStatus status) {
+          [PHPhotoLibrary requestAuthorizationForAccessLevel:PHAccessLevelAddOnly handler:^(PHAuthorizationStatus status) {
               requestPhotoLibraryAccess(reject, authorizedBlock);
           }];
       } else {
```

**This patch probably break reading the gallery** but works for us as we only need to save.

**Comment by ntcong91** [comment]
+1: Please don't request usage permission, only add permission for iOS.
