### ISSUE TITLE
is this being maintained anymore?

### ISSUE THREAD

**Issue by billnbell** [react-native-cameraroll/react-native-cameraroll#293]
There are so many PRs and so many Issues.

who is maintaining this? Maybe it should go back to core?

**Comment by MarcoScabbiolo** [comment]
It is being maintained, recently [some contributors were added](https://github.com/react-native-cameraroll/react-native-cameraroll/issues/242). This wont go back to the main `react-native` repo, and the current code is sustainable and well written, we just need more active contributors and maintainers. Personally I've been taken care of a big overhaul of `react-native-camera` so I couldn't help here as much as i would have liked to, but will do when I have the time.

I understand the repo currently gives the sensation of being abandoned, I've felt that myself on [a PR](https://github.com/react-native-cameraroll/react-native-cameraroll/pull/278), but the only way forward is for all those who can to contribute actively. AFAIK there is no alternative package and this one is well written, it just needs to catch up to iOS and Android latest releases and a cleanup of issues/PRs.

**Comment by lukebrandonfarrell** [comment]
@MarcoScabbiolo I'd be willing to help maintain this if you could get me access, thanks

**Comment by MarcoScabbiolo** [comment]
> @MarcoScabbiolo I'd be willing to help maintain this if you could get me access, thanks

Thanks! Feel free to post PRs or review existing issues/PRs. Mention me if you need anything.

**Comment by lukebrandonfarrell** [comment]
@bartolkaruza Appreciate it! Excited to help out on this repo :)

**Comment by Arjan-Zuidema** [comment]
Still no one active on this repo?

**Comment by Arjan-Zuidema** [comment]
If more maintainers are needed I am willing to help

**Comment by idrissakhi** [comment]
Willing to help too if you need maintainers ....

**Comment by idrissakhi** [comment]
And we really need to clean the board

**Comment by bartolkaruza** [comment]
I've invited @idrissakhi and @Arjan-Zuidema as maintainers. Thank you for the help guys. Reach out to me on Twitter dm if you need help with anything.

**Comment by idrissakhi** [comment]
New releases are coming soon, stay tuned.
