### ISSUE TITLE
[ Android ] @react-native-community_cameraroll:compileDebugJavaWithJavac FAILED

### ISSUE THREAD

**Issue by ahmedrowaihi** [react-native-cameraroll/react-native-cameraroll#295]
> Task :@react-native-community_cameraroll:compileDebugJavaWithJavac FAILED

Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/6.5/userguide/command_line_interface.html#sec:command_line_warnings
8 actionable tasks: 1 executed, 7 up-to-date

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':@react-native-community_cameraroll:compileDebugJavaWithJavac'.
> Could not create service of type DefaultUserHomeScopedCompileCaches using UserHomeScopeServices.createCompileCaches().
   > Unexpected lock protocol found in lock file. Expected 3, found 0.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 7s

error Failed to install the app. Make sure you have the Android development environment set up: https://reactnative.dev/docs/environment-setup. Run CLI with --verbose flag for more details.
Error: Command failed: gradlew.bat app:installDebug -PreactNativeDevServerPort=8081

**Comment by ahmedrowaihi** [comment]
I guess this problem comes with not just this package, please guys I need a solution for this :(

**Comment by Aliakwe** [comment]
I am facing thesame problem any solutions for this yet??

**Comment by EdmundMai** [comment]
@ahmedrowaihi Did you ever find out the solution?

**Comment by Aliakwe** [comment]
No I didnt

From: Edmund ***@***.***>
Reply to: react-native-cameraroll/react-native-cameraroll ***@***.***>
Date: Saturday, 22 May 2021 at 20:37
To: react-native-cameraroll/react-native-cameraroll ***@***.***>
Cc: Emmanuel Ogie ***@***.***>, Comment ***@***.***>
Subject: Re: [react-native-cameraroll/react-native-cameraroll] [ Android ] @react-native-community_cameraroll:compileDebugJavaWithJavac FAILED (#295)


@ahmedrowaihi<https://github.com/ahmedrowaihi> Did you ever find out the solution?

**Comment by ChenhuaWANG22** [comment]
I got an error like this and solved. check below, hope this will help.

https://github.com/react-native-cameraroll/react-native-cameraroll/issues/389#issuecomment-1196295499
