### ISSUE TITLE
Couldn't resolve fbjs

### ISSUE THREAD

**Issue by resting** [react-native-cameraroll/react-native-cameraroll#300]
Getting the below error:
> node_modules/@react-native-community/cameraroll/js/CameraRoll.js: fbjs/lib/invariant could not be found within the project or in these directories

On version: 4.0.4
RN 0.64.0

Installing fbjs separately resolves the issue, but this should be documented or included within the package.

**Comment by sanduluca** [comment]
Any new on this ? I have same issue and had no idea that I should install `fbjs` as well. Can this be added as a dependency or at least added to readme ?

**Comment by markw13a** [comment]
I ran in to this today when installing react-native-cameraroll on a new react-native app. Installing fbjs has resolved this issue for me too.
