### ISSUE TITLE
About requestLegacyExternalStorage

### ISSUE THREAD

**Issue by kperreau** [react-native-cameraroll/react-native-cameraroll#304]
Hello.
I just received this message from Play Store.

> Starting May 5th, you must let us know why your app requires broad storage access
> BeReal - Photos & Friends, no filter. BeReal - Photos & Friends, no filter.
> 14 avr. 2021 19:26
> 
> We've detected that your app contains the requestLegacyExternalStorage flag in the manifest file of 1 or more of your app bundles or APKs.
> 
> Developers with apps on devices running Android 11+ must use Scoped Storage to give users better access control over their device storage. To release your app on Android 11 or newer after May 5th, you must either:
> 
>     Update your app to use more privacy friendly best practices, such as the Storage Access Framework or Media Store API
>     Update your app to declare the All files access (MANAGE_EXTERNAL_STORAGE) permission in the manifest file, and complete the All files access permission declaration in Play Console from May 5th
>     Remove the All files access permission from your app entirely
> 
> For apps targeting Android 11, the requestLegacyExternalStorage flag will be ignored. You must use the All files access permission to retain broad access.
> 
> Apps requesting access to the All files access permission without a permitted use will be removed from Google Play, and you won't be able to publish updates.

Any info to solve this?
Why not simply use the Storage Access Framework?

Thanks for your answers.

**Comment by huurray** [comment]
same to me. i'm using android:requestLegacyExternalStorage="true".
should i do somthing because of changed policy?

**Comment by goguda** [comment]
> same to me. i'm using android:requestLegacyExternalStorage="true".
> should i do somthing because of changed policy?

Essentially, we have two options, according to Google:

> Update your app to declare the All files access (MANAGE_EXTERNAL_STORAGE) permission in the manifest file, and complete the All files access permission declaration in Play

which will probably be frowned upon from a privacy standpoint by both Google and clients unless absolutely needed, and I can imagine Google will deny requests where they don't deem it necessary to use either (i.e. in the case of only accessing photos and videos).

The other option is that this library needs to be updated in advance before May 5th to allow developers using it time to update our apps to be compatible with Android 11+.

Aka implementing Scoped Storage Support needs to be done in the next 2 weeks if we want this library to remain compatible with Android 11+.

**Comment by abeyuya** [comment]
Does anyone know if there are any plans to do `implementing Scoped Storage Support` ?

**Comment by dvquoc** [comment]
I have the same problem. Is there any solution to fix it?

**Comment by HugoGresse** [comment]
Based on the VERY short timeline here, I'm posted a solution on [SO](https://stackoverflow.com/questions/67179409/alternative-for-mediascanner-scanfile-cameraroll-on-android-29-q/67179410#67179410)

So it's working well on my side using the MediaStore API (not very intuitive API though) and the `react-native-fs` package for scanning the file. 
It can probably be adapted to CameraRoll and I'll be happy to submit a PR if the maintainers are ok with the solution.

**Comment by dvquoc** [comment]
> Based on the VERY short timeline here, I've posted a solution on [SO](https://stackoverflow.com/questions/67179409/alternative-for-mediascanner-scanfile-cameraroll-on-android-29-q/67179410#67179410)
> 
> So it's working well on my side using the MediaStore API (not very intuitive API though) and the `react-native-fs` package for scanning the file.
> It can probably be adapted to CameraRoll and I'll be happy to submit a PR if the maintainers are ok with the solution.
How to export this problem. It is very serious!

**Comment by kenMarquez** [comment]
Regarding your solution @HugoGresse, what do you think? If we keep the logic inside the save method, this way the implementers won't have to do anything, just update the library. I based on your proposal and now I am working without him
requestLegacyExternalStorage and it works 🎉

----

If you are looking for a quick way to fix this while the library owners adjust it, you can do this

1- Remove from you android manifest.xml file the property:
`android: requestLegacyExternalStorage = "true"`

2- Make sure you have the following version of react-native-cameraroll in your package.json
`"@react-native-community/cameraroll": "4.0.4",`

3- Execute:
`yarn add -d patch-package`

4. In the root directoy from your project at the same herarchy of your node_modules create a new folder called `patches` and paste this file inside 
https://drive.google.com/file/d/16ar65Z8zw_eRwN1LqFUSHoc2rkl9nWcP/view?usp=sharing


5. Install your dependencies again to override add the logic to work without the `requestLegacyExternalStorage`
`yarn install`

In the terminal you will see something like this
![image](https://user-images.githubusercontent.com/10731555/115618245-0d8da180-a2b8-11eb-9500-2c50c51bb9fe.png)

**Comment by HugoGresse** [comment]
LGTM, will have done a PR rather than a patch though... 
The fileName should also be extracted from the path too, to keep the same signature method.

**Comment by kenMarquez** [comment]
Great recommendations @HugoGresse, i updated the patch
https://drive.google.com/file/d/1tHDpoDSLsP7ntt0fJSEjdaYVKEaG3_Uc/view?usp=sharing

1. Good catch i remove the fileName from the param and now its taken from the path
2. I remove the react-native-fs dependecy and i added the MediaScannerConnection directly from the native side

Hopefully the owner says if he agrees we can work on a PR thank you very much @HugoGresse

**Comment by kursonix** [comment]
@kenMarquez i use your patch and solution. I deleted requestLegacyStorage and was able to save Photo to the Pictures directory on my Phone. But there is a problem with getting this Photo using uri returned from save mrthod. The Photo not appear <Image source={{uri:path}} />. I think that that it is a second problem. How to retrieve Photo using scope storage?

**Comment by anatolysamoilenko** [comment]
@HugoGresse's solution work only for images( 
What about videos?

**Comment by HugoGresse** [comment]
> @HugoGresse's solution work only for images(
> What about videos?

You need to look into MediaStore API for video but it shouldn't be much different, maybe just replace `MediaStore.Images.` by `MediaStore.Videos` or something like this, and the same for the `EXTERNAL_CONTENT_URI`

**Comment by kenMarquez** [comment]
Hello @kursonix , how are you calling the save method? , did you called with await syntax?
something like this:
```
const image = await CameraRoll.save(imagePath, {
  album: ALBUM_NAME,
});
console.log('image', image);
```

**Comment by kursonix** [comment]
@kenMarquez hi yes I use it like this. With requestLegacy flag it works

`public savePhoto = async (imagePath: string): Promise<string | undefined> => {
    if (Platform.OS === 'android' && !(await hasAndroidPermission())) {
      return;
    }
    const newPath = await CameraRoll.save(imagePath, {
      album: 'puzzleTracker',
    });
    return getOrginalPath(newPath);
  };`

**Comment by HugoGresse** [comment]
@bartolkaruza @Naturalclar would you mind taking a look at the proposed solution to fix this and let us know if you are somewhat ok so we can start the PR?

**Comment by Naturalclar** [comment]
@HugoGresse thanks for taking up the issue, the proposed solution sounds fine to me, would you be able to start the PR?

**Comment by HugoGresse** [comment]
I'll work on the PR tomorrow. 
In the meantime, I needed tochange the method to get the file path from the final MediaStore URI for some reason... here is the latest one I used: 
```
    // From https://stackoverflow.com/a/64359655/1377145
    public static String getNameFromContentUri(Context context, Uri contentUri){
        ContentResolver contentResolver = context.getContentResolver();
        Cursor cursor = contentResolver.query(contentUri, null, null, null, null);
        cursor.moveToFirst();
        String document_id = cursor.getString(0);
        document_id = document_id.substring(document_id.lastIndexOf(":") + 1);
        cursor.close();

        cursor = contentResolver.query(
            android.provider.MediaStore.Images.Media.EXTERNAL_CONTENT_URI,
            null, MediaStore.Images.Media._ID + " = ? ", new String[]{document_id}, null);
        cursor.moveToFirst();
        String path = cursor.getString(cursor.getColumnIndex(MediaStore.Images.Media.DATA));
        cursor.close();
        return path;
    }
```

**Comment by billnbell** [comment]
Also on Samsung Galaxy A21 running Android 10, we get a list of images, but cannot show them on the device.

**Comment by HugoGresse** [comment]
First draft: https://github.com/react-native-cameraroll/react-native-cameraroll/pull/307

**Comment by lucaspang** [comment]
@HugoGresse Hello, I have applied your changes and removed requestLegacyExternalStorage. But I can no longer get photos in download folder in Android 10, is it save to keep requestLegacyExternalStorage as Android 11 will ignore it? Thank you.

**Comment by kursonix** [comment]
@lucaspang  Hi. Right now the option with requestLegacyExternalStorage will work if you target api level 29. For exising app in app store it is still valid until November. After that to update app you must use api level 30. For new apps in app store you must target api level 29. Can someone confirm that is true? I will not have problem after 5 May if i still use api level 29 with this flag

**Comment by HugoGresse** [comment]
> @lucaspang Hi. Right now the option with requestLegacyExternalStorage will work if you target api level 29(Android 10). For exising app in app store it is still valid until November. After that to update app you must use api level 30. For new apps in app store you must target api level 30. Can someone confirm that is true? I will not have problem after 5 May if i still use api level 29 with this flag

If that's the case, this gave us some time to finish the PR. In any case, I'll test in production the first solution I posted in SO starting next week on 10k users and keep you posted.

**Comment by pabloearg** [comment]
> @lucaspang Hi. Right now the option with requestLegacyExternalStorage will work if you target api level 29(Android 10). For exising app in app store it is still valid until November. After that to update app you must use api level 30. For new apps in app store you must target api level 30. Can someone confirm that is true? I will not have problem after 5 May if i still use api level 29 with this flag

I understood the same as you, but the google warning in the console does not specify anything about whether it is for 30 or 29, it would be great if someone can confirm this with some documentation

**Comment by kursonix** [comment]
@HugoGresse @pabloearg there is a thread about it on reddit https://www.reddit.com/r/androiddev/comments/mwaqn1/scoped_storage_recap/ and the answer from google tem member
"This Google Play policy refers specifically to apps that target API level 30 and need the MANAGE_EXTERNAL_STORAGE permission (All Files Access). If you don’t use or plan to use this permission, this policy shouldn’t affect you. If you are currently targeting API level 29 and want to use this permission when you update to target API level 30, you will need to comply with this policy."

**Comment by dokkis** [comment]
can somebody look also at my research posted in here and do some double checks? https://github.com/status-im/status-react/issues/12063

**Comment by pabloearg** [comment]
I just contact google support and this was their answer

![Screen Shot 2021-04-29 at 17 14 15](https://user-images.githubusercontent.com/29818262/116760186-a758fb00-a9ea-11eb-8510-a77cfc8a2567.png)
![Screen Shot 2021-04-29 at 17 19 00](https://user-images.githubusercontent.com/29818262/116760193-ad4edc00-a9ea-11eb-852c-6ccf604d19ff.png)

so as long as you point to api 29, nothing should happen

**Comment by MadCoderme** [comment]
So we can wait for complete update in this library until November with Api 29, right?

**Comment by kunalyelne** [comment]
@kenMarquez @kursonix I used the patch but the retrieved images are not visible, I tried
<Image 
source={{
    uri: x.node.image.uri, //uri
  }}>
  it works when legacy storage flag is true.
  
  Any idea why is this issue happening?

**Comment by MadCoderme** [comment]
> @kenMarquez @kursonix I used the patch but the retrieved images are not visible, I tried
> 
> ```
> <Image 
> source={{
>     uri: x.node.image.uri, //uri
>   }}>
> ```
> 
> it works when legacy storage flag is true.
> 
> Any idea why is this issue happening?

@kunalyelne This is probably because the patch only contains updated code for saving file, not for fetching files

**Comment by kenMarquez** [comment]
@kunalyelne Are you still with the problem?

Could you validate if the path you are receiving in the `file://`  format ?

**Comment by kunalyelne** [comment]
@kenMarquez Yeah still facing the problem. Also, I did check the uri and it is correct. It begins with `file:///`. Do we have to access the file using Media Store APIs on Native side or something?

**Comment by kenMarquez** [comment]
Could you modify the patch on this line and change this `file:///` to `file://` and try again 

![image](https://user-images.githubusercontent.com/10731555/117349234-c6371180-ae70-11eb-8b43-a5f987ed4610.png)

**Comment by iamvucms** [comment]
> @kenMarquez @kursonix I used the patch but the retrieved images are not visible, I tried
> 
> ```
> <Image 
> source={{
>     uri: x.node.image.uri, //uri
>   }}>
> ```
> 
> it works when legacy storage flag is true.
> 
> Any idea why is this issue happening?

Same

**Comment by kunalyelne** [comment]
> A better attempt might be to test directly from the pull request made for @HugoGresse and don't forget remove the patch file
> 
> `yarn add https://github.com/HugoGresse/react-native-cameraroll.git#304-scopedStorage`

Nope, problem still persist. @kenMarquez

**Comment by MadCoderme** [comment]
This weird issue happened to me even using main package. Images are visible in one file and not visible in other file even though they are in same project and same code.
I think, you can try creating a new fresh project

**Comment by HugoGresse** [comment]
Following my PR, I've released PlantNet app to 5% of the users for a few days resulting in no issue reported on this subject after 7 days (~500k users / day). I've increased the release to 50%, will update you next week.

**Comment by iamvucms** [comment]
Are you keeping requestLegacyExternalStorage on android 10 ? In my side, images from camera roll aren't able to show in FastImage & Image component if use your PR and remove requestLegacyExternalStorage on android 10

**Comment by HugoGresse** [comment]
I'm using the PR for android 10 and +, and fallback to cameraroll current state for below. 
To be fair, I'm not using the exacte PR as I've released the app before making the pr here, so it's using thoses exacte methods only for Q+: 

```js
            if (isAndroidQAndAbove) {
                // Google ask that the requestLegacyExternalStorage is no longer used when targeting android 11, and use
                // the scoped storage or the new global permission, see https://gitlab.inria.fr/floristic/pn-mobile-test/-/issues/417
                // Solution here, custom module which use the MediaStore API and copy the file to the DCIM folders.
                const segments = path.split('/')
                const fileName = segments[segments.length - 1]

                const fileUriPath = await Module.moveToMediaStore(path.replace('file://', ''), fileName)
                if (!fileUriPath) {
                    return null
                }
                await RNFS.scanFile(fileUriPath)
                if (fileUriPath.startsWith('file:///')) {
                    return fileUriPath
                }
                return `file://${fileUriPath}`
            }
```

```
    @ReactMethod
    public void moveToMediaStore(String filePath, String fileName, Promise promise) {
        if (Build.VERSION.SDK_INT < Build.VERSION_CODES.Q) {
            promise.resolve(null);
            return;
        }
        ContentValues values = new ContentValues();
        values.put(MediaStore.Images.Media.DISPLAY_NAME, fileName);
        values.put(MediaStore.Images.Media.MIME_TYPE, "image/jpeg");

        values.put(MediaStore.MediaColumns.RELATIVE_PATH, Environment.DIRECTORY_DCIM + "/PlantNet");
        values.put(MediaStore.MediaColumns.IS_PENDING, 1);

        ContentResolver resolver = getReactApplicationContext().getContentResolver();
        Uri imageUri = resolver.insert(MediaStore.Images.Media.EXTERNAL_CONTENT_URI, values);

        try {
            OutputStream fos = resolver.openOutputStream(imageUri);
            copy(new File(filePath), fos);
            values.clear();
            values.put(MediaStore.Images.Media.IS_PENDING, 0);
            resolver.update(imageUri, values, null, null);
            promise.resolve(getNameFromContentUri(getReactApplicationContext(), imageUri));
        } catch (Exception e) {
            e.printStackTrace();
            promise.reject(e);
        }
    }

    @RequiresApi(api = Build.VERSION_CODES.Q)
    public static void copy(File src, OutputStream out) throws IOException {
        try (InputStream in = new FileInputStream(src)) {
            FileUtils.copy(in, out);
        }
    }

    // From https://stackoverflow.com/a/64359655/1377145
    public static String getNameFromContentUri(Context context, Uri contentUri){
        ContentResolver contentResolver = context.getContentResolver();
        Cursor cursor = contentResolver.query(contentUri, null, null, null, null);
        cursor.moveToFirst();
        String document_id = cursor.getString(0);
        document_id = document_id.substring(document_id.lastIndexOf(":") + 1);
        cursor.close();

        cursor = contentResolver.query(
            android.provider.MediaStore.Images.Media.EXTERNAL_CONTENT_URI,
            null, MediaStore.Images.Media._ID + " = ? ", new String[]{document_id}, null);
        cursor.moveToFirst();
        String path = cursor.getString(cursor.getColumnIndex(MediaStore.Images.Media.DATA));
        cursor.close();
        return path;
    }
    ```

**Comment by ShubhankSG** [comment]
Can verify app update has been approved with target sdk 29 and with the flag `requestLegacyExternalStorage` in place.
Will be waiting for the next release that solves the scoped storage on sdk 30

**Comment by LuongTruong** [comment]
Hello guys, is this issue still be considering?

**Comment by har2008preet** [comment]
Hi,
We are getting this error: https://stackoverflow.com/questions/68207334/getting-error-while-running-react-native-run-andorid-in-react-native and the solution to that is to upgrade to version 30.

**Comment by MadCoderme** [comment]
Any Update on this topic?

According to @HugoGresse 's proposed PR, is it working with both `getPhotos()`  and `save()` function?
I will be updating my production app soon.

**Comment by HugoGresse** [comment]
Following changes made in my [last comment](https://github.com/react-native-cameraroll/react-native-cameraroll/issues/304#issuecomment-842383234), PlantNet app is doing great, already have 4M users in July with no complaint for this part. I cannot guaranty this is without any risk though.

**Comment by tomgransden** [comment]
Do we have any confirmation from the maintainers/contributors that someone is working to get this library updated for both reading images and saving images?

**Comment by MadCoderme** [comment]
> Do we have any confirmation from the maintainers/contributors that someone is working to get this library updated for both reading images and saving images?

I have not noticed any and that's pathetic

**Comment by MadCoderme** [comment]
Only a few days remaining. Is there any plan to make it supported for both reading and saving images in the official library?

**Comment by marcshilling** [comment]
I've set `targetSdkVersion = 30` and interestingly `CameraRoll.save()` seems to be working for me on an Android 11 device with no changes. However, on an Android 10 device it only seems to work with `android:requestLegacyExternalStorage="true"` still specified in my manifest. If I remove that, I get a permission denied error. I guess no harm leaving that. Is this expected? I'm not using getPhotos(), so I can't speak to the impact there.

**Comment by apgsn** [comment]
Any news on this?

**Comment by MadCoderme** [comment]
An interesting thing is, this library worked as usual for me without `android:requestLegacyExternalStorage="true"` 

I set target SDK version 31. Tested on Android 11 and Android 9. The update is already released in play store. My app don't have much users but still No crash log so far.

**Comment by PaperMonster** [comment]
In my case, `targetSdkVersion = 30` without `android:requestLegacyExternalStorage="true"` works on Android 11, but not Android 10. On Android 10, even with `WRITE_EXTERNAL_STORAGE` permission granted, it still shows permission denied error. I'm using [this native module](https://stackoverflow.com/a/67179410) for Android 10 and higher for the time being.

**Comment by demedos** [comment]
Here's a temporary solution, in case anybody needs it

```
import RNFS from 'react-native-fs';

const getFileNameFromPath = (path: string) => {
  return path.slice(path.lastIndexOf('/') + 1);
};

if (Platform.OS === 'android') {
  RNFS.moveFile(filePath, `${RNFS.PicturesDirectoryPath}/${getFileNameFromPath(filePath)}`);
} else {
  CameraRoll.save(filePath).then(() => RNFS.unlink(filePath));
}


```
