### ISSUE TITLE
Error saving 4K videos in portrait mode to cameral roll on iOS

### ISSUE THREAD

**Issue by douglasgondim** [react-native-cameraroll/react-native-cameraroll#318]
Error saving to Camera Roll: The operation couldn't be completed. (PHPhotosErrorDomain error -1.))

**Comment by bohdan145** [comment]
Have the same issue,
Did u find any solution ?

**Comment by scgough** [comment]
Hi! Check out my comment here https://github.com/react-native-cameraroll/react-native-cameraroll/issues/186#issuecomment-898357526
