### ISSUE TITLE
[Android] `getPhotos()` doesn't behave correctly on Android 11

### ISSUE THREAD

**Issue by isotopeee** [react-native-cameraroll/react-native-cameraroll#320]
`getPhotos()` is not working correctly on Android 11.

1. It only fetches the first (n) images where n = `first: (n)` and use it on subsequent `CameraRoll.getPhotos()` calls.
2. I can also scroll endlessly, instead of being limited to the number of photos that I have in the camera roll. I only have 55+ photos in the camera roll.

I've tested the issue on Android 9 and Android 10 and it's working fine. I'm using the latest version of `@react-native-community/cameraroll`. I've have 55+ photos in the camera roll.

In the screenshot below, first = 12

```
CameraRoll.getPhotos({ first: 12 });
```

![Screenshot_1624258477](https://user-images.githubusercontent.com/17417116/122721216-f9a7f100-d2a2-11eb-91b0-b674cf142aab.png)

I suspect this issue is related to #244, #304, and #253.

**Comment by webthesoul** [comment]
same here. Android 11. 
seems  `after`  doesn't work

**Comment by douglasjunior** [comment]
Same here, unfortunately the repository is abandoned, and it looks like we don't have another alternative at the moment. 😢

**Comment by Cygnus2112** [comment]
I've encountered this as well. Are there any viable workarounds that anyone has found?

**Comment by Oz-on** [comment]
Hi, the problem is caused by this line of code:

```
        // set LIMIT to first + 1 so that we know how to populate page_info
        String limit = "limit=" + (mFirst + 1);

        if (!TextUtils.isEmpty(mAfter)) {
          limit = "limit=" + mAfter + "," + (mFirst + 1);
        }

        Cursor media = resolver.query(
            MediaStore.Files.getContentUri("external").buildUpon().encodedQuery(limit).build(),
            PROJECTION,
            selection.toString(),
            selectionArgs.toArray(new String[selectionArgs.size()]),
            Images.Media.DATE_ADDED + " DESC, " + Images.Media.DATE_MODIFIED + " DESC");
```

In Android 11, `limit` is not working. In order to solve this issue, I recommend adding limitations not in the query but in the place when images are being added to the response.

**Comment by hsnGh67** [comment]
this bug not fixed in new version (4.1.1). please fix it asap.

**Comment by NhatGinnovations** [comment]
I try to get all the photos on Android 11 and the new ones are added back at the bottom of the list. Can you tell me the cause and how to solve it?

Note: It still works as expected on Android 10 by sorting.

**Comment by dungnguyentri3110** [comment]
> same here. Android 11. `getPhotos({first:24, after:24, assetType: 'Photos'})` response.page_info is ` {... , end_cursor: 48, has_next_page': true }`
> 
> response shows that `end_cursor` is increased, but `edges` (items) are same as `getPhotos({first:24, assetType: 'Photos'})`

i face same issue here. you guys have any solution? i use android 12

**Comment by douglasjunior** [comment]
> I've used `expo-media-library` library instead. I've replaced `getPhotos()` with `MediaLibrary.getAssetsAsync()` as a workaround.

I think that this is the way to go. Expo libraries tend to receive more updates and attention.

Today it is quite easy to [add Expo to a RN project](https://docs.expo.dev/bare/existing-apps/), making it possible to install any ["expo" library](https://docs.expo.dev/versions/latest/).
