### ISSUE TITLE
CameraRoll.save to album creating multiple albums

### ISSUE THREAD

**Issue by zuhairnaqi** [react-native-cameraroll/react-native-cameraroll#321]
save(uri, {type: 'photo', album: 'Project'})

creating multiple albums with the same name and having one image per album.

**Comment by donatoaguirre24** [comment]
Same here ✋🏻

**Comment by zuhairnaqi** [comment]
@bartolkaruza do you have any idea related to this?

**Comment by zuhairnaqi** [comment]
It's creating multiple albums because I was saving files in a loop without async-await.
