### ISSUE TITLE
Enhance getAlbums() to include thumbnails

### ISSUE THREAD

**Issue by freakyfriday** [react-native-cameraroll/react-native-cameraroll#325]
Suggestion: Enhance the getAlbums() method to return an array of Albums that include the album thumbnail image

**Comment by valentynberehovyi** [comment]
I also need this in my main project.
@freakyfriday, how do you think what structure of thumbnail should be here?
Will it be enough if thumbnail structure will be the same as `node` structure in `getPhotos` method's result?

**Comment by freakyfriday** [comment]
I'm not sure but this is how it was done in the react-native-camera-kit which has also deprecated the functionality in recent versions:

Android:
https://github.com/teslamotors/react-native-camera-kit/blob/cff3175aa176e664a89b7f19424ddb8ca0a1ed2d/android/src/main/java/com/wix/RNCameraKit/gallery/NativeGalleryModule.java#L171

IOS
https://github.com/teslamotors/react-native-camera-kit/blob/cff3175aa176e664a89b7f19424ddb8ca0a1ed2d/ios/lib/ReactNativeCameraKit/CKGalleryManager.m#L94

I'm not a Native dev so can't really help but was hoping someone else who needs this functionality could lend a hand incorporating thumbnails into the getAlbums() method

**Comment by abhaya-kumar-sahoo** [comment]
### it

> 

it is taking too much  time to call first image of each album .
