### ISSUE TITLE
Getting images URI but not showing in image view [iOS]

### ISSUE THREAD

**Issue by miteshkhatri** [react-native-cameraroll/react-native-cameraroll#333]
Hii..
im getting an error no images from uri in getphotos method. its not showing any. image but response seems good with uri and  names are proper. but only black images
 `CameraRoll.getPhotos({ first: 1000, assetType: 'All' }).then(
                (data) => {
                    const assets = data.edges;
                    let videoArray=[],photoArray=[];
                    assets.forEach((asset) => {
                        if(asset.node.type.includes("video")){
                            asset.node.image.mime = asset.node.type;
                            videoArray.push(asset.node.image);
                        }else{
                            asset.node.image.mime = asset.node.type;
                            photoArray.push(asset.node.image);
                        }
                    });
                    const filteredImages = videoArray.filter((item)=>item.uri.includes('.mp4'))
                    this.setState({videoArray:filteredImages,photoArray:photoArray})
                },
                (error) => {
                    //console.warn(error);
                }
            );`

**Comment by LozytskyiA** [comment]
The same

**Comment by iqqmuT** [comment]
I had the same problem. I received URIs but when trying to open them I got an error that the URI does not exist. Restarted the phone and then the issue was gone.

**Comment by valn1** [comment]
in my case, i was using FastImage to display them, switching it by Image works fine
