### ISSUE TITLE
Replace jcenter() with mavenCentral()

### ISSUE THREAD

**Issue by Romick2005** [react-native-cameraroll/react-native-cameraroll#340]
Can you please replace jcenter() with mavenCentral() (February 1st, 2022 JCenter will no longer be available for non-Artifactory clients).

https://github.com/react-native-cameraroll/react-native-cameraroll/blob/1421c1d7e4a384e3a37c42a4907738ae4fe9e399/android/build.gradle#L5
https://github.com/react-native-cameraroll/react-native-cameraroll/blob/1421c1d7e4a384e3a37c42a4907738ae4fe9e399/android/build.gradle#L35

http://developer.android.com/r/tools/jcenter-end-of-service

**Comment by zmtmaster** [comment]
Opened a Pull Request #373
