### ISSUE TITLE
Listen to Library Changes

### ISSUE THREAD

**Issue by jbromberg** [react-native-cameraroll/react-native-cameraroll#341]
Apple has an API for listening to changes in the Photo Library. It is called PHPhotoLibraryChangeObserver.

Documentation: https://developer.apple.com/documentation/photokit/phphotolibrarychangeobserver

This is an extremely useful tool and can unlock lots of capabilities for RN developers. It would be awesome if someone could help implement this as part of this package. I would be more than happy to, but unfortunately, I don't know any native code.

**Comment by idrissakhi** [comment]
here i have done the implementation of basic listener => 

the module I created will helps to invoke limited photo selection also for iOS 14

`
#import <AVFoundation/AVFoundation.h>
#import <React/RCTBridgeModule.h>
#import <React/RCTEventEmitter.h>
#import <Photos/Photos.h>

typedef enum {
  RNPermissionStatusNotDetermined = 0,
  RNPermissionStatusRestricted = 1,
  RNPermissionStatusDenied = 2,
  RNPermissionStatusAuthorized = 3,
  RNPermissionStatusLimited = 4,
} RNPermissionStatus;

@interface PhotoLibraryPermissionModule : RCTEventEmitter <RCTBridgeModule, PHPhotoLibraryChangeObserver>

@end

#import "PhotoLibraryPermissionModule.h"
#import <React/RCTUtils.h>

@import Photos;
@import PhotosUI;

@implementation PhotoLibraryPermissionModule

{
  bool hasListeners;
}

// Will be called when this module's first listener is added.
-(void)startObserving {
  hasListeners = YES;
  [[PHPhotoLibrary sharedPhotoLibrary] registerChangeObserver:self];
}

// Will be called when this module's last listener is removed, or on dealloc.
-(void)stopObserving {
  hasListeners = NO;
  [[PHPhotoLibrary sharedPhotoLibrary] unregisterChangeObserver:self];
}

RCT_EXPORT_MODULE()

- (dispatch_queue_t)methodQueue
{
  return dispatch_get_main_queue();
}

- (NSArray<NSString *> *)supportedEvents {
    return @[@"onLibrarySelectionChange"];
}

- (NSString *)stringForStatus:(RNPermissionStatus)status {
  switch (status) {
    case RNPermissionStatusRestricted:
      return @"unavailable";
    case RNPermissionStatusNotDetermined:
      return @"not-determined";
    case RNPermissionStatusDenied:
      return @"denied";
    case RNPermissionStatusLimited:
      return @"limited";
    case RNPermissionStatusAuthorized:
      return @"granted";
  }
}

- (void)checkCameraRollPermission:(void (^ _Nonnull)(RNPermissionStatus))resolve
                   rejecter:(void (^ _Nonnull)(NSError * _Nonnull))reject {
  PHAuthorizationStatus status;

  if (@available(iOS 14.0, *)) {
    status = [PHPhotoLibrary authorizationStatusForAccessLevel:PHAccessLevelReadWrite];
  } else {
    status = [PHPhotoLibrary authorizationStatus];
  }

  switch (status) {
    case PHAuthorizationStatusNotDetermined:
      return resolve(RNPermissionStatusNotDetermined);
    case PHAuthorizationStatusRestricted:
      return resolve(RNPermissionStatusRestricted);
    case PHAuthorizationStatusDenied:
      return resolve(RNPermissionStatusDenied);
    case PHAuthorizationStatusLimited:
      return resolve(RNPermissionStatusLimited);
    case PHAuthorizationStatusAuthorized:
      return resolve(RNPermissionStatusAuthorized);
  }

}

- (void)requestCameraRollPermission:(void (^ _Nonnull)(RNPermissionStatus))resolve
                   rejecter:(void (^ _Nonnull)(NSError * _Nonnull))reject {
  if (@available(iOS 14.0, *)) {
    [PHPhotoLibrary requestAuthorizationForAccessLevel:PHAccessLevelReadWrite handler:^(__unused PHAuthorizationStatus status) {
      [self checkCameraRollPermission:resolve rejecter:reject];
    }];
  } else {
    [PHPhotoLibrary requestAuthorization:^(__unused PHAuthorizationStatus status) {
      [self checkCameraRollPermission:resolve rejecter:reject];
    }];
  }
}


- (void)refreshLimitedPhotoselection:(RCTPromiseResolveBlock _Nonnull)resolve
                                         rejecter:(RCTPromiseRejectBlock _Nonnull)reject {
  if (@available(iOS 14, *)) {
    if ([PHPhotoLibrary authorizationStatusForAccessLevel:PHAccessLevelReadWrite] != PHAuthorizationStatusLimited) {
      return reject(@"cannot_open_limited_picker", @"Photo library permission isn't limited", nil);
    }

    UIViewController *presentedViewController = RCTPresentedViewController();
    [[PHPhotoLibrary sharedPhotoLibrary] presentLimitedLibraryPickerFromViewController:presentedViewController];

    resolve(@(true));
  } else {
    reject(@"cannot_open_limited_picker", @"Available on iOS 14 or higher", nil);
  }
}

- (void)photoLibraryDidChange:(PHChange *)changeInstance
{
  if (hasListeners) {
    [self sendEventWithName:@"onLibrarySelectionChange" body:@{@"body": @"changes"}];
  }
}

RCT_EXPORT_METHOD(checkPermission:(RCTPromiseResolveBlock)resolve
                  reject:(RCTPromiseRejectBlock)reject) {

  [self checkCameraRollPermission:^(RNPermissionStatus status) {
    resolve([self stringForStatus:status]);
  } rejecter:^(NSError *error) {
    reject([NSString stringWithFormat:@"%ld", (long)error.code], error.localizedDescription, error);
  }];
}


RCT_EXPORT_METHOD(requestPermission:(RCTPromiseResolveBlock)resolve
                  reject:(RCTPromiseRejectBlock)reject) {

  [self requestCameraRollPermission:^(RNPermissionStatus status) {
    resolve([self stringForStatus:status]);
  } rejecter:^(NSError *error) {
    reject([NSString stringWithFormat:@"%ld", (long)error.code], error.localizedDescription, error);
  }];
}


RCT_REMAP_METHOD(refreshPhotoSelection,
                 refreshLimitedPhotoselectionWithResolver:(RCTPromiseResolveBlock)resolve
                 rejecter:(RCTPromiseRejectBlock)reject) {
  [self refreshLimitedPhotoselection:resolve rejecter:reject];
}

@end`

in JS side

`
import { NativeEventEmitter, NativeModules } from 'react-native';

import { PhotoLibraryAuthorizationStatus } from 'src/Shared/Constants';

export interface PhotoLibraryPermissionModuleType {
  checkPermission: () => Promise<PhotoLibraryAuthorizationStatus>;
  requestPermission: () => Promise<PhotoLibraryAuthorizationStatus>;
  refreshPhotoSelection: () => Promise<boolean>;
  addListener: (eventType: string) => void;
  removeListeners: (count: number) => void;
}

export const photoLibraryPermissionModule =
  NativeModules.PhotoLibraryPermissionModule as PhotoLibraryPermissionModuleType;

export const photoLibraryEventEmitter = new NativeEventEmitter(photoLibraryPermissionModule);

export const iosReadGalleryPermission = () => {
  return photoLibraryPermissionModule.checkPermission();
};

export const iosRequestGalleryPermission = () => {
  return photoLibraryPermissionModule.requestPermission();
};

export const refreshGallerySelection = () => {
  return photoLibraryPermissionModule.refreshPhotoSelection();
};

`

**Comment by cutenesss** [comment]
has this been approved?

**Comment by junguksim** [comment]
Any improvements on this??

**Comment by Arjan-Zuidema** [comment]
If you can make a pull request, I can have a look at it. Right now there is no-one working on this issue. Doing this in my spare time, so I don't have much time unfortunately.

**Comment by junguksim** [comment]
> If you can make a pull request, I can have a look at it. Right now there is no-one working on this issue. Doing this in my spare time, so I don't have much time unfortunately.

Thanks for your fast reply! I hope so.. I want this feature right now so instead I'm checking library after 1.5s I got new file ... So unreliable and inefficient now.
