### ISSUE TITLE
Could not find method compile() for arguments [project ':react-native-community_cameraroll']

### ISSUE THREAD

**Issue by SoonIter** [react-native-cameraroll/react-native-cameraroll#349]
I have two errors , one is fixed by myself.
![image-20211010133042571-3843843](https://user-images.githubusercontent.com/79413249/137537130-4184c1d0-3187-46b1-a7a7-947457a84c10.png)
I fixed it by changing its name to "RNC",then I successfully built it on Xcode.
![image-20211010133117949-3843879](https://user-images.githubusercontent.com/79413249/137537197-e2e8e685-7197-444a-a8f2-4aa1f68b6f15.png)
Today I try to build it on Android Studio.I got a lot of problems by this "cameraroll" .
![image](https://user-images.githubusercontent.com/79413249/137537576-d07529d0-2b40-497b-8509-6b679d1b1de9.png)

**Comment by a1730214056** [comment]
Oh sorry,I solved this problem by changing my JDK buildToolsVersion.But the first problem I don't know why it exists.

**Comment by IlyaSirosh** [comment]
Facing the same issue. Currently trying to setup build for android on mac m1
<img width="1100" alt="Screenshot 2021-11-28 at 22 45 19" src="https://user-images.githubusercontent.com/19352576/143785347-36ab6592-af24-419c-87ee-a12af92b29c4.png">

**Comment by SoonIter** [comment]
I replaced the "compile" with "implementation",I can run normally now.
