### ISSUE TITLE
Android - getPhotos() not returning any photos

### ISSUE THREAD

**Issue by princefishthrower** [react-native-cameraroll/react-native-cameraroll#351]
Another great day in the React Native world.

I can't get any photos to be retrieved - following the exact example in the readme, however with hooks:

```tsx
const [photos, setPhotos] = useState<PhotoIdentifier[]>([]);

  const handleButtonPress = () => {
    CameraRoll.getPhotos({
      first: 20,
      assetType: 'Photos',
    })
      .then(r => {
        setPhotos(r.edges);
      })
      .catch((err) => {
        //Error Loading Images
      });
  };
  // always 0
  console.log(photos.length)
  return (
    <View>
      <Button title="Load Images" onPress={handleButtonPress} />
      <ScrollView>
        {photos.map((p, i) => {
          return (
            <Image
              key={i}
              style={{
                width: 300,
                height: 100,
              }}
              source={{ uri: p.node.image.uri }}
            />
          );
        })}
      </ScrollView>
    </View>
  );
```

_Yes_ I have photos in my android emulator, in both the 'Downloads' and 'Pictures' folder

_Yes_ I have followed all detailed install instructions for android.

Any ideas about what is missing here? I'm already on React Native 0.66.0 - perhaps that has something to do with it?

UPDATE: I can confirm this is a simulator only issue - is there a place I should be putting my photos other than `data/media/0/Pictures` on my simulator?

**Comment by tomskopek** [comment]
@princefishthrower did you figure this out? What is the best way to add photos to the cameraroll on an Android emulator?
