### ISSUE TITLE
undefined Unable to resolve module fbjs/lib/invariant

### ISSUE THREAD

**Issue by septe01** [react-native-cameraroll/react-native-cameraroll#352]
when I'm use react-native-cameraroll

getting error :

ERROR  [Error: undefined Unable to resolve module fbjs/lib/invariant from /Users/septehabudin/Desktop/PROJECT/MOBILE/RN/pendekin/node_modules/@react-native-community/cameraroll/js/CameraRoll.js: fbjs/lib/invariant could not be found within the project or in these directories:
  node_modules

If you are sure the module exists, try these steps:
 1. Clear watchman watches: watchman watch-del-all
 2. Delete node_modules and run yarn install
 3. Reset Metro's cache: yarn start --reset-cache
 4. Remove the cache: rm -rf /tmp/metro-*
  12 | import RNCCameraRoll from './nativeInterface';
  13 |
> 14 | const invariant = require('fbjs/lib/invariant');

what do I have to do?
pleas help...

this my package.json 
  "dependencies": {
    "@hookform/resolvers": "^2.8.2",
    "@react-native-async-storage/async-storage": "^1.15.9",
    "@react-native-community/cameraroll": "^4.1.2",
    "@react-native-community/clipboard": "^1.5.1",
    "react": "17.0.2",
    "react-hook-form": "^7.17.5",
    "react-native": "0.66.1"
  },

**Comment by vfasky** [comment]
yarn add fbjs

**Comment by idrisssakhi** [comment]
please check this lib, it provides all same things => react-native-photo-gallery-api https://www.npmjs.com/package/react-native-photo-gallery-api

**Comment by santhoshvai** [comment]
this is fixed as of 5.0.0

**Comment by talaikis** [comment]
> this is fixed as of 5.0.0

Would be nice to have `5.0.0` on npm.
