### ISSUE TITLE
getAlbums() does not return anything

### ISSUE THREAD

**Issue by princefishthrower** [react-native-cameraroll/react-native-cameraroll#353]
Simulator or real phone, iOS or Android, `getAlbums()` returns nothing - also the typings are wrong, the parameter should be optional, in TypeScript, you have to pass an empty object `getAlbums({})` in order to prevent type complaints.

Doesn't really matter anyway I don't expect this issue to be answered.

**Comment by HuXin957** [comment]
so do I

**Comment by idrisssakhi** [comment]
I re-write the lib to propose new features and resolve most important opened issues → https://www.npmjs.com/package/react-native-photo-gallery-api
