### ISSUE TITLE
Check file exist then save image

### ISSUE THREAD

**Issue by zuhairnaqi** [react-native-cameraroll/react-native-cameraroll#358]
1. Is there any method we can check the remote URL image is exist or not?
2. Can we name the file we're saving in an album?
3. In which directory `CameraRoll.save` is saving the files?

**Comment by WenLonG12345** [comment]
I have the same question too. Anyone can help to answer this?

**Comment by YauhenDavidovich** [comment]
The same problem, any ideas?
