### ISSUE TITLE
CameraRoll.getPhotos with 'after' not working on Android sdk version 30

### ISSUE THREAD

**Issue by daiquangduy** [react-native-cameraroll/react-native-cameraroll#359]
CameraRoll.getPhotos with 'after' not working on Android sdk version 30
```javascript
const params = {
    first: 10,
    assetType: 'Photos'
}
if (endCursor) {
    params.after = endCursor;
}
const response = await CameraRoll.getPhotos(params);
```
It's always return 10 first photos

**Comment by HuzarO** [comment]
Same issue here, any solution? It seems that results from `getPhotos` also does not contain `start_cursor` property, only `has_next_page` and `end_cursor`.

**Comment by mickey-ichi** [comment]
I'm having this issue too. 
Anybody can help us with this?

**Comment by ilyabreev** [comment]
Same issue here

**Comment by ilyabreev** [comment]
> Same issue here, any solution? It seems that results from `getPhotos` also does not contain `start_cursor` property, only `has_next_page` and `end_cursor`.
> 
> === EDIT === Quick workaround is to change `targetSdkVersion` to `29` so it works properly.

It's not a workaround since Google's requirement for `targetSdkVersion` 30 for any updates or new apps.

**Comment by jaspermeijaard** [comment]
We had some issues with this as well on SDK 30. What seem to work: we moved the sorting of the query in to a bundle property `QUERY_ARG_SQL_SORT_ORDER ` which is passed along with the content resolver query. 

Example: 
```
Cursor media = null;
String[] selectionArgsArray = selectionArgs.toArray(new String[selectionArgs.size()]);
String selectionString = selection.toString();
String sortString = Images.Media.DATE_ADDED + " DESC, " + Images.Media.DATE_MODIFIED + " DESC";

if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.R) {
  Bundle selectionBundle = new Bundle();
  selectionBundle.putInt(ContentResolver.QUERY_ARG_LIMIT, mFirst + 1);
  selectionBundle.putInt(ContentResolver.QUERY_ARG_OFFSET, 0);
  selectionBundle.putString(ContentResolver.QUERY_ARG_SQL_SORT_ORDER, sortString);
  selectionBundle.putString(ContentResolver.QUERY_ARG_SQL_SELECTION, selectionString);
  selectionBundle.putStringArray(ContentResolver.QUERY_ARG_SQL_SELECTION_ARGS, selectionArgsArray);

  media = resolver.query(
    MediaStore.Files.getContentUri("external"),
    PROJECTION,
    selectionBundle,
    null
  );
} else {
  media = resolver.query(
    MediaStore.Files.getContentUri("external"),
    PROJECTION,
    selectionString,
    selectionArgsArray,
    sortString + " LIMIT " + (mFirst + 1)
  );
}
```

**Comment by VladlenKaveev** [comment]
@jaspermeijaard you have fork with this changes? Im not fully understand how to resolve it :(

**Comment by VladlenKaveev** [comment]
@jaspermeijaard you have fork with this changes? Im not fully understand how to resolve it :(

**Comment by VladlenKaveev** [comment]
@jaspermeijaard its work correctly only if i get photos from specific album. If i try to get "All" photos, they sorting randomly :(

**Comment by divyasri93** [comment]
I'm facing the same issue in Android 11 ... any updates on this issue!

**Comment by kneubuehl** [comment]
This is really high impact, need this resolved ASAP. @jaspermeijaard are you actively working on this?

**Comment by kesha-antonov** [comment]
Same issue

**Comment by BohdanSol** [comment]
As a quick solution try installing [my fork](https://github.com/BohdanSol/react-native-cameraroll) which does resolve issue on sdk 30 pagination for my purposes. I'm not sure about sorting, I do use only newest to oldest one, which also works.

**Comment by alexsoul95** [comment]
Same issue here, sdk 30 android.

**Comment by juanjosemayorga** [comment]
Same issue :(

**Comment by muralee** [comment]
Still same issue any update on this

**Comment by tastafur** [comment]
yes still same issue

**Comment by KoreanThinker** [comment]
https://github.com/react-native-cameraroll/react-native-cameraroll/issues/359#issuecomment-982648571

That fork work well. Someone merge please.

**Comment by mrdinklepus** [comment]
I am seeing this as well trying to build.  It works ok when targeting API 29, but fails when the target is set to 30.

**Comment by netronicus** [comment]
Still having the same problem :c

**Comment by dungnguyentri3110** [comment]
> As a quick solution try installing [my fork](https://github.com/BohdanSol/react-native-cameraroll) which does resolve issue on sdk 30 pagination for my purposes. I'm not sure about sorting, I do use only newest to oldest one, which also works. Edit: I'm not going to edit the fork till the package itself will fix the issue, so don't worry about it.

it is work well. thanks you bro. Some one merge this.

**Comment by tpagram-pwc** [comment]
Still an issue. Can a maintainer please merge in this fix? A big thank you to @BohdanSol for the fork in the meantime.

**Comment by KuiGoan** [comment]
There is my code. It's working on Android 10 and 11
`     if (isAlbumPresent) {
            // Notes: I got this error when using Environment.DIRECTORY_MOVIES
            // Primary directory Movies not allowed for content://media/external_primary/file; allowed directories are [Download, Documents]
            if (isVideo) {
              mediaCollection = MediaStore.Video.Media.getContentUri(MediaStore.VOLUME_EXTERNAL_PRIMARY);
              File dirDest = new File(Environment.DIRECTORY_MOVIES, album);
              mediaDetails.put(MediaStore.MediaColumns.RELATIVE_PATH, dirDest.toString() + File.separator);
              mediaDetails.put(Video.Media.DISPLAY_NAME, source.getName());
              mediaDetails.put(Video.Media.IS_PENDING, 1);
            } else {
              mediaCollection = MediaStore.Images.Media.getContentUri(MediaStore.VOLUME_EXTERNAL_PRIMARY);
              File dirDest = new File(Environment.DIRECTORY_PICTURES, album);
              mediaDetails.put(Images.Media.MIME_TYPE, mimeType);
              mediaDetails.put(MediaStore.MediaColumns.RELATIVE_PATH, dirDest.toString() + File.separator);
              mediaDetails.put(Images.Media.DISPLAY_NAME, source.getName());
              mediaDetails.put(Images.Media.IS_PENDING, 1);
            }
          } else {
            mediaCollection = MediaStore.Files.getContentUri(MediaStore.VOLUME_EXTERNAL_PRIMARY);
          }
          mediaDetails.put(MediaStore.MediaColumns.MIME_TYPE, mimeType);`
          
          Or can check in my source:
          https://github.com/KuiGoan/react-native-cameraroll/blob/master/android/src/main/java/com/reactnativecommunity/cameraroll/CameraRollModule.java

**Comment by vienle197** [comment]
Well, You need to increment the `first` param by `endCursor`, and this getPhotos function will fetch you more photos. You will need to check for duplicates of these photos. I have made a function to solve the problem temporarily:

`
function getPhotos(refresh = false) {
    if (loading || (isEnd && !refresh)) return;
    setLoading(true);
    const params = { first: PAGE_SIZE };
    if (endCursor && !refresh) {
      params.after = endCursor;
      params.first = parseInt(endCursor) + PAGE_SIZE;
    }
    CameraRoll.getPhotos(params).then(
      resp => {
        setLoading(false);
        setEndCursor(resp.page_info.end_cursor);
        setIsEnd(!resp.page_info.has_next_page)
        const imgs = resp?.edges?.map(e => e.node) || []
        const currentImgs = (images || [])
        setImages(
          !refresh ? currentImgs.concat(imgs.filter(img => !currentImgs.find(cImg => cImg.image.uri === img.image.uri)))
            : (resp?.edges?.map(e => e.node) || [])
        );
      },
    );
  }
`
