### ISSUE TITLE
The picker doesn’t show videos

### ISSUE THREAD

**Issue by Pietro-Putelli** [react-native-cameraroll/react-native-cameraroll#361]
I'm working on a custom picker components, and trying to get all user's camera roll photos, even if they are on iCloud and it seems to work, but when I try to get videos it doesn't work, returning an errore code in <Video/> component saying -1100 unable to find video. Maybe because of it's on iCloud? What's the problem?

iOS 14.1

**Comment by poteboy** [comment]
This happens to me as well. Any updates?

**Comment by Pietro-Putelli** [comment]
> This happens to me as well. Any updates?

Hey, I've solve using expo-media-library, the best library for doing this stuffs, and keep in mind to use localUri for getting video✌️

**Comment by tx-techxpert** [comment]
hi, @Pietro-Putelli  can you please share your code, 
I am stuck on the same issue, in ios cameraroll.getPhotos showing videos as images but working fine in android,

**Comment by Pietro-Putelli** [comment]
Hi, at the end I used expo media library, because it works really well, and in conjunction I suggest you to use the FlashList (by Shopify) for handling the gigantic amount of assets.

I'll post the code as soon as possible.
Bye
