### ISSUE TITLE
CameraRoll.getAlbums

### ISSUE THREAD

**Issue by chenweigh** [react-native-cameraroll/react-native-cameraroll#362]
### Version 
`4.1.2`

### Code
```Code
CameraRoll.getAlbums({assetType:'All'})
      .then(val => {
        console.log(val);
      })
```

### Problem
the albums is empty Array.  what is wrong ?

**Comment by rranjan14** [comment]
Happened to me as well. Did you try granting permission to read/write storage?

**Comment by KoreanThinker** [comment]
Are you solved?

**Comment by siddharth-kt** [comment]
any solution guys ?

**Comment by idrisssakhi** [comment]
I re-write the lib to propose new features and resolve most important opened issues → https://www.npmjs.com/package/react-native-photo-gallery-api

**Comment by CVHOANG-coder** [comment]
@rranjan14  
same issue. i tried to granting permission to read/write storage

**Comment by CVHOANG-coder** [comment]
> I re-write the lib to propose new features and resolve most important opened issues → https://www.npmjs.com/package/react-native-photo-gallery-api

i used it, but same issue

**Comment by canpoyrazoglu** [comment]
Probably not the solution but I was making a silly mistake: I was complaining that it returned 0 albums on simulator, whereas I really didn't have any albums. It won't return "All Photos" or "Portrait" etc. albums but only user created albums apparently. If you don't have any self-curated albums it will return zero items.
