### ISSUE TITLE
Android Target SDK 30, no access to content.

### ISSUE THREAD

**Issue by rahulnainwal107** [react-native-cameraroll/react-native-cameraroll#364]
When i am trying to delete images from cameraroll using below code it throw no access to content://media..... error.
`
await CameraRoll.deletePhotos(uris).then((result) =>
            console.log('Image deleted ', result),
          )};
`
uris is an array of urls like this:
`['file:///storage/emulated/0/Pictures/CAPTURED/rn_im…lib_temp_3face87c-1b9d-457b-91fe-c011073ef38c.jpg', 'file:///storage/emulated/0/Pictures/CAPTURED/rn_im…lib_temp_5ea7f6d3-3a3d-40d2-8679-6e40ffcfe27b.jpg', 'file:///storage/emulated/0/Pictures/CAPTURED/rn_im…lib_temp_0d370195-3254-4dd9-9c29-26d3287f13d1.jpg', 'file:///storage/emulated/0/Pictures/CAPTURED/rn_im…lib_temp_31d0ecc9-8aed-464c-9155-acc05f487d8d.jpg', 'file:///storage/emulated/0/Pictures/CAPTURED/rn_im…lib_temp_3b147a78-48fd-46a2-8388-7239a3381ca2.jpg', 'file:///storage/emulated/0/Pictures/CAPTURED/rn_im…lib_temp_e1aa682d-c876-4869-9a2b-9ed6495b2e88.jpg', 'file:///storage/emulated/0/Pictures/CAPTURED/rn_im…lib_temp_f5e269cd-eb34-4db2-97d6-e11461926a41.jpg', 'file:///storage/emulated/0/Pictures/CAPTURED/rn_im…lib_temp_d720514f-106e-405c-ab8e-47143de1fb91.jpg', 'file:///storage/emulated/0/Pictures/CAPTURED/rn_im…lib_temp_01f39001-fb3e-48bc-99c7-c5118c8963c6.jpg', 'file:///storage/emulated/0/Pictures/CAPTURED/rn_im…lib_temp_6a89ece8-5de2-4628-8ecc-9b3abf6cab35.jpg']`
![Screenshot_20211215-221452](https://user-images.githubusercontent.com/36499090/146229771-ad0116b6-18f9-4c7b-8f8b-f3b545f95061.png)

**Comment by GEllickson-Hover** [comment]
From what I can tell, this library is unviable on Android now if you're using latest Android standards and targeting 30... It still hasn't updated to support scoped storage, and the old `android:requestLegacyExternalStorage` does nothing anymore once you target API 30 (which has been required to update apps in the Play Store for several months now).

https://developer.android.com/training/data-storage/use-cases#opt-out-in-production-app

**Comment by idrisssakhi** [comment]
I re-write the lib to propose new features and resolve most important opened issues → https://www.npmjs.com/package/react-native-photo-gallery-api

**Comment by vijaygojiya** [comment]
> When i am trying to delete images from cameraroll using below code it throw no access to content://media..... error. `await CameraRoll.deletePhotos(uris).then((result) => console.log('Image deleted ', result), )};` uris is an array of urls like this: `['file:///storage/emulated/0/Pictures/CAPTURED/rn_im…lib_temp_3face87c-1b9d-457b-91fe-c011073ef38c.jpg', 'file:///storage/emulated/0/Pictures/CAPTURED/rn_im…lib_temp_5ea7f6d3-3a3d-40d2-8679-6e40ffcfe27b.jpg', 'file:///storage/emulated/0/Pictures/CAPTURED/rn_im…lib_temp_0d370195-3254-4dd9-9c29-26d3287f13d1.jpg', 'file:///storage/emulated/0/Pictures/CAPTURED/rn_im…lib_temp_31d0ecc9-8aed-464c-9155-acc05f487d8d.jpg', 'file:///storage/emulated/0/Pictures/CAPTURED/rn_im…lib_temp_3b147a78-48fd-46a2-8388-7239a3381ca2.jpg', 'file:///storage/emulated/0/Pictures/CAPTURED/rn_im…lib_temp_e1aa682d-c876-4869-9a2b-9ed6495b2e88.jpg', 'file:///storage/emulated/0/Pictures/CAPTURED/rn_im…lib_temp_f5e269cd-eb34-4db2-97d6-e11461926a41.jpg', 'file:///storage/emulated/0/Pictures/CAPTURED/rn_im…lib_temp_d720514f-106e-405c-ab8e-47143de1fb91.jpg', 'file:///storage/emulated/0/Pictures/CAPTURED/rn_im…lib_temp_01f39001-fb3e-48bc-99c7-c5118c8963c6.jpg', 'file:///storage/emulated/0/Pictures/CAPTURED/rn_im…lib_temp_6a89ece8-5de2-4628-8ecc-9b3abf6cab35.jpg']` ![Screenshot_20211215-221452](https://user-images.githubusercontent.com/36499090/146229771-ad0116b6-18f9-4c7b-8f8b-f3b545f95061.png)

hey also facing same issue are you able to fix it? please let me know the solution. thank you

**Comment by burak4ydin** [comment]
same issue... any solution?

**Comment by derneuere** [comment]
You have to add  <uses-permission android:name="android.permission.MANAGE_EXTERNAL_STORAGE"/> to your AndroidManifest.xml

You then have to go to settings and choose the permission "Files and Media" and then select "Allow management of all files".

There does not seem to be a way to set this permission within the app / by code, so you probably have to notify the user that he has to set this up manually.

**Comment by Arjan-Zuidema** [comment]
Closing this issue. Comment about should fix the problem.
