### ISSUE TITLE
No NSPhotoLibraryUsageDescription causes crash without error

### ISSUE THREAD

**Issue by formula1** [react-native-cameraroll/react-native-cameraroll#371]
Had no idea what was causing the crash, thankfully it got sorted out.

Can the [info.plist check](https://github.com/react-native-cameraroll/react-native-cameraroll/blob/master/ios/RNCCameraRollManager.m#L469) happen without being in a react dev environment? If so, it's possible to reject the promise  gracefully instead of simply just allowing it to crash without error.

I didn't take too much time on this crash so I consider that nice.

I noticed something that seems a little weird
- https://github.com/react-native-cameraroll/react-native-cameraroll/blob/master/ios/RNCCameraRollManager.m#L267
  - `checkPhotoLibraryConfig()` Checks the photo library config
- https://github.com/react-native-cameraroll/react-native-cameraroll/blob/master/ios/RNCCameraRollManager.m#L470
  - `RCTLogError(@"NSPhotoLibraryUsageDescription key must be present in Info.plist to use camera roll.");`

I'm still working in a dev environment so I would have certainly liked to see this error. But it seems like it checks a [global RCT_DEV](https://github.com/react-native-cameraroll/react-native-cameraroll/blob/master/ios/RNCCameraRollManager.m#L468)? I'm not familiar with objective c so I don't know if this set in the .h file or where this is coming from. But how can I set this variable to true? Would it also create unexpected logs from other modules? I have enough logs in my own debugging situation, I don't particularly want to get a ton of errors.

### My Environment

```
@react-native-community/cameraroll: 4.1.2

System:
    OS: macOS 11.6
    CPU: (8) x64 Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz
    Memory: 1.05 GB / 16.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 16.11.1 - /usr/local/bin/node
    Yarn: 1.7.0 - /usr/local/bin/yarn
    npm: 8.0.0 - /usr/local/bin/npm
    Watchman: Not Found
  Managers:
    CocoaPods: 1.11.2 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.2, iOS 15.2, macOS 12.1, tvOS 15.2, watchOS 8.3
    Android SDK: Not Found
  IDEs:
    Android Studio: Not Found
    Xcode: 13.2.1/13C100 - /usr/bin/xcodebuild
  Languages:
    Java: 10.0.2 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.2 => 17.0.2 
    react-native: 0.66.4 => 0.66.4 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

**Comment by idrisssakhi** [comment]
I re-write the lib to propose new features and resolve most important opened issues → https://www.npmjs.com/package/react-native-photo-gallery-api
