### ISSUE TITLE
Not viable on Android 11 and above without scoped storage support

### ISSUE THREAD

**Issue by GEllickson-Hover** [react-native-cameraroll/react-native-cameraroll#377]
Making an issue just to emphasize that this library is not viable on Android for production apps anymore in Google Play unless support for scoped storage is added. I see some existing PRs for this, but no updates on that for a long time, but scoped storage has been around for a couple years now.

The old `android:requestLegacyExternalStorage` does nothing anymore once you target API 30 (which has been required to update apps in the Play Store for several months now).
https://developer.android.com/training/data-storage/use-cases#opt-out-in-production-app
https://developer.android.com/about/versions/11/privacy/storage#scoped-storage

Unless this library is updated for scoped storage, this isn't appropriate for any production Android app using Google Play as new devices won't work with this consistently.

**Comment by idrisssakhi** [comment]
I re-write the lib to propose new features and resolve most important opened issues → https://www.npmjs.com/package/react-native-photo-gallery-api
