### ISSUE TITLE
'Get Media Types' albums from IOS device

### ISSUE THREAD

**Issue by viniciusdba27** [react-native-cameraroll/react-native-cameraroll#378]
Hi Everyone,

Would you know if it's possible to get the 'Media Types' albums of an IOS device? If so, how can that be achieved?

![image](https://user-images.githubusercontent.com/8820814/157593667-38e1bcb0-c8ce-4b6b-8bd2-8accbd55ebd1.png)

thank you

**Comment by eranga-akva** [comment]
Did you find any workaround for this?

**Comment by viniciusdba27** [comment]
Unfortunately no.
