### ISSUE TITLE
Video file saved as image

### ISSUE THREAD

**Issue by STU-DESIGNER** [react-native-cameraroll/react-native-cameraroll#380]
I am on iOS and whenever I save to the CameraRoll I do a quick fetch for a blob afterwards and it comes back as type 'image/jpeg'.

The video before I save to CameraRoll is type video/QuickTime.  Not sure what's going on here.

            let URI = await CameraRoll.save(`file://${path}`, {
                type: 'video',
            });

           let vbp = await fetch(URI);
                      let result = await vbp.blob();
                      console.log(result);

          {"_data": {"__collector": {}, "blobId": "D523E484-DD16-4441-BDD1-70DF0B6186AA", "name": "001.jpeg", "offset": 0, "size": 128149, "type": "image/jpeg"}}

Also funny enough I am able to use this file path for playback on a video preview.  But when it comes to fetching it is labelled as type: "image/jpeg"

**Comment by idrisssakhi** [comment]
I re-write the lib to propose new features and resolve most important opened issues → https://www.npmjs.com/package/react-native-photo-gallery-api
