### ISSUE TITLE
Question: Create a new album

### ISSUE THREAD

**Issue by JohnZcp** [react-native-cameraroll/react-native-cameraroll#385]
Hi, I checked the readme file and wonder if this library has the method to create a new ablum?

**Comment by Stortag** [comment]
Yes if you look properly you will notice under usage / methods / save 
[https://github.com/react-native-cameraroll/react-native-cameraroll#save](url)

**Comment by idrisssakhi** [comment]
I re-write the lib to propose new features and resolve most important opened issues → https://www.npmjs.com/package/react-native-photo-gallery-api
