### ISSUE TITLE
> Task :react-native-community_cameraroll:compileDebugJavaWithJavac FAILED

### ISSUE THREAD

**Issue by JohnZcp** [react-native-cameraroll/react-native-cameraroll#389]
I received this error when I tried to run the app on android.

> Task :react-native-community_cameraroll:compileDebugJavaWithJavac FAILED

Deprecated Gradle features were used in this build, making it incompatible with Gradle 8.0.

You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.

> Configure project :react-native-community_cameraroll
Subproject ':react-native-community_cameraroll' has location '/Users/ziyuanzhou/Desktop/signdectection/App/node_modules/@react-native-community/cameraroll/android' which is outside of the project root. This behaviour has been deprecated and is scheduled to be removed in Gradle 8.0. Consult the upgrading guide for further information: https://docs.gradle.org/7.2/userguide/upgrading_version_7.html#deprecated_flat_project_structure
The RepositoryHandler.jcenter() method has been deprecated. This is scheduled to be removed in Gradle 8.0. JFrog announced JCenter's sunset in February 2021. Use mavenCentral() instead. Consult the upgrading guide for further information: https://docs.gradle.org/7.2/userguide/upgrading_version_6.html#jcenter_deprecation
        at build_d16b4xxuymnjucki6xbmpsrql$_run_closure1$_closure2.doCall(/Users/ziyuanzhou/Desktop/signdectection/App/node_modules/@react-native-community/cameraroll/android/build.gradle:5)
        (Run with --stacktrace to get the full stack trace of this deprecation warning.)

How should I fix it?

**Comment by idrisssakhi** [comment]
please check this lib, it provides all same things => react-native-photo-gallery-api https://www.npmjs.com/package/react-native-photo-gallery-api

**Comment by ChenhuaWANG22** [comment]
I got an error like this. Solved with below:

Cause:
There are two "java_home" existing at the same time, i.e. JRE(Java Runtime Environment) and JDK(Java Development Kit). 

> The problem is that with the update the built-in java took precedence and it doesn't have the SDK because it's just the runtime.

run below cmd to check:
`/usr/libexec/java_home -V`

![image](https://user-images.githubusercontent.com/17723793/181169235-3f39fb57-cd99-4f71-967f-6b6fe404f32c.png)
it's unnormal to have two virtual machine records. JavaAppletPlugin.plugin is JRE and jdk1.8.0_311.jdk is JDK.
ref: docs.oracle.com

![image](https://user-images.githubusercontent.com/17723793/181169425-1a1729a6-ac64-4092-88a8-8dc90faccb0c.png)
this is the result after fixing.

Besides, recall if OS is updated recently (I did).

Solution 1: uninstall JRE.

> To uninstall the JRE on macOS:
> You must have Administrator privileges to remove one directory and one file (a symlink).
> Note:
> 
> Do not uninstall Java by removing the Java tools from /usr/bin. This directory is part of the system software and any changes will be reset by Apple the next time that you perform an update of the OS.
> 
> Go to /Library/Internet Plug-Ins.
> Remove the JavaAppletPlugin.plugin directory by executing the rm command as a root user or by using the sudo tool.
> Go to /Library/PreferencePanes.
> Remove JavaControlPanel.prefpane by executing the rm command as a root user or by using the sudo tool.

ref: https://docs.oracle.com/javase/9/install/installation-jdk-and-jre-macos.htm#JSJIG-GUID-577CEA7C-E51C-416D-B9C6-B1469F45AC78

Run below again to make sure there is only one virtual machine record.
By the way, I use "rm" cmd to remove, while it doesn't work. I guess these two directions are set to immune. Later I use "Finder" to that path and throw them to trash bin. 
`/usr/libexec/java_home -V`
check the image above for the result after fixing.

below two additional solutions are not tested by me, check below ref link to know more.

Solution 2:  change your java home and add the java binary to your .zshrc to find your java home execute.
Solution 3:  copied "tools.jar" or anything that mentioned missing in the error message from /Library/Java/JavaVirtualMachines/jdk1.8.0_111.jdk/Contents/Home/lib/ to /Library/Internet Plug-Ins/JavaAppletPlugin.plugin/Contents/Home/lib/.

ref: 
https://newbedev.com/could-not-find-tools-jar-please-check-that-library-internet-plug-ins-javaappletplugin-plugin-contents-home-contains-a-valid-jdk-installation
https://blog.csdn.net/gongsunjinqian/article/details/121228000
