### ISSUE TITLE
Image is saved on android but Promise from CameraRoll.save is rejected

### ISSUE THREAD

**Issue by Mistra97** [react-native-cameraroll/react-native-cameraroll#394]
I have a very simple logic for saving images on android. Images do get saved on the device but Promise always returns error, which is empty string. I have logic which needs to be run after image gets successfully saved but right now I can't utilize it on android.

`CameraRoll.save('file://' + path, {type: 'photo'})
                     .then(...)
                     .catch(err => console.log('save failed ' + err))`

log I get is:

> save failed

**Comment by idrisssakhi** [comment]
please check this lib, it provides all same things => react-native-photo-gallery-api https://www.npmjs.com/package/react-native-photo-gallery-api
