### ISSUE TITLE
Is this package dead?

### ISSUE THREAD

**Issue by professorkolik** [react-native-cameraroll/react-native-cameraroll#397]
Hi there!

We are looking replacement for expo-media-library, and seems only `react-native-cameraroll`  might provide all the features we need. But we see that there is no update for a year.

Any plans to recover it?

Thanks

**Comment by idrissakhi** [comment]
i forked the project and resolved all it issues, and also provided new features, please check https://www.npmjs.com/package/react-native-photo-gallery-api

**Comment by bartolkaruza** [comment]
@idrissakhi if you would like, I can give you maintainer access to this repository instead of maintaining a fork. You'd reach more people this way. About a year ago I've onboarded 3-4 people as maintainers, but nobody seems to have been able to find the time to actually regularly process issues and pull requests. If anyone else is interested in taking on this responsibility, let me know.

**Comment by bartolkaruza** [comment]
@lukebrandonfarrell

**Comment by bartolkaruza** [comment]
Also, I'm seeing you already offer this; https://github.com/react-native-cameraroll/react-native-cameraroll/issues/293 as well as @Arjan-Zuidema

Let me add you guys.

**Comment by bartolkaruza** [comment]
Ok, you're both invited for maintainer role. Make sure you read through this; https://github.com/react-native-cameraroll/react-native-cameraroll/blob/master/.circleci/config.yml on how deployments work. This process is driven by https://www.conventionalcommits.org/

**Comment by idrissakhi** [comment]
@bartolkaruza I would love to please.

**Comment by Arjan-Zuidema** [comment]
Thanks @bartolkaruza 

I am in vacation right now. Will be back in two weeks

**Comment by professorkolik** [comment]
@siddharth-kt it's good enough, but when it comes to update it or any topic with permissions, which is handled by core modules it takes ages for them to resolve it

As well as it's too difficult to provide them reproducible sample, since most of our issues not reproducible on our side but on production on users side

**Comment by siddharth-kt** [comment]
@professorkolik 🤔 thanks for letting me know.
Since i am using expo-media-library (for android) can you please tell me any trouble/errors i might face ?

**Comment by professorkolik** [comment]
@siddharth-kt the most common problems are getAssetInfoAssync and folders and photos are not visible for users

**Comment by bartolkaruza** [comment]
I've tried to get a healthy maintainer group off the ground here, but it's hard to get focus on this. Maintaining takes hours, unpaid hours, by smart people. I volunteered to take this package out of React Core years ago and after about one year, I stopped working on apps that used this library and couldn't find the time and energy to maintain a healthy test setup needed to vet code going into this package.

This package is clearly used by a lot of apps, by developers that are getting paid to work on camera related apps. What this repo really needs is for someone to champion this and dedicate time to maintain this package. This could be someone either passionate about open source and cameraroll or a company that profits from an app using this code to step up and make sure this is a continuously updated and reliably maintained package.

I'm going to keep this issue open until we resolve this or everyone writes their own native code.

#342 #242

**Comment by bartolkaruza** [comment]
@idrissakhi @Arjan-Zuidema @santhoshvai Thank you so much for stepping up. Future for this package looks bright 💯
