### ISSUE TITLE
Getting error when saving image to Camera roll on iOS TestFlight build

### ISSUE THREAD

**Issue by i-vlaisavljevic-vegait** [react-native-cameraroll/react-native-cameraroll#398]
Saving images works perfectly with Android apk and also with iOS simulator and on a real device as well. But on TestFlight build I get asked if I allow access to the photo library and I allow it, but I get error. If I try to put error message to Alert.alert() -> app crashes.

Error:

"code":"E UNABLE_TO_SAVE" 
"message":"The operation couldn't be completed. (PHPhotosError-Domain error 3303.)"
 "domain": "PHPhoto-sErrorDomain"

I have added these keys in Info.plist:
<key>NSPhotoLibraryUsageDescription</key>
    <string>This app requires access to the photo library.</string>
 <key>NSPhotoLibraryAddUsageDescription</key>
    <string>This app requires access to the photo library.</string>

**Comment by Arjan-Zuidema** [comment]
Since version 5 a lot has changed. My guess this has been fixed now. Can you please verify? I will close this for now, feel free to reopen when the problem still persist.

**Comment by Hashir524** [comment]
Using the latest version and facing the same problem. Any Solutions?
