### ISSUE TITLE
Retriever.release error

### ISSUE THREAD

**Issue by vladimirevstratov** [react-native-cameraroll/react-native-cameraroll#402]
When i try to run my app on android, this problem appeared on compilation stage.

```
Error: Command failed: ./gradlew app:installDebug -PreactNativeDevServerPort=8081
~/node_modules/@react-native-community/cameraroll/android/src/main/java/com/reactnativecommunity/cameraroll/CameraRollModule.java:650: error: unreported exception IOException; must be caught or declared to be thrown
      retriever.release();
                       ^
~/node_modules/@react-native-community/cameraroll/android/src/main/java/com/reactnativecommunity/cameraroll/CameraRollModule.java:713: error: unreported exception IOException; must be caught or declared to be thrown
          retriever.release();
                           ^
Note: ~/node_modules/@react-native-community/cameraroll/android/src/main/java/com/reactnativecommunity/cameraroll/CameraRollModule.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
2 errors

```

React Native 0.69.4
com.android.tools.build:gradle:7.1.1
Repository: mavenCentral instead of jcenter

**Comment by vladimirevstratov** [comment]
Solution:
Replace all `retriever.release();` in `@react-native-community/cameraroll/android/src/main/java/com/reactnativecommunity/cameraroll/CameraRollModule.java`  with
```
try {
  retriever.release();
} catch (IOException ex) {
  // handle the exception here
}
```

**Comment by Arjan-Zuidema** [comment]
If you could create a pull request with a fix that would be awesome!

**Comment by vladimirevstratov** [comment]
> ~~If you could create a pull request with a fix that would be awesome!~~
> 
> 
> 
> Pull request here #413
> 
> 
> 
> 

Oh, didn't see notification of your response 🙂

**Comment by santhoshvai** [comment]
Note: Make sure the compile SDK version is set to 33. Otherwise, the suggested solution will cause a compilation error.

**Comment by Pranavpatel428** [comment]
> Note: Make sure the compile SDK version is set to 33. Otherwise, the suggested solution will cause a compilation error.

Hello, I have updated my compile SDK version to 33 but still I am getting this error. Also, I am not able to create a build.
