### ISSUE TITLE
Save gif

### ISSUE THREAD

**Issue by ankitpro** [react-native-cameraroll/react-native-cameraroll#407]
I'm unable to save gif as animated. Instead it is getting saved as static image. Can you please address this issue.

**Comment by Arjan-Zuidema** [comment]
There is a pull request for it in progress. See #272

**Comment by ankitpro** [comment]
Thank you for the response.

**Comment by ankitpro** [comment]
How long do you think this will take? @Arjan-Zuidema

**Comment by ankitpro** [comment]
Do you have a tentative date? @Arjan-Zuidema

**Comment by Arjan-Zuidema** [comment]
It looks like the original author of the pull request is no longer active. I'll see if have any time this week to fix the pull request and create a release.

**Comment by Arjan-Zuidema** [comment]
This is now fixed in version 5.0.3
