### ISSUE TITLE
Save video error on Android: MIME type video/mp4 cannot be inserted into content://media/external/images/media; expected MIME type under image/*

### ISSUE THREAD

**Issue by hwth** [react-native-cameraroll/react-native-cameraroll#423]
I get this error when trying to save a video from app cache directory to gallery on **Android only**

<img width="317" alt="image" src="https://user-images.githubusercontent.com/44694010/188324872-ca7b8e06-8d20-484a-9eab-4d4f4bb3c2b9.png">

Does anyone see the same issue?

**Comment by ahardy42** [comment]
yeah i'm seeing the same error.  annoyingly this is in a try/catch block but it's throwing anyway. I'm using

```
const saved = await CameraRoll.save(video, { type: 'video' }) // video is a URI string 
```

**Comment by Christophertdoc** [comment]
I am experiencing the same issue.

**Comment by zees98** [comment]
**Greetings**
I am having the same issue over here while trying to save a video captured by **_expo camera_** package to gallery. 
`await CameraRoll.save(selectedVideo, { type: "auto", album: "MyAwesomeApp" })`

**Comment by hwth** [comment]
I did a quick fix in this pull request: https://github.com/react-native-cameraroll/react-native-cameraroll/pull/430

Hopefully it will help you guys!

**Comment by adidoes** [comment]
Thanks for the patch @hwth! Hopefully this gets merged fast

**Comment by orchsik** [comment]
Still having the same problem.

**Comment by Arjan-Zuidema** [comment]
@orchsik this should be fixed in v5.0.3. Can you provide an example video to test this with?

**Comment by magom001** [comment]
It appears to be happening in 5.2.3 as well

**Comment by magom001** [comment]
It appears that `Utils.getMimeType` returns an empty string for URI:

/data/user/0/com.package.name/cache/A43D4D4904409F0DE22163D05C64202341CDDD0F9C8BAB303A3F9661ACDC4383/FileCache/Screen Recording 2023-02-20 at 10.44.14-1.mov

**Comment by magom001** [comment]
Please check this fix: https://github.com/react-native-cameraroll/react-native-cameraroll/pull/465

**Comment by magom001** [comment]
@Arjan-Zuidema could you please review the fix?

**Comment by SHRASHRI08** [comment]
Extremely annoyed by this error, 
It only appears in android API Level >=30

**Comment by Arjan-Zuidema** [comment]
@SHRASHRI08 This was fixed in 5.2.4. Have you tried @stefan-sabau solution?

**Comment by Leslie-Wong-H** [comment]
Using 5.6.0, I faced the same error in Android with this special file URL. Apparently, the file URL has been encoded without spaces. 


```
import { CameraRoll } from '@react-native-camera-roll/camera-roll';

...
    
const filePath =  'file:///data/user/0/com.example.example/files/%5BReinForce%5D%20Shinryaku!!%20Ika%20Musume%20OVA%202%20(BDRip%201920x1080%20x264%20FLAC).mp4';

const url: string = await CameraRoll.save(
     filePath,
     'video'
    );
```

React Native: 0.72.8

**Comment by Leslie-Wong-H** [comment]
Another file URL with the same error. 

`file:///data/user/0/com.example.example/files/%5BReinForce%5D%20Suzumiya%20Haruhi%20no%20Yuuutsu%2004%20(BDRip%201920x1080%20x264%20FLAC).mp4`

Is it because of the brackets?

**Comment by Leslie-Wong-H** [comment]
Removing the brackets and exclamation mark solves the problem. 
```
    fileName = fileName.replace(/\(|\)|\!/g, '');
```
