### ISSUE TITLE
Cameraroll.getPhotos metadata issue on android

### ISSUE THREAD

**Issue by dbadalyan97** [react-native-cameraroll/react-native-cameraroll#424]
I tried to get the photos from the android device using getPhotos method, but I got this result.

{
               "node": {
                    "location": null,
                    "modified": 1662107826,
                    "group_name": "Download",
                    "timestamp": 1572485158,
                    "type": "video/mp4",
                    "image": {
                         "fileSize": null,
                         "filename": null,
                         "playableDuration": null,
                         "height": null,
                         "width": null,
                         "uri": "file:///storage/emulated/0/Download/mixkit-dog-catches-a-ball-in-a-river-1494.mp4"
                    }
               }
          },
          {
               "node": {
                    "location": null,
                    "modified": 1662104038,
                    "group_name": "Pictures",
                    "timestamp": 1662104038.326,
                    "type": "image/jpeg",
                    "image": {
                         "fileSize": null,
                         "filename": null,
                         "playableDuration": null,
                         "height": null,
                         "width": null,
                         "uri": "file:///storage/emulated/0/Pictures/IMG_20220902_113358.jpg"
                    }
               }
          },
}

Can you tell me, why I get null in metadata only for Android?

**Comment by Arjan-Zuidema** [comment]
Can you provide some more info? What [params](https://github.com/react-native-cameraroll/react-native-cameraroll#getphotos) did you use in the `getPhotos` method?

If you do not provide the include, you will not get any data.

**Comment by dbadalyan97** [comment]
I have used the "first" param and I got the data from the device, but the problem is that I couldn't know the size, width, height, and more about the image.

**Comment by Arjan-Zuidema** [comment]
You need to use `include` in the params to get the metadata you want. For example if you want the width/height and file size you need:

```js
const params = {
  first: 10,
  include: ['fileSize', 'imageSize']
}

CameraRoll.getPhotos(params);
```
