### ISSUE TITLE
React Native Cameraroll doesn't access the photos from the device on Android 13

### ISSUE THREAD

**Issue by khushal87** [react-native-cameraroll/react-native-cameraroll#426]
Lately, the application using react native cameraroll is not able to access the photos from the file system even after giving permission on the settings for Android 13.

This could be due to the fact that:

With Android 13 the `READ_EXTERNAL_STORAGE` is replaced with granular permissions like `READ_MEDIA_IMAGES`, `READ_MEDIA_VIDEO` etc.
Ref - https://developer.android.com/about/versions/13/behavior-changes-13#granular-media-permissions

**Comment by vanGalilea** [comment]
Any updates on this one guy?

**Comment by Arjan-Zuidema** [comment]
I'm sorry. I don't have time any time soon. Maybe @santhoshvai or @idrissakhi ?

**Comment by idrissakhi** [comment]
I will try to check this, this weekend guys, stay tuned 😁🙂

**Comment by jshinrock** [comment]
Any update? Awaiting to fix.

**Comment by Arjan-Zuidema** [comment]
This is not something that is fixed in this package. The [README.md permissions](https://github.com/react-native-cameraroll/react-native-cameraroll#permissions) has a section on the permissions. I will update this section
