### ISSUE TITLE
Publish latest version 5.0.2 to npm that has 4.1.2 with correct name

### ISSUE THREAD

**Issue by Romick2005** [react-native-cameraroll/react-native-cameraroll#427]
Can you please publish newest version to the npm with the new package name?
![image](https://user-images.githubusercontent.com/17779660/189140012-b6963888-d73c-4acf-9e0f-46dd8b944b79.png)
![image](https://user-images.githubusercontent.com/17779660/189140445-623a4870-689b-4b3f-872c-768da94ea756.png)
![image](https://user-images.githubusercontent.com/17779660/189140105-97488a51-5bdc-4364-b5b8-710bab453dda.png)

**Comment by Arjan-Zuidema** [comment]
The package has been renamed. Package here: https://www.npmjs.com/package/@react-native-camera-roll/camera-roll

**Comment by Romick2005** [comment]
Yes I see, but how we can ensure that users will get notified about newest version using **npm outdated** mechanism? Because of renaming it does not inform that new version of the package is available.

**Comment by Arjan-Zuidema** [comment]
@Romick2005 [@react-native-community/cameraroll](https://www.npmjs.com/package/@react-native-community/cameraroll) package has been marked as deprecated. The other one you posted a screenshot of is nor from the React Native Core team nor the React Native Community. So there is nothing we can do to mark it as deprecated unfortunately.

**Comment by Romick2005** [comment]
> @Romick2005 [@react-native-community/cameraroll](https://www.npmjs.com/package/@react-native-community/cameraroll) package has been marked as deprecated. The other one you posted a screenshot of is nor from the React Native Core team nor the React Native Community. So there is nothing we can do to mark it as deprecated unfortunately.

Understand. Thank you!
