### ISSUE TITLE
Cannot save image to gallery on Android

### ISSUE THREAD

**Issue by lamlengend98** [react-native-cameraroll/react-native-cameraroll#431]
Hi all, I have a problem about saving image  on Android
```
CameraRoll.saveToCameraRoll(urls[index], 'photo')
```
or
```
CameraRoll.save(urls[index], { type: 'photo' })
```
both received same exception
```
/1922367c2bf0d6c5/media/file_name.jpg: open failed: ENOENT (No such file or directory)
```
here is my AndroidManifest.xml
```
<uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />
<uses-permission android:name="android.permission.DOWNLOAD_WITHOUT_NOTIFICATION" />
<uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE" />
<application android:requestLegacyExternalStorage="true"... >
```
package.json
```
"@react-native-camera-roll/camera-roll": "^5.0.2",
"react-native": "0.68.1",
```

**Comment by HaddyYang** [comment]
I got the same error

**Comment by haroon-cb** [comment]
Were you able to get any solution?

**Comment by lrobak0** [comment]
I got the same error

**Comment by serp1412** [comment]
same error on my end. Please help us out

**Comment by santhoshvai** [comment]
Which android OS do you get this error? 13 I believe?

**Comment by serp1412** [comment]
So the error happens when attempt to use the `save` function with a non-local link.
Fixing it means download image separately to local storage and passing the local path instead

It's stated in the docs on github, but not in the documentation in the package. I'd really recommend adding that and making it more obvious that on Android it's important to go through this.

**Comment by Arjan-Zuidema** [comment]
Okay, so from what I understand it's a documentation thing?

@serp1412 Unfortunately I personally don't have much time to fix things. I don't know about the other maintainers, but if your could help out by creating a pull request, that would be awesome!

**Comment by santhoshvai** [comment]
@serp1412 additionally would it make sense to throw an error on Android if it's not a local link. Local link must start with `file://` I believe. I would be happy to help too. It would be great if you could help us out by making a PR to fix this.

**Comment by caijiami** [comment]
有什么进展吗，我也遇到了相同问题

**Comment by hungtooc** [comment]
> 

Hi, I'm newbie of react native. I don't understand why in android, the image much be in ```local storage``` first and save that image again using this library???. Do we have to save the image twice? thanks

**Comment by naytun** [comment]
I have the same issue and why anybody is answering?

**Comment by deyanskiq** [comment]
any update here?
