### ISSUE TITLE
Cannot infer mime type from extensionless url

### ISSUE THREAD

**Issue by t0nyh0** [react-native-cameraroll/react-native-cameraroll#437]
Currently the android java code detects the mimetype based on URL extension.  This will break saving the file in android if there is no mime-type.

**Potential Solution 1**
Infer from HTTP response headers

**Potential Solution 2**
Provide an override in the options property

![image](https://user-images.githubusercontent.com/898773/197483778-aa37a257-2fec-4e87-b269-cd08162b3f7d.png)

**Comment by anastasia-son** [comment]
When I try to save video from app cache to a particular album, the uri is extensionless and I get the same error. Android 12
