### ISSUE TITLE
Execution failed for task ':@react-native-camera-roll_camera-roll:generateDebugRFile'. in react native 0.68.2

### ISSUE THREAD

**Issue by Farhatdjehan** [react-native-cameraroll/react-native-cameraroll#438]
i just recently use this library for save my photo to gallery.. but when i trying to run the apps with the libs.. my got error like this

Execution failed for task ':@react-native-camera-roll_camera-roll:generateDebugRFile'.
> Could not resolve all files for configuration ':@react-native-camera-roll_camera-roll:debugCompileClasspath'.
   > Failed to transform react-native-0.71.0-rc.0-debug.aar (com.facebook.react:react-native:0.71.0-rc.0) to match attributes {artifactType=android-symbol-with-package-name, com.android.build.api.attributes.BuildTypeAttr=debug, org.gradle.category=library, org.gradle.dependency.bundling=external, org.gradle.libraryelements=aar, org.gradle.status=release, org.gradle.usage=java-api}.
      > Could not find react-native-0.71.0-rc.0-debug.aar (com.facebook.react:react-native:0.71.0-rc.0).
        Searched in the following locations:
            https://repo.maven.apache.org/maven2/com/facebook/react/react-native/0.71.0-rc.0/react-native-0.71.0-rc.0-debug.aar

**Comment by Arjan-Zuidema** [comment]
What version of this package and react-native are you using?
Have you seen [this](https://github.com/facebook/react-native/issues/35210) issue?
