### ISSUE TITLE
[Android] CameraRoll.getPhotos return empty edges on some android devices

### ISSUE THREAD

**Issue by alqubo** [react-native-cameraroll/react-native-cameraroll#441]
## Versions
- `react-native 0.70.5`
- `@react-native-camera-roll/camera-roll 5.1.0`

## Problem
On some android devices when i call `getPhotos` return empty edges response.

### Android Manifest
Permissions:
```java
<uses-permission android:name="android.permission.READ_MEDIA_IMAGES"/>
<uses-permission android:name="android.permission.READ_MEDIA_VIDEO"/>
<uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE" />
<uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE"/>
```

Application:
```java
android:requestLegacyExternalStorage="true"
```

### Code
```js
await CameraRoll.getPhotos({
  first: 20,
  after: endCursor,
  assetType: 'Photos',
  groupTypes: 'All',
  include: ['imageSize'],
});
```

### Promise response
```json
{
  "edges": [],
  "page_info": {
    "has_next_page": false
  }
}
```
### Device model example
- Redmi Note 10S (Android 12)

**Comment by alqubo** [comment]
Removing `include: ['imageSize']` works well. Maybe some is wrong when getting image size

**Comment by adefuentes** [comment]
+1

**Comment by Arjan-Zuidema** [comment]
I am unable to reproduce this issue on the devices I have available. @alqubo @adefuentes maybe you can do some investigation and try to create a pull request?

**Comment by Arise-cn** [comment]
+1

**Comment by Arise-cn** [comment]
+1
