### ISSUE TITLE
CameraRoll is undefined.

### ISSUE THREAD

**Issue by Itrainlcincom** [react-native-cameraroll/react-native-cameraroll#446]
Hi.

I use  "@react-native-camera-roll/camera-roll": "^5.2.0" in project.

In my code.
import CameraRoll from "@react-native-camera-roll/camera-roll";
console.log(CameraRoll);

--> Result undefined.

Please help me.

**Comment by Arjan-Zuidema** [comment]
Try

```js
import { CameraRoll } from "@react-native-camera-roll/camera-roll"
```

See: [Migrating from the core react-native module](https://github.com/react-native-cameraroll/react-native-cameraroll#migrating-from-the-core-react-native-module) in the docs
