### ISSUE TITLE
No enough description for iosGetImageDataById

### ISSUE THREAD

**Issue by Caliman-Nicolae** [react-native-cameraroll/react-native-cameraroll#449]
This function does not work for some reason.
I just requested media using getPhotos, and then I try to use iosGetImageDataById to request another information for file `ph://xxxx` and I get the error: "Error while getting file path". Seems that `imageURL.absoluteString` is null

**Comment by VaibhavValere** [comment]
Same for me, has there been any workaround for this ?

**Comment by vforvasile** [comment]
Should be fixed in 5.6.1
