### ISSUE TITLE
Cannot resolve symbol 'R'

### ISSUE THREAD

**Issue by a728384698** [react-native-cameraroll/react-native-cameraroll#451]
![截屏2023-01-06 17 44 11](https://user-images.githubusercontent.com/7380874/210975124-4e1b123a-89c7-451a-9bbd-d48babfd1ced.png)
    dependencies {
      classpath("com.android.tools.build:gradle:4.2.2")
    }

distributionUrl=https\://services.gradle.org/distributions/gradle-6.2-all.zip

**Comment by Arjan-Zuidema** [comment]
What `compileSdkVersion` are you using in `android/build.gradle`?
