### ISSUE TITLE
I receive 'React/RCTBridge.h' file not found, with the latest version of react native, so actualy 0.71.1.

### ISSUE THREAD

**Issue by Pnlvfx** [react-native-cameraroll/react-native-cameraroll#457]
Anyone have tried this package with the latest version? Maybe i'm doing something wrong?

**Comment by ahaseeb001** [comment]
@Pnlvfx  hello can you please help me by telling how integrate library into android app folder because when i start making build it shows error ===>.  Build file '/Volumes/C/Muskeeters/fm-podcast-application/android/app/build.gradle' line: 272

**Comment by Pnlvfx** [comment]
I'm on ios

**Comment by Rubeenvz** [comment]
Hi, I have the same problem.

I'm using this:

"dependencies": {
    "@react-native-camera-roll/camera-roll": "^5.2.3",
    "react": "18.2.0",
    "react-native": "0.71.1"
  },
  
  I have another project and it has the same problem
  
  "dependencies": {
    "@react-native-firebase/app": "^16.4.6",
    "@react-native-firebase/auth": "^16.4.6",
    "@react-native-firebase/database": "^16.5.0",
    "@react-native-material/core": "^1.3.7",
    "@react-native-picker/picker": "^2.4.8",
    "@react-navigation/bottom-tabs": "^6.5.1",
    "@react-navigation/native": "^6.1.1",
    "react": "18.1.0",
    "react-native": "0.70.6",
    "react-native-qrcode-svg": "^6.1.2",
    "react-native-reanimated": "^2.13.0",
    "react-native-safe-area-context": "^4.4.1",
    "react-native-screens": "^3.18.2",
    "react-native-svg": "^13.6.0"
  },

**Comment by ahaseeb001** [comment]
@Rubeenvz my issu solved ! Tell me! Did you done any manual configurations in android or ios folder ?

**Comment by Rubeenvz** [comment]
@ahseeb001 I think I'm doing everything fine :D

I'm doing this:

1.- yarn add @react-native-camera-roll/camera-roll
2.- Libraries -> Add folder to ..... -> @react-native-camera-roll/camera-roll/RNCCameraroll.xcodeproj
3.- Add libRNCCcameraroll.a

![image](https://user-images.githubusercontent.com/66394271/215219442-06485929-ec9b-43cd-b824-8712231598d2.png)

Also, I added NSPhotoLibraryUsageDescription key in tha Info.plist file

I'm just developing an IOS app, What else do I need to do? Thanks :D

**Comment by ahaseeb001** [comment]
@Rubeenvz i guess 0.70 is auto linking so you dnt need to add manul linking try to undu all linking related to library and than intall and cd ios / pod install

**Comment by Rubeenvz** [comment]
Thanks @ahaseeb001 It is working now.

I just did: 

1.- yarn add @react-native-camera-roll/camera-roll
2.- npx pod-install (or cd ios && pod install)
3.- I added the NSPhotoLibraryAddUsageDescription key and its string

I also installed [react-native-permissions ](https://github.com/zoontek/react-native-permissions) :D

**Comment by ahaseeb001** [comment]
@Rubeenvz happy coding 🥰

**Comment by cheeka13** [comment]
got it today. how to fix?
