### ISSUE TITLE
Dont know how to install react-native-cameraroll

### ISSUE THREAD

**Issue by ajnesm** [react-native-cameraroll/react-native-cameraroll#458]
Hi guys,
I really need ur help. Ich have my expo react native app and I would love to install this package.
I start the expo app in visual studio code and tried to install ist but I just can't get it done.
Can you tell me what I need Xcode for? Can I even install it without Xcode? I never really worked with Xcode

That you guys I would appreciate every litte help. I am really desperate.

Kind regards Anes

**Comment by harrigee** [comment]
For expo you need to use a custom development client: https://blog.expo.dev/introducing-custom-development-clients-5a2c79a9ddf8. 

In general the MediaLibrary from expo https://docs.expo.dev/versions/latest/sdk/media-library/ might be a good fit for you too. We just realized that reading the whole camera roll on android takes way longer with the MediaLibrary than with this package. So we decided to use this package for Android and the MediaLibrary for iOS. 

I hope this helped a bit.
