### ISSUE TITLE
Could not resolve project :@react-native-camera-roll_camera-roll

### ISSUE THREAD

**Issue by DamonPandm** [react-native-cameraroll/react-native-cameraroll#483]
Manually install according to documentation, it works on ios, but not works on android. 

`
* What went wrong:
Could not determine the dependencies of task ':app:compileDebugJavaWithJavac'.
> Could not resolve all task dependencies for configuration ':app:debugCompileClasspath'.
   > Could not resolve project :@react-native-camera-roll_camera-roll.
     Required by:
         project :app
      > No matching configuration of project :@react-native-camera-roll_camera-roll was found. The consumer was configured to find an API of a component, preferably optimized for Android, as well as attribute 'com.android.build.api.attributes.BuildTypeAttr' with value 'debug', attribute 'com.android.build.api.attributes.AgpVersionAttr' with value '7.1.1' but:
          - None of the consumable configurations have attributes.
`

react-native: "0.69.4"
"@react-native-camera-roll/camera-roll": "^5.3.1"

**Comment by masoomro16** [comment]
same issue
