### ISSUE TITLE
deletePhotos failure with proper uri

### ISSUE THREAD

**Issue by sekcan** [react-native-cameraroll/react-native-cameraroll#486]
Hi everyone.
I did my research but got no solution. Sorry if this is duplicate or has an obvious solution.

I'm trying to delete a photo from gallery. I'm getting URI's with CameraRoll.getPhotos(), then passing this URI to deletePhotos():

![image](https://user-images.githubusercontent.com/16785003/231712369-ca03da0a-20e9-4dea-96bc-cc1d7c2080d4.png)

The console.log above gives this: file:///storage/emulated/0/DCIM/Camera/IMG_20230409_154656.jpg
So I'm assuming the URI fullfills the expectation:
![image](https://user-images.githubusercontent.com/16785003/231712781-cd8c0a14-3eb2-45bc-bfe5-856b499e126d.png)

But unfortunately, I got this error on my device:
![WhatsApp Image 2023-04-13 at 12 14 53](https://user-images.githubusercontent.com/16785003/231713304-75141fab-49ed-492f-a929-1a0c9d56ef30.jpg)

I think I got the READ/WRITE permissions properly:
![image](https://user-images.githubusercontent.com/16785003/231713874-aaa4010c-dd19-4212-a914-02f7db3e081d.png)

And this console.log gives: {"android.permission.READ_EXTERNAL_STORAGE": "granted", "android.permission.WRITE_EXTERNAL_STORAGE": "granted"}

Any ideas?
Thanks in advance

**Comment by dawlatxai** [comment]
@sekcan I have the same issue while deleting photos. Did you find any solution or workaround?

**Comment by Arjan-Zuidema** [comment]
What Android version are you using? From Android 13 you need other permissions. See the bottom part about Android 13 of [this](https://github.com/react-native-cameraroll/react-native-cameraroll#permissions) section. Hope this helps

**Comment by Arjan-Zuidema** [comment]
Closing this due to lack of response, so I guess the problem is fixed. Feel free to reopen when it's still a problem

**Comment by danharrisondev** [comment]
@Arjan-Zuidema I'm also having this issue on Android SDK version 33 (Android 13).

**Comment by danharrisondev** [comment]
@zonist Did you fix the issue? If so can you write your solution here? Thanks.
