### ISSUE TITLE
TurboModuleRegistry

### ISSUE THREAD

**Issue by vikalinic** [react-native-cameraroll/react-native-cameraroll#496]
When running jest test i get: 
"Invariant Violation: TurboModuleRegistry.getEnforcing(...): 'RNCCameraRoll' could not be found. Verify that a module by this name is registered in the native binary"

EDIT:
Fixed with
`jest.mock('@react-native-camera-roll/camera-roll', () => ({
  getPhotos: jest.fn(),
  saveToCameraRoll: jest.fn()
}));`

**Comment by zatteo** [comment]
Thank you for your solution. You can also use 

```
import mockRNCameraRoll from '@react-native-camera-roll/camera-roll/src/__mocks__/nativeInterface'

jest.mock('@react-native-camera-roll/camera-roll', () => mockRNCameraRoll)
```

**Comment by Arjan-Zuidema** [comment]
Closing this as it's fixed
