### ISSUE TITLE
MIME type video/mp4 cannot be inserted

### ISSUE THREAD

**Issue by SHRASHRI08** [react-native-cameraroll/react-native-cameraroll#499]
MIME type video/mp4 cannot be inserted into content expected MIME type under image/*

Getting this error even after taking the latest update

**Comment by Arjan-Zuidema** [comment]
What function are you calling when this error occurs?

**Comment by SHRASHRI08** [comment]
await CameraRoll.save(outputVideoPath, 'video')
                  .then(() => {
                    Alert.alert(
                      'Download successful',
                      `${fileName} saved to gallery`,
                      [{
                        text: 'OK', onPress: () => insertVideo()
                      }],
                      { cancelable: false }
                    );
                  })

This is the function

**Comment by SHRASHRI08** [comment]
Extremely annoyed by this error, 
It only appears in android API Level >=30

**Comment by SHRASHRI08** [comment]
Any update on this ?

**Comment by MinhThu100200** [comment]
Any update ?

**Comment by Arjan-Zuidema** [comment]
Duplicate of #423
