### ISSUE TITLE
Unable to build Android app that uses this library and `react-native-webview`

### ISSUE THREAD

**Issue by evanwalsh** [react-native-cameraroll/react-native-cameraroll#506]
With v5.7.0, Android apps that use this library and `react-native-webview` cannot build due to a duplicate class error.

[Shouldn't this namespace](https://github.com/react-native-cameraroll/react-native-cameraroll/pull/505/commits/cdc6729da925d329f246bb2e63a02733f9ef20d2#diff-197b190e4a3512994d2cebed8aff5479ff88e136b8cc7a4b148ec9c3945bd65aR139) be `com.reactnativecommunity.cameraroll`?

The error seen on build is the following:

```
Type com.reactnativecommunity.webview.BuildConfig is defined multiple times: [SRC]/node_modules/@react-native-camera-roll/camera-roll/android/build/.transforms/2d1e59288a3d562c2f5d50d42cefe703/transformed/classes/classes.dex, [SRC]/node_modules/react-native-webview/android/build/.transforms/7fdaa75708060e982f026ee0f7088828/transformed/classes/classes.dex
```

**Comment by lpfrenette** [comment]
Yes you're right.

With [patch-package](https://www.npmjs.com/package/patch-package) install add the following file to your patches/ folder

you can also add 
``` 
"postinstall": "patch-package",
```
to package.json

@react-native-camera-roll+camera-roll+5.7.0.patch
```diff --git a/node_modules/@react-native-camera-roll/camera-roll/android/build.gradle b/node_modules/@react-native-camera-roll/camera-roll/android/build.gradle
index 3325454..a2ca303 100644
--- a/node_modules/@react-native-camera-roll/camera-roll/android/build.gradle
+++ b/node_modules/@react-native-camera-roll/camera-roll/android/build.gradle
@@ -136,7 +136,7 @@ manifestOutFile.write(manifestContent)

 android {
   if(shouldUseNameSpace){
-    namespace = "com.reactnativecommunity.webview"
+    namespace = "com.reactnativecommunity.cameraroll"
   }
   compileSdkVersion getExtOrIntegerDefault('compileSdkVersion')

```

**Comment by Arjan-Zuidema** [comment]
Whoops. Thats why you should never coup paste 😅

Will fix this tomorrow 🙂 or if you van make a pr i can merge it

**Comment by lpfrenette** [comment]
> Whoops. Thats why you should never copy paste 😅
> 
> Will fix this tomorrow 🙂 or if you van make a pr i can merge it

Just created the pull request https://github.com/react-native-cameraroll/react-native-cameraroll/pull/507
