### ISSUE TITLE
IOS: Trimmed videos with Photos app on iPhone

### ISSUE THREAD

**Issue by MilanC994** [react-native-cameraroll/react-native-cameraroll#510]
I use Photos app on IOS to trim my video  (iPhone 13). I use Camera roll like this:

`const assets = await CameraRoll.getPhotos({
        first: 100,
        assetType: assetType || 'Photos',
        include: ['playableDuration']
      });`
      
My original video is 51 sec long, but I trim it to 19 (change start time and end time). Playable duration returns 19 sec, and that's okay. However, when I pass the url to rn-video and play it, it plays full video, also, when I upload the video (rn background upload, axios or node fetch) it uploads full video version.

**Comment by vforvasile** [comment]
I think iOS never actually cuts the video, they rather keep the original and show you a preview of the trim you made.

Would be a nice feature to access the trim output though.

**Comment by MilanC994** [comment]
I think that too, but I need a way to access the trimmed video.

**Comment by Arjan-Zuidema** [comment]
I guess there is a way to access the trimmed version as other apps also do that. But I am not very familiar with the iOS sdk.

**Comment by vforvasile** [comment]
I ran a test on iPhone 13 Pro Max, iOS 16.2


After calling: 
`CameraRoll.iosGetImageDataById(ph://...);`
on the original video and the trim (I chose not to save **as new clip** but just to save my settings)
this is what I got from `photo.node.image.filepath`


Original Video path:
`file:///Users/sparky/Library/Developer/CoreSimulator/Devices/C2148AC2-BC19-4510-9746-E896D8B8E48C/data/Media/DCIM/100APPLE/IMG_0090.MP4`


<img width="411" alt="Screenshot 2023-07-10 at 12 31 38" src="https://github.com/react-native-cameraroll/react-native-cameraroll/assets/9382283/ffa6667f-1795-48e8-92a1-c4c1aa30468c">

![Screenshot 2023-07-10 at 12 28 31](https://github.com/react-native-cameraroll/react-native-cameraroll/assets/9382283/03f9fb8f-7a0f-45b2-aac4-f5d5565c5107)



Trimmed, cropped and enhanced video path:

`file:///Users/sparky/Library/Developer/CoreSimulator/Devices/C2148AC2-BC19-4510-9746-E896D8B8E48C/data/Media/PhotoData/Mutations/DCIM/100APPLE/IMG_0090/Adjustments/FullSizeRender.mov`


<img width="441" alt="Screenshot 2023-07-10 at 12 26 55" src="https://github.com/react-native-cameraroll/react-native-cameraroll/assets/9382283/6b80aefd-98c3-4c1a-b68b-84639055b717">

![Screenshot 2023-07-10 at 12 27 37](https://github.com/react-native-cameraroll/react-native-cameraroll/assets/9382283/e770782c-cb47-4048-92f1-33a26ca66ec3)


And if you pass the trimmed `photo.node.image.filepath` in rn-video, the duration is ok, video is trimmed/cropped

Soo, I guess it works with `CameraRoll.iosGetImageDataById`?
