### ISSUE TITLE
[iOS]Error: The operation couldn’t be completed. (PHPhotosErrorDomain error 3302.)

### ISSUE THREAD

**Issue by DamonPandm** [react-native-cameraroll/react-native-cameraroll#515]
I'm currently using this library to download image from URL.
The vast majority images works fine, but some images got error like this:
#### Error: The operation couldn’t be completed. (PHPhotosErrorDomain error 3302.)

I wrote code like this
```
const uri = 'https://gooles.oss-cn-hongkong.aliyuncs.com/1/gooles/2023/07/21/08f1b9a1f1c8406fb64f46472f993332.jpeg'
await CameraRoll.save(uri, { type: 'photo', album: 'Test' })
```

Here's my version information.

"react-native": "0.69.4",
"@react-native-camera-roll/camera-roll": "^5.3.1",

**Comment by Arjan-Zuidema** [comment]
Try downloading the file to disk before adding it to the camera roll.

**Comment by DamonPandm** [comment]
> Try downloading the file to disk before adding it to the camera roll.

I tried doing this before, but it didn't work

```
const save = async (uri: string) => {
  let dirs = Platform.OS === 'ios' ? RNFS.LibraryDirectoryPath : RNFS.ExternalDirectoryPath
  let fileName = `test-${Math.floor(Math.random() * 10000)}${new Date().getTime()}.png`
  // filePath
  let downloadDest = `${dirs}/${fileName}`
  const ret = RNFS.downloadFile({ fromUrl: uri, toFile: downloadDest })
  const res = await ret.promise
  if (res.statusCode === 200) {
    try {
      await CameraRoll.save('file://' + downloadDest, { type: 'photo', album: 'test' })
    } catch (e) {
      console.log(e)
    }
  }
}
```

**Comment by Arjan-Zuidema** [comment]
Can you try downloading it to a temp directory?

**Comment by DamonPandm** [comment]
Sorry, I tried, but it didn't work. Could you help to try this link like 'https://gooles.oss-cn-hongkong.aliyuncs.com/1/gooles/2023/07/21/08f1b9a1f1c8406fb64f46472f993332.jpeg'?

**Comment by Arjan-Zuidema** [comment]
Can you create a minimal reproducible repro? I don't have much time to debug

**Comment by AntonyARHS** [comment]
Hello, 

I've the same error but for MP4 file. 

I'm downloading the video with ReactNativeBlobUtil and then trying to save it using this lib. I'm using the same process than the one used for picture (just defining "video" type instead of "photo"). 

Could you explain exactly what are the triggers of this 3302 error plz?

**Comment by eman747** [comment]
use  const result = await CameraRoll.iosGetImageDataById(
              e.node.image.uri,
            ); now result will give you filename and that you can use with react-native-video to render

**Comment by hussnainshafiul** [comment]
I am still having this error, The operation couldn’t be completed. (PHPhotosErrorDomain error 3302.)

I am first downloading the video (mp4) using rnfetchblob in DocumentDirectory, and then save it using CameraRoll.save
but it gives error on ios (which is working perfectly fine on android)

**Comment by Dung1128** [comment]
> I am still having this error, The operation couldn’t be completed. (PHPhotosErrorDomain error 3302.)
> 
> I am first downloading the video (mp4) using rnfetchblob in DocumentDirectory, and then save it using CameraRoll.save but it gives error on ios (which is working perfectly fine on android)

I have the same issue
