### ISSUE TITLE
The package only works in release mode and not in debug

### ISSUE THREAD

**Issue by simran7575** [react-native-cameraroll/react-native-cameraroll#516]
invariant violation: turbomoduleregistery.getenforcing(..): "rnccameraroll" could not be found. verify that a module by this name is registered in the native binary. This is what I get when I try to run it in debug mode on my device.

**Comment by Arjan-Zuidema** [comment]
Can you provide some more info? What versions you are using? Are you using fabric?

**Comment by simran7575** [comment]
Till yesterday I was working on version 5.7.2 and it was working fine but
today if I try to create a build it is crashing and getting error that Could
not resolve project ***@***.***_camera-roll.

Please help on this. It is very urgent

**Comment by Arjan-Zuidema** [comment]
If it was working before then it should not be a problem with this package but with your workflow. Provide me with more details and maybe I can take a look.

**Comment by simran7575** [comment]
In debug mode I am getting this error. I have installed the package and just imported it  -> import {CameraRoll} from '@react-native-camera-roll/camera-roll'

![WhatsApp Image 2023-07-26 at 17 54 53](https://github.com/react-native-cameraroll/react-native-cameraroll/assets/70148135/cc05e32e-db72-4ff3-a544-d6b4b00cc59b)

**Comment by Arjan-Zuidema** [comment]
Please tell me what versions you are using:
- Android
- React-native

Are you using fabric?

**Comment by simran7575** [comment]
Android: 13
React-native- 0.61.3

No , not using fabric

**Comment by Arjan-Zuidema** [comment]
Please update react-native version to at least version 69. All other package are deprecated:
https://www.npmjs.com/package/react-native?activeTab=versions
