### ISSUE TITLE
Build Failed with Exception on React Native 0.72.3

### ISSUE THREAD

**Issue by ElSierra** [react-native-cameraroll/react-native-cameraroll#519]
Task :react-native-camera-roll_camera-roll:packageDebugResources FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Some problems were found with the configuration of task ':react-native-camera-roll_camera-roll:packageDebugResources' (type 'MergeResources').
  - Gradle detected a problem with the following location: 'E:\my-app\node_modules\@react-native-camera-roll\camera-roll\android\build\generated\res\rs\debug'.

    Reason: Task ':react-native-camera-roll_camera-roll:packageDebugResources' uses this output of task ':@react-native-camera-roll_camera-roll:compileDebugRenderscript' without declaring an explicit or implicit dependency. This can lead to incorrect results being produced, depending on what order the tasks are executed.        

    Possible solutions:
      1. Declare task ':@react-native-camera-roll_camera-roll:compileDebugRenderscript' as an input of ':react-native-camera-roll_camera-roll:packageDebugResources'.
      2. Declare an explicit dependency on ':@react-native-camera-roll_camera-roll:compileDebugRenderscript' from ':react-native-camera-roll_camera-roll:packageDebugResources' using Task#dependsOn.
      3. Declare an explicit dependency on ':@react-native-camera-roll_camera-roll:compileDebugRenderscript' from ':react-native-camera-roll_camera-roll:packageDebugResources' using Task#mustRunAfter.

    Please refer to https://docs.gradle.org/8.0.1/userguide/validation_problems.html#implicit_dependency for more details about this problem.
  - Gradle detected a problem with the following location: 'E:\Desktop\Projects\social-app - Copy\node_modules\@react-native-camera-roll\camera-roll\android\build\generated\res\resValues\debug'.

    Reason: Task ':react-native-camera-roll_camera-roll:packageDebugResources' uses this output of task ':@react-native-camera-roll_camera-roll:generateDebugResValues' without declaring an explicit or implicit dependency. This can lead to incorrect results being produced, depending on what order the tasks are executed.

    Possible solutions:
      1. Declare task ':@react-native-camera-roll_camera-roll:generateDebugResValues' as an input of ':react-native-camera-roll_camera-roll:packageDebugResources'.  
      2. Declare an explicit dependency on ':@react-native-camera-roll_camera-roll:generateDebugResValues' from ':react-native-camera-roll_camera-roll:packageDebugResources' using Task#dependsOn.
      3. Declare an explicit dependency on ':@react-native-camera-roll_camera-roll:generateDebugResValues' from ':react-native-camera-roll_camera-roll:packageDebugResources' using Task#mustRunAfter.

**Comment by minhna** [comment]
I have the same problem

**Comment by ElSierra** [comment]
> I have the same problem

I ended just using the package without all the changes to Gradle file and Android build and it worked, Try removing all configuration and using it like any other package.

**Comment by minhna** [comment]
> > I have the same problem
> 
> I ended just using the package without all the changes to Gradle file and Android build and it worked, Try removing all configuration and using it like any other package.

WOW, I removed configurations from `android/settings.gradle` and `android/app/build.gradle` and the build pass (but I'm having other error, I'm upgrading my app to 0.72.3).
Does your app works as expected?

**Comment by ElSierra** [comment]
Everything works as expected for me

**Comment by SayisMe** [comment]
I had the same problem, and it was solved thanks to you. 👍🏻 
Build works well, but I encountered a new problem as shown in the image below.

<img width="362" alt="image" src="https://github.com/react-native-cameraroll/react-native-cameraroll/assets/46295659/00b27e15-88c7-4b5c-953f-32c3d585fa78">

I just removed `new CameraRollPackage()` from `android/app/src/main/java/[...]/MainApplication.java` > **getPackages()**.
So Everything works as expected
