### ISSUE TITLE
Error when 'yarn android' : Could not get unknown property 'com' for project ':@react-native-camera-roll_camera-roll' of type org.gradle.api.Project.

### ISSUE THREAD

**Issue by marcell6** [react-native-cameraroll/react-native-cameraroll#521]
Help, I'm doing new install on v5.0.2.

Previously, I used the @react-native-community/cameraroll package. because it was deprecated, so I moved to use @react-native-cameraroll/react-native-cameraroll v5.0.2.
And when I did 'yarn android', an error message appeared "Could not get unknown property 'com' for project ':@react-native-camera-roll_camera-roll' of type org.gradle.api.Project."

note: I have done react-native link

<img width="564" alt="image" src="https://github.com/react-native-cameraroll/react-native-cameraroll/assets/137249826/deb4818f-3d03-4131-a91b-7b1bcd189f15">

React Native v0.61.5
Thank you

**Comment by Arjan-Zuidema** [comment]
You should not need to use react-native link. The library works fine with automatic installation. Can you try to remove the library and reinstall it completely?

**Comment by abhinav-official** [comment]
getting same error when trying to install on REACT NATIVE 0.63.5
