### ISSUE TITLE
android deletePhotos

### ISSUE THREAD

**Issue by athaljen** [react-native-cameraroll/react-native-cameraroll#535]
android delete photo not working .
throw error has no access to content: //media/external/images/media...
![1694522655703](https://github.com/react-native-cameraroll/react-native-cameraroll/assets/144444939/65aaa635-d68d-47ee-a116-33a6a4e9508b)

**Comment by Arjan-Zuidema** [comment]
Did you implement asking for [permissions](https://github.com/react-native-cameraroll/react-native-cameraroll#permissions)?

**Comment by athaljen** [comment]
> Did you implement asking for [permissions](https://github.com/react-native-cameraroll/react-native-cameraroll#permissions)?

yes these [permissions](https://github.com/react-native-cameraroll/react-native-cameraroll#permissions), i have all-ready added them, but they don't work on android 11 & above. then it worked for android 11 & above. 
so i added the MANAGE_EXTERNAL_STORAGE permission externally by native modules. Now its working.

**Comment by lluisandreu** [comment]
@athaljen did you publish your app to Google Play? I had the same problem and installed this package https://www.npmjs.com/package/react-native-manage-external-storage but Google doesn't like the idea of accessing all files and rejected my app.
