### ISSUE TITLE
Subscribe to change event for add, delete, edit of photos/videos.

### ISSUE THREAD

**Issue by jp-23** [react-native-cameraroll/react-native-cameraroll#537]
How do we subscribe to changes to photos - i.e. when the user adds, deletes, or edits a photo - is there an event we can subscribe to so that we can update the list of photos currently loaded in the app to reflect these changes?

**Comment by Arjan-Zuidema** [comment]
Currently there is not such thing. I think you can check use `AppState` (from react-native) to check when the app goes from background to foreground. And then update the camera roll
