### ISSUE TITLE
Build input file cannot be found : RNCCameraRollManager.m, RNCCameraRollPermissionModule.m

### ISSUE THREAD

**Issue by SayisMe** [react-native-cameraroll/react-native-cameraroll#543]
I just tried this

`$ npm install @react-native-camera-roll/camera-roll --save`

#### iOS

1. In XCode, in the project navigator, right click `Libraries` ➜ `Add Files to [your project's name]`
2. Go to `node_modules` ➜ `@react-native-camera-roll/camera-roll` and add `RNCCameraroll.xcodeproj`
3. In XCode, in the project navigator, select your project. Add `libRNCCameraroll.a` to your project's `Build Phases` ➜ `Link Binary With Libraries`
4. Run your project (`Cmd+R`)<

But I got this build error messages

> /Users/say/Documents/GitHub/SWM/forked/App_Template/node_modules/@react-native-camera-roll/camera-roll/ios/RNCCameraRollManager.m Build input file cannot be found: '/Users/say/Documents/GitHub/SWM/forked/App_Template/node_modules/@react-native-camera-roll/camera-roll/ios/RNCCameraRollManager.m'. Did you forget to declare this file as an output of a script phase or custom build rule which produces it?

<img width="731" alt="image" src="https://github.com/react-native-cameraroll/react-native-cameraroll/assets/46295659/fa9fbc82-f809-4f7b-ac3e-0c10cf4b0fcd">

Any solution about this?

**Comment by Arjan-Zuidema** [comment]
Why are you not using automatic install? That should work. Manual installation is only needed for older RN versions

**Comment by SayisMe** [comment]
Thanks to @Arjan-Zuidema , it worked out well!
Closing this issue.

**Comment by christian-hess-94** [comment]
How to run react-native link with npx? I do not have the cli installed as per the latest recommendation from react-native installation docs. The link command does not exist anymore when running react-native cli with npx

**Comment by Arjan-Zuidema** [comment]
@christian-hess-94  Linking should not be needed. React native takes care of linking using [auto linking](https://reactnative.dev/docs/linking-libraries-ios#automatic-linking)
