### ISSUE TITLE
Encountered the following error

### ISSUE THREAD

**Issue by majiabin** [react-native-cameraroll/react-native-cameraroll#546]
react-native:0.70.5
npm install @react-native-camera-roll/camera-roll

FAILURE: Build failed with an exception.

* Where:
Script 'E:\Demo\ZDLD\node_modules\@react-native-community\cli-platform-android\native_modules.gradle' line: 450

* What went wrong:
A problem occurred evaluating script.
> Calling `[node, E:\Demo\ZDLD\node_modules\react-native\node_modules\@react-native-community\cli\build\bin.js, config]` finished with an exception. Error message: groovy.json.JsonException: Unable to determine the current character, it is not a string, number, array, or object
  
  The current character read is 'i' with an int value of 105
  Unable to determine the current character, it is not a string, number, array, or object
  line number 1
  index number 0
  info Run CLI with --verbose flag for more details.
  ^. Output: info Run CLI with --verbose flag for more details.

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 8s

**Comment by majiabin** [comment]
{
  "name": "ZDLD",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "android": "react-native run-android",
    "ios": "react-native run-ios",
    "start": "react-native start",
    "test": "jest",
    "lint": "eslint ."
  },
  "dependencies": {
    "@react-native-async-storage/async-storage": "^1.17.10",
    "@react-native-camera-roll/camera-roll": "^6.0.0",
    "@react-native-community/datetimepicker": "^6.5.5",
    "@react-native-community/progress-bar-android": "^1.0.5",
    "@react-navigation/bottom-tabs": "^6.4.0",
    "@react-navigation/material-bottom-tabs": "^6.2.4",
    "@react-navigation/material-top-tabs": "^6.3.0",
    "@react-navigation/native": "^6.0.13",
    "@react-navigation/native-stack": "^6.9.1",
    "axios": "0.19.0",
    "deprecated-react-native-prop-types": "^2.3.0",
    "react": "18.1.0",
    "react-native": "0.70.5",
    "react-native-background-timer": "^2.4.1",
    "react-native-circular-progress": "^1.3.7",
    "react-native-device-info": "^10.3.0",
    "react-native-dropdownalert": "^4.5.1",
    "react-native-fs": "^2.20.0",
    "react-native-image-crop-picker": "^0.38.1",
    "react-native-image-zoom-viewer": "^3.0.1",
    "react-native-loading-spinner-overlay": "^3.0.1",
    "react-native-modal": "13.0.1",
    "react-native-modal-datetime-picker": "^14.0.0",
    "react-native-modal-selector": "^2.1.2",
    "react-native-pager-view": "^6.1.0",
    "react-native-paper": "^4.12.5",
    "react-native-safe-area-context": "^4.4.1",
    "react-native-screens": "^3.18.2",
    "react-native-sound": "^0.11.2",
    "react-native-svg": "^13.6.0",
    "react-native-tab-view": "^3.3.0",
    "react-native-vector-icons": "^9.2.0",
    "react-native-vision-camera": "^2.15.2",
    "react-native-watermark-component": "^0.1.0",
    "react-native-webview": "^11.23.1",
    "rn-fetch-blob": "^0.12.0"
  },
  "devDependencies": {
    "@babel/core": "^7.12.9",
    "@babel/runtime": "^7.12.5",
    "@react-native-community/eslint-config": "^2.0.0",
    "babel-jest": "^26.6.3",
    "eslint": "^7.32.0",
    "jest": "^26.6.3",
    "metro-react-native-babel-preset": "0.72.3",
    "react-test-renderer": "18.1.0"
  },
  "jest": {
    "preset": "react-native"
  }
}

**Comment by interstates21** [comment]
I have the same issue
