### ISSUE TITLE
Build issue on 6.0.1 - Cannot compare java.lang.String with value 

### ISSUE THREAD

**Issue by apamphilon** [react-native-cameraroll/react-native-cameraroll#554]
* What went wrong:
A problem occurred evaluating project ':react-native-camera-roll_camera-roll'.
> Cannot compare java.lang.String with value '0.72.6' and java.lang.Integer with value '71'

**Comment by apamphilon** [comment]
I believe this might be an issue on my end

**Comment by Arjan-Zuidema** [comment]
> I believe this might be an issue on my end

@apamphilon if not, just re-open. Was just about to investigate 🙂

**Comment by apamphilon** [comment]
@Arjan-Zuidema I believe on further investigation, it might actually be an issue with the package, so I've re-opened 👍

**Comment by chenweigh** [comment]
same problem +1

**Comment by Arjan-Zuidema** [comment]
@apamphilon i see the problem, working on a fix.

**Comment by Arjan-Zuidema** [comment]
> BUILD SUCCESSFUL in 1m 12s

Pushing out a new build now

**Comment by Arjan-Zuidema** [comment]
Fixed in [v6.0.2](https://github.com/react-native-cameraroll/react-native-cameraroll/releases/tag/v6.0.2)

**Comment by apamphilon** [comment]
@Arjan-Zuidema  - Thanks, I can confirm that my app now builds 👍.
