### ISSUE TITLE
`getPhotos` returns only photos, no videos, when `assetType` is set to `'All'`

### ISSUE THREAD

**Issue by itsabk** [react-native-cameraroll/react-native-cameraroll#556]
## Environment
- React Native version: 0.70.5
- `@react-native-community/cameraroll` version: ^5.2.4
- Platform: Android
- Device: Poco F3
- OS version: Android 13

## Description
When using `CameraRoll.getPhotos` with `assetType` set to `'All'`, the response only includes photos and does not include videos.

Here's the code snippet:

```javascript
const fetchPhotos = useCallback((type: string) => {
  const assetType = "All";
  Promise.all([
    CameraRoll.getPhotos({ first: 200, assetType }),
    CameraRoll.getAlbums({ assetType: "All" }),
  ])
  .then(([photosResponse, albumsResponse]) => {
    setPhotos(photosResponse.edges);
    // Albums response is not currently used
  })
  .catch((err) => console.error("*_CameraRoll Fetch", err));
}, []);
```

## Expected Behavior
When `assetType` is set to `'All'`, both photos and videos should be returned in the `photosResponse`.

## Actual Behavior
Only photos are being returned, and videos are not included in the response.

Has anyone else encountered this issue, or am I missing something in my implementation?

**Comment by phamthang03** [comment]
in my case, assetType = 'Photos' will return both photo and video :]

**Comment by lucianobracco-geojam** [comment]
It's still happening to me. I did update to latest version v7.3.0 (on Android 13)

**Comment by AgussDominguez** [comment]
Same issue here, any solution?
