### ISSUE TITLE
getPhotos() method returns data even after delete video from file manager

### ISSUE THREAD

**Issue by c-info** [react-native-cameraroll/react-native-cameraroll#558]
Platform: Android
OS: 12.5.1 MI Global
Brand: MI 
Issue: when user remove video from particular album still getting video path on getPhotos method

sample code 
```
const camData = await CameraRoll.getPhotos({
        assetType: 'Videos',
        groupName: 'My-Recording',
        first: 100,
        groupTypes: 'Album',
      });
```

above code returns data even if My-Recording don't have any records

**Comment by Arjan-Zuidema** [comment]
Probably because the video is still on the device, in an other album? Have you tested any other devices or simulators?
