### ISSUE TITLE
While saving a base64 image in IOS 15 and 16 -> error [Error: The operation couldn’t be completed. (PHPhotosErrorDomain error 3303.)]

### ISSUE THREAD

**Issue by EducoreAPK** [react-native-cameraroll/react-native-cameraroll#560]
When i am trying to save a base64 format image in IOS 15 and 16, in 17 it is working fine.
Before it was working fine i recently updated my react and all other libraries. 

Now I am getting this error 
[Error: The operation couldn’t be completed. (PHPhotosErrorDomain error 3303.)]
when i try to call 

  ```
dPath = (Platform.OS === 'android') ? 'file://' + dPath : dPath
  CameraRoll.save(dPath, { album: 'EducoreParent' }).then((res) => {
```
dPath is base64 of a image

i am using 
    "@react-native-camera-roll/camera-roll": "^6.0.2",
    "react": "18.2.0",
    "react-native": "0.72.6",

**Comment by Arjan-Zuidema** [comment]
Have you checked the README.md section about the [permissions](https://github.com/react-native-cameraroll/react-native-cameraroll#permissions)?
