### ISSUE TITLE
add metadata to the image

### ISSUE THREAD

**Issue by EzzineSmichi** [react-native-cameraroll/react-native-cameraroll#561]
Is there any way to add metadata, such as location (i have the location : using @react-native-community/geolocation), to the image before it is saved in the gallery using this package?

**Comment by Arjan-Zuidema** [comment]
No, current there is no way to add metadata to media files. Also I think that is outside of the scope of this package.

**Comment by kueda** [comment]
FWIW, I don't think actually embedding EXIF data in an image binary is in-scope for this package, but I think writing metadata common to both iOS and Android is in scope. For example, the iOS `PHAssetChangeRequest` will accept a [location](https://developer.apple.com/documentation/photokit/phassetchangerequest/1624048-location) attribute containing coordinates, and the Android `MediaStore.Images` provider at least has [latitude](https://developer.android.com/reference/kotlin/android/provider/MediaStore.Images.ImageColumns?hl=en#LATITUDE:kotlin.String) and longitude columns (not sure if they're writeable). If we *can* write those attributes for new images for both iOS and Android, that seems in-scope and a useful feature for this library. `CameraRoll.save( imageUri, { location: { latitude: 1, longitude: 1 } )` would be awesome.
