### ISSUE TITLE
Crash ios when call "CameraRoll.getPhotoThumbnail(uri, options)"

### ISSUE THREAD

**Issue by R0LLeX** [react-native-cameraroll/react-native-cameraroll#564]
I use such a component to implement the functionality for obtaining miniature images on ios, everything works fine on the simulator, however, if I run on a real device, then when I enter the screen where I request media files, after the request
"const thumbnailResponse = await CameraRoll.getPhotoThumbnail(url, options)"
thumbnails are shown for a second, and then the app crashes

Versions :
Device: iPhone
OS: iOS 16.1.1
Xcode version = Xcode 14.2
React Native Version = 0.71.3

  OS: macOS 12.5
  Binaries:
    Node: 18.10.0 - ~/.nvm/versions/node/v18.10.0/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 8.19.2 - ~/.nvm/versions/node/v18.10.0/bin/npm
    Watchman: 2023.04.03.00 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.13.0 - /Users/us/.rbenv/shims/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 22.2, iOS 16.2, macOS 13.1, tvOS 16.1, watchOS 9.1
    Android SDK: Not Found
  IDEs:
    Android Studio: 2022.2 AI-222.4459.24.2221.9862592
    Xcode: 14.2/14C18 - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.16.1 - /usr/bin/javac
  npmPackages:
    react: 18.2.0 => 18.2.0
    react-native: 0.71.3 => 0.71.3

Uploading 2023-11-30 11.36.18.mp4…

export const ThumbnailImage = ({ uri, extension }: ThumbnailType) => {
  const [base64Image, setBase64Image] = useState("");

  useEffect(() => {
    if (!uri) {
      return;
    }

    const getThumbnail = async () => {
      const options = {
        allowNetworkAccess: true,
        targetSize: {
          height: 80,
          width: 80,
        },
        quality: 1.0,
      };

      if (!isIos) {
        return;
      }
      try {
        const thumbnailResponse = await CameraRoll.getPhotoThumbnail(uri, options);
        setBase64Image(thumbnailResponse.thumbnailBase64);
      } catch (e) {
        console.log("e", e);
      }
    };

    getThumbnail().then();
  }, [uri]);

  let prefix;

  switch (extension) {
    case "png":
      prefix = "data:image/png;base64,";
      break;
    default:
      prefix = "data:image/jpeg;base64,";
      break;
  }

  return <Image source={{ uri: isIos ? `${prefix}${base64Image}` : uri }} style={styles.GalleryImage} />;
};

**Comment by R0LLeX** [comment]
Uploading 2023-11-30 11.36.18.mp4…

**Comment by R0LLeX** [comment]
https://github.com/react-native-cameraroll/react-native-cameraroll/assets/95383638/cf6988c2-e2c6-4e08-86bc-cf2cb0100f80

**Comment by Arjan-Zuidema** [comment]
Hi @R0LLeX can you create a minimal repo so we can reproduce the issue?

**Comment by R0LLeX** [comment]
https://github.com/tpetrew/TestImagesBase

the problem occurs if you request many photos at the same time

**Comment by branchbyte** [comment]
@R0LLeX i've tried this with a page size of 250, and cannot reproduce the error.

I have not tried your repo yet.

When you say this happens with many photos - what do you consider many?  As I've mentioned above, I've tried with a page size of 250, and do not get an error, although with that large of a page size the performance is degraded, which pagination helps with - get small chunks at a time for better performance.  I don't see pagination logic in your example repo - have you tried that?

**Comment by jp-23** [comment]
@R0LLeX i've tried this with a page size of 250, and cannot reproduce the error.

I have not tried your repo yet.

When you say this happens with many photos - what do you consider many? As I've mentioned above, I've tried with a page size of 250, and do not get an error, although with that large of a page size the performance is degraded, which pagination helps with - get small chunks at a time for better performance. I don't see pagination logic in your example repo - have you tried that?

**Comment by alainburindi** [comment]
I am having the same issue with just 5 photos. Using an iPhone 11

**Comment by alainburindi** [comment]
Having the same issue. I am building a custom image picker, which means I have to request hundreds of thubmnails depending on how fast the user scrolls

**Comment by R0LLeX** [comment]
The crash only happens on a real ios device, namely iphone 11 (ios 16.6.1), even when I request only 20 photos.
I repeat, everything works without problems on the ios simulator
