### ISSUE TITLE
Camera roll package not found while upgraded to 0.68.5

### ISSUE THREAD

**Issue by profaddy** [react-native-cameraroll/react-native-cameraroll#565]
Versions :
Device: android
android studio version =  Android Studio Chipmunk | 2021.2.1 Patch 1  and Giraffe
React Native Version = 0.68.5
Mac OS - 13.4 
@react-native-camera-roll/camera-roll: `5.7.2`, `5.10.0`

Issue
While upgrading to React Native version 0.68.5 , camera roll package started giving issue saying package was not found, even when package is there. Attaching screenshots for reference.

![Screenshot 2023-11-30 at 1 44 14 PM](https://github.com/react-native-cameraroll/react-native-cameraroll/assets/22865264/61fb3a98-eb9e-433b-896b-4c5c62c3519f)

![Screenshot 2023-11-30 at 1 44 54 PM](https://github.com/react-native-cameraroll/react-native-cameraroll/assets/22865264/b933eecc-15f3-4b8c-881a-9f242c042e2d)

**Comment by Arjan-Zuidema** [comment]
Try removing all references to the package and reinstall again using automatic install, that should work. Also, React native 0.68 is very old, try using the latest version

**Comment by profaddy** [comment]
Tried doing the fresh install, still facing same issue, upgrading to the latest RN version is not possible now as it may break other dependencies.

**Comment by profaddy** [comment]
Also you can have look at modules, multiple modules are there and in packagelist unable to import cameraRoll package.


<img width="1641" alt="Screenshot 2023-11-30 at 2 54 32 PM" src="https://github.com/react-native-cameraroll/react-native-cameraroll/assets/22865264/1d9dcd33-56e1-4d23-9795-fcd27af4f447">

**Comment by yuan9090** [comment]
camera-roll version needs to upgrade then 6.0.2 to fix `undfined.CameraRollPackage`

**Comment by Arjan-Zuidema** [comment]
@profaddy try the latest version
