### ISSUE TITLE
feature request: Return full `PhotoIdentifier` in `save()` 

### ISSUE THREAD

**Issue by mrousavy** [react-native-cameraroll/react-native-cameraroll#568]
Hey all!

Thanks for this amazing package, RN CameraRoll is great!

I was wondering if it'd be possible for RN CameraRoll to return the full `PhotoIdentifier` information instead of just the URI on `save()`, as this is quite relevant in my case since I immediately display images after capturing them.

I'd love to help with implementation if needed!

Thanks!

**Comment by Arjan-Zuidema** [comment]
Hi @mrousavy!
That sounds like a functional feature. I'd be willing to accept a pull request if you have the time to create it. Currently I don't have much time to create a feature

**Comment by mrousavy** [comment]
Awesome, working on it as we speak!

**Comment by mrousavy** [comment]
PR up: https://github.com/react-native-cameraroll/react-native-cameraroll/pull/569

**Comment by bobbyecho** [comment]
up up up, i need this feature so much 🙏
