### ISSUE TITLE
Is it really needed to link the package manually?

### ISSUE THREAD

**Issue by slavko-lukic** [react-native-cameraroll/react-native-cameraroll#570]
![Screenshot 2023-12-15 at 14 28 44](https://github.com/react-native-cameraroll/react-native-cameraroll/assets/87854709/ad0f7944-62a5-417d-935d-e8c2448c85fb)

It's not really clear from the docs if it should be linked manually.

**Comment by Arjan-Zuidema** [comment]
Linking should not be needed, I guess we need to update the docs
