### ISSUE TITLE
iOS: Incorrect suffixes result in the failure of saving webp format images.

### ISSUE THREAD

**Issue by Lunziyuan** [react-native-cameraroll/react-native-cameraroll#571]
The content of the following two URLs represents the same webp image. URLs with the "webp" suffix can be successfully saved, while those with the "png" suffix will result in an error: "Error: The operation couldn’t be completed. (PHPhotosErrorDomain error 3302.)"

https://dcdn.microstore.app/MSH5_eaabbe168b7889c04c08727c7ced740c.webp
https://dcdn.microstore.app/MSH5_ddee994de208867ae6cdb03bbe4e4522.png

**Comment by Arjan-Zuidema** [comment]
![image](https://github.com/react-native-cameraroll/react-native-cameraroll/assets/30040390/1f4eddb8-5370-4642-af91-147e74fd9dc2)

Both files are wepb. So the png one has the wrong extension. That why it fails.
Also `PHPhotosErrorDomain error 3302` means `Asset resource validation failed`
