### ISSUE TITLE
Execution failed for task ':react-native-camera-roll_camera-roll:compileDebugJavaWithJavac'

### ISSUE THREAD

**Issue by Yngesh-Raman-au6** [react-native-cameraroll/react-native-cameraroll#582]
Everything was working fine, I just installed one package, it was react-native-background-upload, this new package was not supported in my project so i decided to remove it. After that I tried starting my project and it keeps failing with this error: **Execution failed for task ':react-native-camera-roll_camera-roll:compileDebugJavaWithJavac'**.

Looked for this issue solution, but couldnt find the solution to this exact package, there was a solution for react-native-camera package, in which the suggestion was to match the minSdkVersion with my build.gradle file. That didnt work either.

I tried completely removing nodemodules, lock files, build files and then run, still fails with this error and project doesnt start.
Any help or info is appreciated. Thanks.

**Comment by Arjan-Zuidema** [comment]
Looks like a caching issue. Try cleaning the git repo: `git clean -fdX`. You can also try to clear the gradle cache

**Comment by DeveloperMCD** [comment]
I'm having the same issue!

**Comment by Yngesh-Raman-au6** [comment]
I fixed it, by updating the module(which was throwing error) to latest version.
Removed react-native_camera-roll, then installed it again to get the latest version, and the error was gone
