### ISSUE TITLE
group_name always empty in last version?

### ISSUE THREAD

**Issue by pierroo** [react-native-cameraroll/react-native-cameraroll#587]
This is the code I use:

```
CameraRoll.getPhotos({
            assetType: 'Photos',
            first: 9999999,
          })
```
          
This returns photos no problem, but the "group_name" is constantly an empty array.
It used to have the album name in it, which I then used to filter photos based on album picked and it worked perfectly.

I am on RN0.73.4
targetsdk 34 (Android 14)
latest react-native-cameraroll     7.4.1

when it used to work I was on RN0.69.12
targetsdk 33 (android 13)
cameraroll 5.2.0

So I don't know which one is at fault: RN / android OS version / camera roll

**Comment by Arjan-Zuidema** [comment]
You need to use the include param. See the docs 🙂

**Comment by pierroo** [comment]
Oh. That must have been added between the two versions, thank you for this!

**Comment by Abdullo-0901** [comment]
@Arjan-Zuidema  I am using the latest version, but group_name is coming back empty.
 {"group_name": [], "id": "CC95F08C-88C3-4012-9D6D-64A413D254B3/L0/001", "image": {"extension": null, "fileSize": 2808983, "filename": "IMG_0111.HEIC", "height": 3024, "playableDuration": null, "uri": "ph://CC95F08C-88C3-4012-9D6D-64A413D254B3/L0/001", "width": 4032}, "location": {"altitude": 4.583391486392184, "heading": 0, "latitude": 37.76007833333333, "longitude": -122.50956666666667, "speed": 0.5513811087502415}, "modificationTimestamp": 1727717667.547421, "sourceType": null, "subTypes": ["PhotoHDR"], "timestamp": 1522437259.365, "type": "image"}
 
 
 
    const albums = await CameraRoll.getAlbums({
      assetType: "All",
      albumType: "All",
    })

    const photosSave = await CameraRoll.getPhotos({
      first: 10,
      groupTypes: "All",
      groupName: "Screenshots",
      assetType: "Photos",
      include: ["fileSize", "filename", "imageSize", "location"],
    })
