### ISSUE TITLE
Get Album id in getAlbums

### ISSUE THREAD

**Issue by alainburindi** [react-native-cameraroll/react-native-cameraroll#592]
Is it possible to add the album id as part of the getAlbums response?

Expo MediaLibrary provides it: [https://docs.expo.dev/versions/latest/sdk/media-library/#album](https://docs.expo.dev/versions/latest/sdk/media-library/#album). But I am using this package to fetch albums as it allows me to filter by asset type

**Comment by Arjan-Zuidema** [comment]
Sure! I'd be willing to accept pull request. Unfortunately I personally don't have much time to implement this right now.

**Comment by alainburindi** [comment]
Hey @Arjan-Zuidema the PR #614 is ready for review

**Comment by Arjan-Zuidema** [comment]
Hi, I'm sorry I didn't had the time to check this. Will try to find time tomorrow!

**Comment by alainburindi** [comment]
Closed as it's working as expected
