### ISSUE TITLE
Apple rejection due to usage of PHAssetResource.fileSize (version 7.5.2)

### ISSUE THREAD

**Issue by xi3793-rpareek** [react-native-cameraroll/react-native-cameraroll#604]
We submitted our RN-App to apple-store which got rejected due to below reason.
We are using camera-roll version :- 7.5.2

===========================================================
Reason for rejection from Apple :- 

Guideline 2.5.1 - Performance - Software Requirements

The app uses or references the following non-public or deprecated APIs:

Selectors:
• **PHAssetResource.fileSize**

The use of non-public or deprecated APIs is not permitted, as they can lead to a poor user experience should these APIs change and are otherwise not supported on Apple platforms.

**Comment by Arjan-Zuidema** [comment]
This should be fixed in 7.6.0, can you confirm?
