### ISSUE TITLE
PrivacyInfo

### ISSUE THREAD

**Issue by Jignesh1303** [react-native-cameraroll/react-native-cameraroll#605]
Please add privacy info file for usage of non public api.

Found potentially required reason API usage '.creationDate' in './node_modules/@react-native-camera-roll/camera-roll/ios/RNCCameraRollManager.m'
Line numbers: 68 73 321 418 570 611

Apple wont allow app after 30th April.

**Comment by Arjan-Zuidema** [comment]
Linked pull request #609
