### ISSUE TITLE
not able to get blob for android images after getting photos from .getPhotos

### ISSUE THREAD

**Issue by yash-memwa** [react-native-cameraroll/react-native-cameraroll#607]
Thanks for this useful package 🙏

I have been struggling how to get blobs for android images.

I have been able to get blobs in iOS

Function for getting blob

```ts

 */
export const getBlob = async (fileUri: string) => {
  const response = await fetch(fileUri);
  const blob = await response.blob();
  return blob;
};

```

I had to append ph-upload in uri for iOS

```ts
let url = photo.node.image.uri;
if (Platform.OS === "ios") {
  url = `ph-upload${url.substring(2)}`;
}
```

However I could not find any resource online for how to get blob for android photos.
Uris are coming in this format: `content://media/external/file/1000000023`

Any pointers will be really appreciated.

**Comment by Arjan-Zuidema** [comment]
Getting blob data is not a function of this package, check out this package instead: https://github.com/RonRadtke/react-native-blob-util

**Comment by PrgrmmrOleg** [comment]
@yash-memwa try this solution to get the real file path

```
import RNFS from "react-native-fs";
...
const res = await RNFS.stat(uri);
const filePath = `file://${res.originalFilepath}`;
...
```

PS. I see that [react-native-blob-util](https://github.com/RonRadtke/react-native-blob-util) also has a stat function. Didn't test it. You can try it too
