### ISSUE TITLE
[Error: The operation couldn’t be completed. (PHPhotosErrorDomain error -1.)]

### ISSUE THREAD

**Issue by giapmn-1380** [react-native-cameraroll/react-native-cameraroll#610]
Hello,

I'm downloading the image with ReactNativeBlobUtil and then trying to save it using this lib. And then I want save file into camera roll.
Example:
![Screenshot 2024-04-16 at 15 48 38](https://github.com/react-native-cameraroll/react-native-cameraroll/assets/30829812/aeb08552-a5d9-4fb3-873e-a682e7fd5783)

Return error: 
`[Error: The operation couldn’t be completed. (PHPhotosErrorDomain error -1.)]`

Evidance: 

https://github.com/react-native-cameraroll/react-native-cameraroll/assets/30829812/8aeb6f17-9779-4a4c-897c-2fa7ac9c438d

Here's my version information:
`"react-native": "0.72.3",`
`"@react-native-camera-roll/camera-roll": "^7.5.2",`

**Comment by giapmn-1380** [comment]
> 2024-04-17 15:45:16.855021+0700 INSHARE[33530:6377858] [PhotoKit] PHExternalAssetResource: Unable to issue sandbox extension for /var/mobile/Containers/Data/Application/421C81AF-D6BB-4555-BF52-6A759D38C867/Downloads/写真②。。。。.jpg (hash=2361612238518302885)
> 2024-04-17 15:45:16.878325+0700 INSHARE[33530:6377753] [javascript] 'Error saving photo to camera roll', [Error: The operation couldn’t be completed. (PHPhotosErrorDomain error -1.)]

=> Log in Xcode

**Comment by giapmn-1380** [comment]
I'm try test on Simulator, error still occurs

![Screenshot 2024-04-17 at 16 08 08](https://github.com/react-native-cameraroll/react-native-cameraroll/assets/30829812/33b1cf10-e97e-4301-a4e9-c8bf24da5d2a)

**Comment by giapmn-1380** [comment]
I'm try download another image on Simulator => save success. But on device physical, iphone 11 => error still occurs

![Screenshot 2024-04-17 at 16 18 35](https://github.com/react-native-cameraroll/react-native-cameraroll/assets/30829812/a3c40d58-5037-46ef-b948-ad08701c80d9)

**Comment by Arjan-Zuidema** [comment]
Try moving/copying the file to a temp directory before saving it to the camera roll.

**Comment by giapmn-1380** [comment]
@Arjan-Zuidema Yes, I change folder save when download. From `Download` folder -> `Document` folder

![Screenshot 2024-04-17 at 17 44 26](https://github.com/react-native-cameraroll/react-native-cameraroll/assets/30829812/bbd8444f-1d14-4c6b-aece-b52d3a3ef7d2)

**Comment by Arjan-Zuidema** [comment]
Documents folder does work?

**Comment by giapmn-1380** [comment]
> Documents folder does work?
Yes, it work

**Comment by Arjan-Zuidema** [comment]
So it seems a permissions issue. Why not use the documents folder. Or a temp directory?

**Comment by giapmn-1380** [comment]
Yep, here is latest solution for both android, ios:
`const saveDir = Device.isAndroid ? fs.dirs.DownloadDir : fs.dirs.DocumentDir`

Thanks,
