### ISSUE TITLE
 Task :react-native-camera-roll_camera-roll:packageDebugResources FAILED

### ISSUE THREAD

**Issue by igorhtech** [react-native-cameraroll/react-native-cameraroll#611]
Android 8.1
React-Native 73.2
Ubuntu 22.04

FAILURE: Build failed with an exception.

* What went wrong:
A problem was found with the configuration of task ':react-native-camera-roll_camera-roll:packageDebugResources' (type 'MergeResources').
  - Gradle detected a problem with the following location: '/home/igor/projetos/app-htech/node_modules/@react-native-camera-roll/camera-roll/android/build/generated/res/resValues/debug'.
    
    Reason: Task ':react-native-camera-roll_camera-roll:packageDebugResources' uses this output of task ':@react-native-camera-roll_camera-roll:generateDebugResValues' without declaring an explicit or implicit dependency. This can lead to incorrect results being produced, depending on what order the tasks are executed.
    
    Possible solutions:
      1. Declare task ':@react-native-camera-roll_camera-roll:generateDebugResValues' as an input of ':react-native-camera-roll_camera-roll:packageDebugResources'.
      2. Declare an explicit dependency on ':@react-native-camera-roll_camera-roll:generateDebugResValues' from ':react-native-camera-roll_camera-roll:packageDebugResources' using Task#dependsOn.
      3. Declare an explicit dependency on ':@react-native-camera-roll_camera-roll:generateDebugResValues' from ':react-native-camera-roll_camera-roll:packageDebugResources' using Task#mustRunAfter.
    
    For more information, please refer to https://docs.gradle.org/8.3/userguide/validation_problems.html#implicit_dependency in the Gradle documentation.

**Comment by Arjan-Zuidema** [comment]
Did you use manual installation? If so, try removing the package and use automatic installation

**Comment by igorhtech** [comment]
I tried both installation methods.

**Comment by rryyy** [comment]
> I tried both installation methods.

Did you resolve this issue? I am encountering the same

**Comment by rryyy** [comment]
> Did you use manual installation? If so, try removing the package and use automatic installation

This helps solve the problem for me, if anyone encountering the same issue. Thank you
