### ISSUE TITLE
App crash with error Invariant Violation: TurboModuleRegistry.getEnforcing(...): 'RNCCameraRoll' 

### ISSUE THREAD

**Issue by Jakub-Owczarzak** [react-native-cameraroll/react-native-cameraroll#612]
Hello after installation of package app crashes. 

Error Message 
Invariant Violation: TurboModuleRegistry.getEnforcing(...): 'RNCCameraRoll' could not be found. Verify that a module by this name is registered in the native binary., js engine: hermes
 ERROR  Invariant Violation: "main" has not been registered. This can happen if:
* Metro (the local dev server) is run from the wrong folder. Check if Metro is running, stop it and restart it in the current project.

packag.json dependecies 
  "dependencies": {
    "@expo/metro-runtime": "~3.1.3",
    "@expo/vector-icons": "^13.0.0",
    "@hookform/resolvers": "^3.3.4",
    "@react-native-camera-roll/camera-roll": "^7.5.2",
    "@react-native-community/datetimepicker": "7.2.0",
    "@react-native-picker/picker": "2.4.10",
    "@react-navigation/bottom-tabs": "^6.5.20",
    "@react-navigation/drawer": "^6.6.15",
    "@react-navigation/native": "^6.1.17",
    "@react-navigation/native-stack": "^6.9.26",
    "@reduxjs/toolkit": "^2.2.3",
    "@unimodules/core": "^7.1.2",
    "babel-plugin-module-resolver": "^5.0.0",
    "expo": "^49.0.23",
    "expo-app-loading": "^1.1.2",
    "expo-font": "~11.4.0",
    "expo-image-picker": "~14.3.2",
    "expo-linear-gradient": "~12.3.0",
    "expo-splash-screen": "~0.20.5",
    "expo-status-bar": "~1.6.0",
    "install": "^0.13.0",
    "react": "18.2.0",
    "react-hook-form": "^7.51.3",
    "react-native": "0.72.10",
    "react-native-date-picker": "^5.0.1",
    "react-native-gesture-handler": "~2.12.0",
    "react-native-reanimated": "~3.3.0",
    "react-native-safe-area-context": "4.6.3",
    "react-native-screens": "~3.22.0",
    "react-native-unimodules": "^0.14.10",
    "react-native-vector-icons": "^10.0.3",
    "react-native-web": "~0.19.6",
    "react-redux": "^9.1.0",
    "styled-components": "^6.1.8",
    "zod": "^3.22.4"
  },

**Comment by jahirfiquitiva** [comment]
I'm facing the same issue but when building for react-native web 😕

**Comment by Arjan-Zuidema** [comment]
This package does not support react-native-web
