### ISSUE TITLE
no such column error when saving videos on android

### ISSUE THREAD

**Issue by edasazak** [react-native-cameraroll/react-native-cameraroll#613]
Hello, I get the below error when I save videos in Android. Even though the video is saved to device, I always get this error. There is no problem when saving images.

**Issue persists on versions below Android API 29.**

"@react-native-camera-roll/camera-roll": "^7.5.2",
"react-native": "0.73.4",

- Error:

`
[Error: no such column: orientation (code 1): , while compiling: SELECT _id, mime_type, bucket_display_name, datetaken, date_added, date_modified, width, height, _size, _data, orientation FROM video WHERE (_id=?)]
`

**Comment by Arjan-Zuidema** [comment]
Can you post some code what you are doing exactly?

**Comment by edasazak** [comment]
```javascript
const TEST_MP4_FILE =
    'https://test-videos.co.uk/vids/bigbuckbunny/mp4/h264/1080/Big_Buck_Bunny_1080_10s_5MB.mp4';
    
ReactNativeBlobUtil.config({
    fileCache: true,
    appendExt: 'mp4',
  })
    .fetch('GET', TEST_MP4_FILE)
    .then(async res => {
      if (Platform.OS === 'android') {
        if (!(await hasAndroidGalleryPermission())) {
          return;
        }
      }
      CameraRoll.saveAsset(res.data, {
        album: albumName,
      })
        .then(res => console.log(res))
        .catch(err => console.log(err));
    })
    .catch(error => console.log(error));
```

What I want to do here is basically, cache a file and then save the file to the device's Camera Roll if permissions are granted.

**Comment by iita71737** [comment]
Excuse me, any updated? thx

**Comment by edasazak** [comment]
I tried with the latest update but I still get the same error on versions below Android API 29, unfortunately
