### ISSUE TITLE
Successfully saved the image to the album in iOS 17.4.1, but encountered an error

### ISSUE THREAD

**Issue by TallNutAlt** [react-native-cameraroll/react-native-cameraroll#622]
https://github.com/react-native-cameraroll/react-native-cameraroll/assets/109561878/13c4bb7d-12d0-46e1-8893-a5fce2db2eb3

**Comment by Arjan-Zuidema** [comment]
It's not clear what's happening here. Could you provide some more context and info?

**Comment by TallNutAlt** [comment]
> 目前尚不清楚这里发生了什么。您能否提供更多背景信息和信息？

https://github.com/react-native-cameraroll/react-native-cameraroll/issues/617
与他一致

**Comment by iita71737** [comment]
iOS 17.4.1 
CameraRoll.save(source, { type: "photo", album: 'dev' })

[Error: 無法完成作業。（PHPhotosErrorDomain錯誤-1 。）] error

**Comment by Arjan-Zuidema** [comment]
Can you explain what's happening and what you are doing? Not really understanding your language

**Comment by iita71737** [comment]
> Can you explain what's happening and what you are doing? Not really understanding your language.
> 
> What is `source` here?

I give u more info, thanks.

**Comment by Arjan-Zuidema** [comment]
Ah ok, duplicate of #613
