### ISSUE TITLE
> Task :react-native-camera-roll_camera-roll:compileDebugJavaWithJavac FAILED  Deprecated Gradle features were used in this build, making it incompatible with Gradle 9.0.

### ISSUE THREAD

**Issue by jibo001** [react-native-cameraroll/react-native-cameraroll#629]

**Comment by jibo001** [comment]
"react-native": "0.73.7"
"@react-native-camera-roll/camera-roll": "^7.6.1"
error :CameraRollModule is not abstract, and does not override the abstract method removeListeners(double) in NativeCameraRollModuleSpec.

**Comment by aleksey-golovanov** [comment]
This is the same issue https://github.com/react-native-cameraroll/react-native-cameraroll/issues/600

**Comment by tdammy92** [comment]
any fix for this ?? @jibo001 what worked for you ?
