### ISSUE TITLE
`ph://` not loading anymore after upgrading to react-native 0.74/new-arch

### ISSUE THREAD

**Issue by mrousavy** [react-native-cameraroll/react-native-cameraroll#631]
Hey all!

I see that react-native-cameraroll implements a custom [`RNCAssetsLibraryRequestHandler.m`](https://github.com/react-native-cameraroll/react-native-cameraroll/blob/master/ios/RNCAssetsLibraryRequestHandler.m) module which should be responsible for loading `ph://` and `asset-library://` assets (images/videos).

This worked perfectly fine and allowed me to use such `ph://` assets as sources for the `<Image>` component before, but now after upgrading to the new architecture (on react-native 0.74) it will fail to load `ph://` assets:

```
No suitable image URL loader found for ph://.......
```

I'm thinking that the module might just be ignored? Any ideas why this might break and what could fix it?

<img src="https://github.com/react-native-cameraroll/react-native-cameraroll/assets/15199031/383e7c2f-92d9-46eb-9c3e-41adf162f138" width="55%" />

cc @WoLewicki since you migrated that over to the new arch in https://github.com/react-native-cameraroll/react-native-cameraroll/pull/460

**Comment by mrousavy** [comment]
So CodeGen supports adding custom Protocol providers (image loader, data decoder and url request handlers) - see [`generateCustomURLHandlers(..)`](https://github.com/facebook/react-native/blob/355fe7717cf4b16aefa17345d3ab7067ca489991/packages/react-native/scripts/codegen/generate-artifacts-executor.js#L542-L586).

I'm just not quite sure how that is expected to be implemented...

**Comment by AliRehman7141** [comment]
I'm still facing the issue with
```
"@react-native-camera-roll/camera-roll": "^7.8.3",
"react": "18.3.1",
"react-native": "0.75.3",
```
