### ISSUE TITLE
Configuration Issues with Latest Versions

### ISSUE THREAD

**Issue by hypesol** [react-native-cameraroll/react-native-cameraroll#637]
This is my package.json

    "@react-native-camera-roll/camera-roll": "^7.8.1",
    "@react-navigation/bottom-tabs": "^6.5.20",
    "@react-navigation/drawer": "^6.6.15",
    "@react-navigation/native": "^6.1.17",
    "@react-navigation/native-stack": "^6.9.26",
    "@reduxjs/toolkit": "^2.2.5",
    "aws-sdk": "^2.1637.0",
    "axios": "^1.7.2",
    "d3-shape": "^3.2.0",
    "formik": "^2.4.6",
    "react": "18.3.1",
    "react-hook-form": "^7.51.5",
    "react-native": "^0.74.2",

![image](https://github.com/react-native-cameraroll/react-native-cameraroll/assets/14737991/45ebda87-7590-43ce-b760-67bc0d133944)

this is settings.gradle file

![image](https://github.com/react-native-cameraroll/react-native-cameraroll/assets/14737991/59153cf2-a896-4d64-947c-45033f1b99b8)

this is android/app/build.gradle file

![image](https://github.com/react-native-cameraroll/react-native-cameraroll/assets/14737991/038f41c2-afd3-4f82-8ac1-b7d79a642769)

This is MainApplication.kt file

![image](https://github.com/react-native-cameraroll/react-native-cameraroll/assets/14737991/c0b22c45-c942-4c67-abbf-6794b60e378f)

everything is according to documentation but i am getting errors

![image](https://github.com/react-native-cameraroll/react-native-cameraroll/assets/14737991/01aec419-95f6-4e76-8e85-5429d8301c64)

* What went wrong:
A problem was found with the configuration of task ':react-native-camera-roll_camera-roll:packageDebugResources' (type 'MergeResources').
  - Gradle detected a problem with the following location: '/Users/ejaz/code/seecard_mobile_app/node_modules/@react-native-camera-roll/camera-roll/android/build/generated/res/resValues/debug'.

    Reason: Task ':react-native-camera-roll_camera-roll:packageDebugResources' uses this output of task ':@react-native-camera-roll_camera-roll:generateDebugResValues' without declaring an explicit or implicit dependency. This can lead to incorrect results being produced, depending on what order the tasks are executed.

    Possible solutions:
      1. Declare task ':@react-native-camera-roll_camera-roll:generateDebugResValues' as an input of ':react-native-camera-roll_camera-roll:packageDebugResources'.
      2. Declare an explicit dependency on ':@react-native-camera-roll_camera-roll:generateDebugResValues' from ':react-native-camera-roll_camera-roll:packageDebugResources' using Task#dependsOn.
      3. Declare an explicit dependency on ':@react-native-camera-roll_camera-roll:generateDebugResValues' from ':react-native-camera-roll_camera-roll:packageDebugResources' using Task#mustRunAfter.

Can you please help me to fix these issues
Thanks

**Comment by Arjan-Zuidema** [comment]
Try automatic installation. Looks like you used manual installation

**Comment by hypesol** [comment]
I have tried that but in that case i got this error

error: unknown command 'link'

i google this issue and got the results that automatic linking is not supporting after 0.69 version
now i am working in latest react native version "0.74.2"

can you please guide me for this version

**Comment by Arjan-Zuidema** [comment]
Link command is not needed, it says in the docs that linking is not needed 🙂 
> Linking should be automatic since react-native version 0.60. Below are instructions if auto linking does not work.

**Comment by easeebiz** [comment]
Hi
@Arjan-Zuidema i am also facing the same issue. I have tried manual and automatic both but not working. I have also download and installed example code but again could not configure. According to documentation i have added all lines in relevant files as above @hypesol  has mentioned. Please help me.

**Comment by easeebiz** [comment]
Hi @hypesol 
if you got solution please share in this thread. I need this library implementation asap. thanks

**Comment by Arjan-Zuidema** [comment]
> Hi @Arjan-Zuidema i am also facing the same issue. I have tried manual and automatic both but not working. I have also download and installed example code but again could not configure. According to documentation i have added all lines in relevant files as above @hypesol has mentioned. Please help me.

Do not add anything, as documented, just use automatic install (by doing nothing)

**Comment by easeebiz** [comment]
Can you please explain the about Automatic Install
i have installed using this command
yarn add @react-native-camera-roll/camera-roll

only this is automatic install

or i need to use this command

react-native link @react-native-camera-roll/camera-roll && npx pod-install

if i used above command this give me error with or without "link"

**Comment by Arjan-Zuidema** [comment]
That is not automatic install, that is for when automatic is not working, MOSTLY automatic

**Comment by easeebiz** [comment]
Still confused let me make this simple
If i install this library using this command

yarn add @react-native-camera-roll/camera-roll

this will be automatic install and after that i did not add anything in any file like
settings.gradle
android/app/build.gradle
MainApplication.kt 

I do not need to follow these steps
![image](https://github.com/react-native-cameraroll/react-native-cameraroll/assets/172377336/fdf43864-59ab-495a-bd70-f1fef69c5d17)

simple install and use the library am i right?

**Comment by easeebiz** [comment]
Thanks ... this working now
