### ISSUE TITLE
[BUG]: iOS getPhotoThumbnail crashed the app on corrupted file 

### ISSUE THREAD

**Issue by iserzh** [react-native-cameraroll/react-native-cameraroll#638]
### Version

7.8.1

### What platforms are you having the problem on?

iOS

### System Version

17.5.1

### On what device are you experiencing the issue?

Real device, Simulator

### What happened?

iOS Application crashes when calling `getPhotoThumbnail` with the dead video file from iCloud. 

Error details:
```
NSInvalidArgumentException __58-[RNCCameraRoll getPhotoThumbnail:options:resolve:reject:]_block_invoke_2
** -[__NSPlaceholderDictionary initWithObjects:forKeys:count:]: attempt to insert nil object from objects[0]
```

### Reproduction

It's hard to reproduce because there are no steps to make the video file dead as it bugs itself.

Here is how this asset might look
<img src="https://github.com/react-native-cameraroll/react-native-cameraroll/assets/11062353/72da47ea-8df2-4cbd-94f2-e52df7b7a239" width="300">

Here is how this call looks

```typescript
CameraRoll.getPhotoThumbnail(id, {
  targetSize: {
    width: 128,
    height: 128,
  },
  allowNetworkAccess: true,
  quality: 0,
})
```

**Comment by frenbergFNX** [comment]
I see something similar. The app crash if I try to save an invalid file file with CameraRoll.saveAsset(). This resulted in an error before using CameraRoll.save that we could fetch and give feedback to user.

```
    Exception was thrown:
    NSInvalidArgumentException
    *** -[NSFileManager fileSystemRepresentationWithPath:]: nil or empty path argument
    (
    	0   CoreFoundation                      0x0000000114ab4521 __exceptionPreprocess + 226
    	1   libobjc.A.dylib                     0x000000010d0ce7e8 objc_exception_throw + 48
    	2   Foundation                          0x0000000115e557b8 _NSFileSystemRepresentationWithPath + 445
    	3   PhotoLibraryServicesCore            0x00000001209ce55c PLGetSandboxExtensionTokenWithFlags + 69
    	4   Photos                              0x000000010e81b0d4 -[PHAssetCreationRequest encodeToXPCDict:] + 758
    	5   Photos                              0x000000010e795e38 addChangeRequests + 311
    	6   Photos                              0x000000010e7926de -[PHPerformChangesRequest encodeWithCoder:] + 654
    	7   Foundation                          0x0000000115f87ea4 -[NSXPCEncoder _encodeObject:] + 448
    	8   Foundation                          0x0000000115df06bc _NSXPCSerializationAddInvocationWithOnlyObjectArgumentsArray + 96
    	9   Foundation                          0x0000000115f883b8 -[NSXPCEncoder _encodeInvocationObjectArgumentsOnly:count:typeString:selector:isReply:into:] + 192
    	10  Foundation                          0x0000000115f7e48f -[NSXPCConnection _sendInvocation:orArguments:count:methodSignature:selector:withProxy:] + 1831
    	11  Foundation                          0x0000000115f7db57 -[NSXPCConnection _sendSelector:withProxy:arg1:arg2:] + 132
    	12  Foundation                          0x0000000115f930ba _NSXPCDistantObjectSimpleMessageSend2 + 63
    	13  PhotoLibraryServicesCore            0x00000001209b0733 __70+[PLAssetsdPhotoKitClient sendChangesRequest:usingProxyFactory:reply:]_block_invoke.13 + 489
    	14  PhotoLibraryServicesCore            0x0000000120a06962 __74-[PLAssetsdServiceProxyFactory remoteObjectProxyWithErrorHandler:handler:]_block_invoke_2 + 117
```

**Comment by frenbergFNX** [comment]
Sorry, not related... my problem appeared when @mrousavy alias Magic Marc changed from
        UIImage *image = [UIImage imageWithData:data];
        assetRequest = [PHAssetChangeRequest creationRequestForAssetFromImage:image];
to 
          assetRequest = [PHAssetChangeRequest creationRequestForAssetFromImageAtFileURL:inputURI];

😅

**Comment by mrousavy** [comment]
i'll take that alias

**Comment by Dentoty** [comment]
I can confirm that this has been happening in my application too. Again using "allowNetworkAccess: true".

**Comment by jp-23** [comment]
@Dentoty @iserzh how do you get a video into a corrupted state?

**Comment by iserzh** [comment]
@jp-23 I would be very grateful if I could find out more about this. I have noticed that some files stored on iCloud are becoming corrupted, although I can confirm that at least seven users of my application are also experiencing this problem. Perhaps we could try using a try/catch block to see if this helps?
