### ISSUE TITLE
Can't save a file with .mp4 extension

### ISSUE THREAD

**Issue by ivaniuk7531** [react-native-cameraroll/react-native-cameraroll#646]
I use this method 

`save(my_path_to_file, {
            type: 'video',
            album: my_album,
          })
`

and get this error below

[Error: The operation couldn’t be completed. (PHPhotosErrorDomain error 3302.)]

The path to the file is valid and doesn't include special characters or spaces.

My "@react-native-camera-roll/camera-roll" version is 7.8.3. Also, I tried to use the latest version of this package but got the same behavior.
My  "react-native" version is 0.72.14.

**Comment by Arjan-Zuidema** [comment]
Are you sure it's a valid video file? `PHPhotosErrorDomain error 3302` can also mean that there is not enough space on the device

**Comment by dbs-tuan** [comment]
> I use this method
> 
> `save(my_path_to_file, { type: 'video', album: my_album, }) `
> 
> and get this error below
> 
> [Error: The operation couldn’t be completed. (PHPhotosErrorDomain error 3302.)]
> 
> The path to the file is valid and doesn't include special characters or spaces.
> 
> My "@react-native-camera-roll/camera-roll" version is 7.8.3. Also, I tried to use the latest version of this package but got the same behavior. My "react-native" version is 0.72.14.

you could try this code out:

     import RNFS from 'react-native-fs';

      const _mimeType = await fetch(uri, { method: 'HEAD' });
      const mimeType = _mimeType.headers.get('Content-Type')?.split('/');

      if (mimeType) {
        // Get today's date to add the time suffix in filename
        const date = new Date();
        const fileType = mimeType[0] === 'image' ? 'image' : 'video';
        const fileExtension = mimeType[1];

        const fileName = `${fileType}-${Math.floor(
          date.getTime() + date.getSeconds() / 2
        )}.${fileExtension}`;

        const path =
          (isAndroid()
            ? RNFS.DownloadDirectoryPath
            : RNFS.DocumentDirectoryPath) + `/${fileName}`;

        RNFS.downloadFile({
          fromUrl: uri,
          toFile: path,
        })
