### ISSUE TITLE
Media download not working in Android 15 (works fine on lower android versions)

### ISSUE THREAD

**Issue by 1880akshay** [react-native-cameraroll/react-native-cameraroll#656]
saveAsset promise neither resolves nor rejects and hence the download functionality is stuck. This issue is only happening in Android 15.

I tried to debug the issue and found that FileUtils.copy() method is being called in the CameraRollModule.java file which is somehow causing the issue. The code does not reach the next line and is stuck on this method call.

Here is a minimum reproducible example of the issue: [https://github.com/1880akshay/RN_NewArch_TextInput/tree/media-download](https://github.com/1880akshay/RN_NewArch_TextInput/tree/media-download)

Environment:
React native: 0.74.3
@react-native-camera-roll/camera-roll: 7.8.3
react-native-blob-util: 0.19.11

The issue is happening on both old and new architectures of react native.
I also tried setting target and compile sdk version to 35 but the issue still persists.

Video of the issue:

https://github.com/user-attachments/assets/899037db-c785-4444-9857-cfd744519ddb

**Comment by 1880akshay** [comment]
Any solutions for this issue? @bartolkaruza or anyone who knows?

**Comment by Arjan-Zuidema** [comment]
Hi @1880akshay Thanks for reporting this, and providing a reproducible repo. Unfortunately I don't have much time but I will do my best. Maybe I can look into it next Friday.

**Comment by 1880akshay** [comment]
Hi @Arjan-Zuidema , did you get time to look into this?

**Comment by Arjan-Zuidema** [comment]
@1880akshay Sorry, unfortunately not. Im very busy, and only have time on Fridays

**Comment by 1880akshay** [comment]
@Arjan-Zuidema oh okay, so can someone else look into this? I tried finding the root cause but it goes down to the FileUtils.copy() method provided by android. I was not able to debug any further.

**Comment by Arjan-Zuidema** [comment]
I tried your repo and it works like it should. After pressing download I get the `Download success` in console. Did you use a real device or simulator? Android 15 is not released yet, so I can only test on a simulator
