### ISSUE TITLE
Compliance with Google Play's Photo and Video Permissions policy

### ISSUE THREAD

**Issue by webchun** [react-native-cameraroll/react-native-cameraroll#659]
Got this problem today when pushing a new update for my app

There is upcoming android deadline regarding READ_MEDIA_IMAGES permission. As per new google You can only use READ_MEDIA_PERMISSION permission if your app is a gallery app, or if its core functionality is editing, managing, and maintaining photos. Otherwise, you must migrate to the [Android photo picker](https://android-developers.googleblog.com/2023/04/photo-picker-everywhere.html),
or a photo picker of your choice.

Now apps that are using this for picking up profile pictures or other non-core features won't be able to use READ_MEDIA_IMAGES permission after the deadline.

<img width="480" alt="SCR-20240924-gwke" src="https://github.com/user-attachments/assets/6e61c849-4d98-4584-b97c-0ef7bee98e4e">

**Comment by darshan09200** [comment]
Related to #618
