### ISSUE TITLE
[IOS] Fix error "No suitable URL request handler found for ph-upload://..."

### ISSUE THREAD

**Issue by DarkShtir** [react-native-cameraroll/react-native-cameraroll#669]
Hi! 👋 
      
Firstly, thanks for your work on this project! 🙂

Today I used [patch-package](https://github.com/ds300/patch-package) to patch `@react-native-camera-roll/camera-roll@7.8.4` for the project I'm working on.

I have a problem with new arch on ios, to send images from camera-roll to server using fetch requests. I've got error "No suitable URL request handler found for ph-upload://...". I researched problem and understand that RNCPHAssetUploader not implement modulesConformingToProtocol in package.json file.

Here is the diff that solved my problem:

```diff
diff --git a/node_modules/@react-native-camera-roll/camera-roll/package.json b/node_modules/@react-native-camera-roll/camera-roll/package.json
index 141d393..17b415a 100644
--- a/node_modules/@react-native-camera-roll/camera-roll/package.json
+++ b/node_modules/@react-native-camera-roll/camera-roll/package.json
@@ -121,7 +121,8 @@
     "jsSrcsDir": "./src",
     "ios": {
       "modulesConformingToProtocol": {
-        "RCTImageURLLoader": "RNCPHAssetLoader"
+        "RCTImageURLLoader": "RNCPHAssetLoader",
+        "RCTURLRequestHandler": "RNCPHAssetUploader"
       }
     },
     "android": {
```
Thank you for library development.
Best regards

**Comment by Arjan-Zuidema** [comment]
Hey @DarkShtir 

If you can make a PR with this change we can create a release. Seems like a good fix 🙂

**Comment by DarkShtir** [comment]
@Arjan-Zuidema Ready https://github.com/react-native-cameraroll/react-native-cameraroll/pull/670 and thanks)
