### ISSUE TITLE
Loading all photos that show in Google Photos app and iOS Photos app

### ISSUE THREAD

**Issue by thekevinbrown** [react-native-cameraroll/react-native-cameraroll#72]
# Question

A user of ours has an Oppo phone. In the Google Photos app she has `Back up & sync` turned on, so Google Photos seamlessly shows all the photos in her google drive.

The Oppo photos app only shows 4 photos, which are the same photos we currently get from `getPhotos`.

Is there a way to get `getPhotos` to return the photos that are in her Google Drive, or a way to configure her phone so that it'll sync the photos locally and they can be found by `getPhotos`?

**Comment by albullington** [comment]
Following this -- we've had users request for their Google Photos to show up as well.

**Comment by thekevinbrown** [comment]
We've also had a report from an iOS user that they can't find all their photos in our app. They had enabled Settings -> Photos -> Optimise iPhone Storage instead of Download and Keep Originals.

We should look into how we can access cloud stored photos for users on both platforms.

**Comment by pierroo** [comment]
I might be late to the party but... did anyone find a solution to this? :) @thekevinbrown @albullington

**Comment by thekevinbrown** [comment]
Not that I know of. Our advice to users is that the Google Photos app is special and what's shown there is different than what's on the device.

**Comment by Arjan-Zuidema** [comment]
Closing this since this falls out of the scope of this project. Google Photos app cannot be directly communicated with.
