### ISSUE TITLE
[IOS] CameraRoll.getPhotos() returns photos with duplicates

### ISSUE THREAD

**Issue by fctmolina1135** [react-native-cameraroll/react-native-cameraroll#75]
# Bug

- CameraRoll.getPhotos in IOS returns photos with duplicates of the photos.

![Screen Shot 2019-08-07 at 2 35 56 PM](https://user-images.githubusercontent.com/22470020/62600889-9fa61880-b922-11e9-939d-9513a902ec08.png)

## Environment info

React native info output:

```bash
React Native Environment Info:
    System:
      OS: macOS 10.14.5
      CPU: (4) x64 Intel(R) Core(TM) i5-4308U CPU @ 2.80GHz
      Memory: 32.09 MB / 8.00 GB
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 12.4.0 - /usr/local/bin/node
      Yarn: 1.16.0 - /usr/local/bin/yarn
      npm: 6.9.0 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 12.2, macOS 10.14, tvOS 12.2, watchOS 5.2
      Android SDK:
        API Levels: 23, 28, 29
        Build Tools: 28.0.3, 29.0.0
        System Images: android-28 | Google Play Intel x86 Atom, android-29 | Intel x86 Atom_64
    IDEs:
      Xcode: 10.2.1/10E1001 - /usr/bin/xcodebuild
    npmPackages:
      react: ^16.8.3 => 16.8.6 
      react-native: ^0.59.8 => 0.59.9 
    npmGlobalPackages:
      create-react-native-app: 2.0.2
      react-native-cli: 2.0.1
```

## Steps To Reproduce

Describe what you expected to happen:

1. CameraRoll.getPhotos should not return an object containing the photos and the duplicates.

## Reproducible sample code
Number of photos in phone should be less than the value of `first` in CameraRoll Params

CameraRoll Params:
```
ios: {
    first: 30,
    assetType: 'Photos',
    groupTypes: 'All',
  }
```

Code for getting photos:
```
CameraRoll.getPhotos(// config)
   .then(data => console.log(data)
   .catch(err => console.log(err));
```

Expected output: 
data returned should be only the photos but the data returned contains the photos and its duplicates.

**Comment by thekevinbrown** [comment]
Do you have duplicates in the camera roll? Can you post a screenshot of what you see in the Photos app?

**Comment by fctmolina1135** [comment]
@thekevinbrown Yes, the duplicates are in the camera roll.
This is what I see in the Photos App

![Screen Shot 2019-08-22 at 9 32 44 AM](https://user-images.githubusercontent.com/22470020/63479222-eb7ac500-c4bf-11e9-9f9a-d2f6be38a754.png)

**Comment by mohaned2014** [comment]
i have the same issue

**Comment by dev2612** [comment]
I am facing a problem with videos specifically. In my scenario, I have to save a file on cameraRoll and pick the last saved file from the camera roll to share it further.

iOS cameraRoll retains the video's original metadata and thus save the file with createdate and not with today's Date.

So when I pick the last saved file, I get someother file instead of the video I just saved to cameraRoll

Any help in this regards will be highly appreciable. it is bit Urgent. Thanks in advance.

**Comment by fokoz** [comment]
It is duplicate because when you are fetching with `groupTypes: 'All'`, it will return every albums and images inside them. In your example case may have 2 albums: Recent Photos and All Photos.

**Comment by jzyds** [comment]
I solved this problem by upgrading react-native-cameraroll version

**Comment by stevejboyer** [comment]
> It is duplicated because when you are fetching with `groupTypes: 'All'`, it will return every albums and images inside them. In your example case may have 2 albums: Recent Photos and All Photos.

Yes I found this was happening for me due to having some photos marked as Favorite so they were in the "Favorites" album, and getting by `groupTypes: 'All'` was getting duplicates.

**Comment by fctmolina1135** [comment]
> > It is duplicated because when you are fetching with `groupTypes: 'All'`, it will return every albums and images inside them. In your example case may have 2 albums: Recent Photos and All Photos.
> 
> Yes I found this was happening for me due to having some photos marked as Favorite so they were in the "Favorites" album, and getting by `groupTypes: 'All'` was getting duplicates.

@stevejboyer then what should I set the groupTypes to in order to get all photos without them being duplicated?

**Comment by stevejboyer** [comment]
> > > It is duplicated because when you are fetching with `groupTypes: 'All'`, it will return every albums and images inside them. In your example case may have 2 albums: Recent Photos and All Photos.
> > 
> > 
> > Yes I found this was happening for me due to having some photos marked as Favorite so they were in the "Favorites" album, and getting by `groupTypes: 'All'` was getting duplicates.
> 
> @stevejboyer then what should I set the groupTypes to in order to get all photos without them being duplicated?

I'm still actively working on figuring this whole thing out. For a while I was teaching myself Swift (I  come from the web, not native app development), and writing my own photos getter, because the native one is so buggy.

For now I've found if I put groupTypes to 'Album' or 'Library' it will get photos from a specific custom-named album, but not Favorites or another built-in album.

Looks like I was getting duplicates from the Favorites album when I asked for:
groupTypes: 'All',
groupName: 'UserLibrary'
Once I set groupName to undefined it actually stopped returning duplicates, so perhaps I was incorrect earlier about it being from groupTypes: 'All'.

Like I said, still figuring this stuff out :/

**Comment by ederelk** [comment]
I am having the same issue

**Comment by fctmolina1135** [comment]
I tried to use other groupTypes if I use them there are no photos returned by the getPhotos() method

**Comment by bartolkaruza** [comment]
> I solved this problem by upgrading react-native-cameraroll version

Can anyone confirm this is still happening on the latest version of cameraroll?

**Comment by sharifashraful** [comment]
it returns same image with different pages.. when i add filter by Images.Media._ID it fix duplicate image return issue..

**Comment by nihp** [comment]
I am getting an error **undefined is not an object (evaluating '_cameraroll.CameraRoll.getPhotos)**

Did anyone faced this issue?

**Comment by nihp** [comment]
Image is flickering while loading and returned all images. After some time if I navigate to the same screen it shows some images.

**Comment by bartolkaruza** [comment]
related to #41
