### ISSUE TITLE
Add support for media subtypes? (e.g. only return screenshots)

### ISSUE THREAD

**Issue by Jarred-Sumner** [react-native-cameraroll/react-native-cameraroll#99]
# Feature Request

[`PHAssetMediaSubtype`](https://developer.apple.com/documentation/photokit/phassetmediasubtype) lets you filter results by things like screenshot, live photo, panoramic photo, HDR photo, etc.

## Why it is needed

This is helpful in apps that want to narrow the results to show specific types of photos/videos.

## Possible implementation

I have it working in a fork. Here's the most relevant commit: https://github.com/Jarred-Sumner/react-native-cameraroll/commit/585ddea18f31c699cd3f4b66d5c5b3ce925b6682

I don't have time to turn my fork into a PR and write tests for this right now, but I figured maybe this would be helpful to someone here.

**Comment by bartolkaruza** [comment]
We'll take a PR for this if anyone is up for it.
